"""Accessible lecture-term explorers for the ASTR 476 generators."""
from __future__ import annotations

import html


TERM_EXPLORER_CSS = """
.glossary-slide{align-content:start}.term-explorer{display:grid;grid-template-columns:minmax(220px,.7fr) minmax(0,1.8fr);gap:28px;align-items:stretch;min-height:58vh}.term-list{display:flex;flex-direction:column;gap:10px}.term-button{width:100%;padding:12px 14px;border:2px solid var(--line);border-radius:8px;background:#fff;color:var(--navy);font:700 1rem/1.25 Arial,sans-serif;text-align:left;cursor:pointer}.term-button:hover{border-color:var(--teal)}.term-button:focus-visible{outline:4px solid var(--gold);outline-offset:2px}.term-button[aria-selected="true"]{color:#fff;background:var(--teal);border-color:var(--teal)}.term-details{min-width:0}.term-detail{border:1px solid var(--line);border-radius:10px;padding:18px 22px;background:var(--paper);overflow:auto}.term-detail h3{margin:0 0 10px;color:var(--teal);font:700 1.35rem/1.2 Arial,sans-serif}.term-detail p{font-size:1rem;margin:9px 0}.term-detail[hidden]{display:none}@media(max-width:800px){.term-explorer{grid-template-columns:1fr}.term-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:520px){.term-list{grid-template-columns:1fr}}@media print{.term-explorer{display:block}.term-list{display:none}.term-detail[hidden]{display:block!important}.term-detail{break-inside:avoid;margin:12px 0}}
"""

TERM_EXPLORER_SCRIPT = """
<script>document.querySelectorAll("[data-term-explorer]").forEach((explorer)=>{const tabs=[...explorer.querySelectorAll('[role="tab"]')];const panels=[...explorer.querySelectorAll('[role="tabpanel"]')];const select=(tab)=>{tabs.forEach((item)=>item.setAttribute("aria-selected",String(item===tab)));panels.forEach((panel)=>{panel.hidden=panel.id!==tab.dataset.termTarget;});};tabs.forEach((tab,index)=>{tab.addEventListener("click",()=>select(tab));tab.addEventListener("keydown",(event)=>{if(!["ArrowDown","ArrowUp","ArrowRight","ArrowLeft","Home","End"].includes(event.key))return;event.preventDefault();const forward=event.key==="ArrowDown"||event.key==="ArrowRight";const nextIndex=event.key==="Home"?0:event.key==="End"?tabs.length-1:(index+(forward?1:-1)+tabs.length)%tabs.length;tabs[nextIndex].focus();select(tabs[nextIndex]);});});});</script>
"""

TERM_SETS = {
    1: [("Redshift", "The fractional change between observed and emitted wavelength after identifying the same spectral feature."), ("Scale factor", "The time-dependent relative size assigned to spatial separations between comoving observers in an FLRW model."), ("Cosmological redshift", "Wavelength stretching associated with the change in scale factor between emission and observation."), ("Peculiar velocity", "Motion relative to the local comoving expansion flow."), ("CMB frame", "A redshift reference frame corrected for the observer's motion relative to the microwave-background dipole.")],
    2: [("FLRW metric", "The homogeneous and isotropic spacetime geometry used to relate expansion history to photon paths."), ("Comoving distance", "The present-epoch radial coordinate separation obtained by integrating inverse expansion rate."), ("Luminosity distance", "The distance definition that makes bolometric flux obey the inverse-square relation."), ("Angular-diameter distance", "Physical transverse size divided by observed angular size."), ("Distance duality", "The relation D_L=(1+z)^2 D_A for transparent metric propagation with photon conservation.")],
    3: [("Type Ia supernova", "A thermonuclear stellar explosion used as a distance indicator after empirical standardization."), ("Standardizable candle", "An object whose intrinsic luminosity scatter is reduced using measured correlations rather than assumed identical luminosity."), ("Distance modulus", "The logarithmic difference between apparent and absolute magnitude."), ("Light-curve stretch", "A duration or shape parameter correlated with standardized Type Ia luminosity."), ("Absolute calibration", "The external distance scale that fixes standardized absolute magnitude and the Hubble-diagram intercept.")],
    4: [("Residual vector", "The ordered differences between observed supernova magnitudes and model predictions."), ("Covariance matrix", "The variances and pairwise correlated uncertainties of the ordered data vector."), ("Cholesky factorization", "A stable triangular decomposition of a positive-definite covariance used to whiten residuals."), ("Generalized least squares", "Least-squares estimation using the full inverse-covariance weighting implied by correlated errors."), ("Calibration mode", "A shared systematic shift that moves multiple supernova measurements coherently.")],
    5: [("Baryon acoustic oscillation", "The late-time clustering imprint of sound waves in the pre-recombination photon-baryon plasma."), ("Sound horizon", "The comoving distance an acoustic wave traveled before baryon drag ended."), ("Standard ruler", "A feature with calibrated physical length whose observed angular or redshift extent constrains geometry."), ("Volume-averaged distance", "The isotropic BAO combination D_V that mixes transverse area and radial depth."), ("Anisotropic BAO", "Separate use of transverse and radial clustering to constrain D_M/r_d and H r_d.")],
    6: [("Acoustic scale", "The angle subtended by the sound horizon at last scattering."), ("Sound horizon at recombination", "The comoving acoustic propagation distance evaluated near photon decoupling."), ("Last scattering", "The epoch when the photon mean free path became large enough for the CMB to free-stream."), ("Multipole", "An angular Fourier index whose scale is approximately inverse to angle on the sky."), ("Recombination model", "The ionization and thermal history needed to predict visibility and acoustic features.")],
    7: [("Weak lensing", "Small coherent distortions of background images produced by foreground gravitational potentials."), ("Cosmic shear", "The two-point statistical pattern of weak-lensing distortions across source galaxies."), ("Tangential shear", "The component of image distortion aligned tangentially around a foreground lens."), ("Critical surface density", "The lens-source geometry factor converting projected mass contrast into shear."), ("S8", "The compressed amplitude combination sigma8 sqrt(Omega_m/0.3) aligned with a common lensing degeneracy.")],
    8: [("Density contrast", "The fractional matter-density perturbation relative to the cosmic mean."), ("Growth factor", "The time-dependent amplitude of the linear growing mode, usually normalized at a chosen epoch."), ("Growth rate", "The logarithmic derivative f=d ln D/d ln a."), ("Redshift-space distortion", "Anisotropy in observed clustering caused by line-of-sight peculiar velocities."), ("f sigma8", "A growth observable combining the logarithmic growth rate with fluctuation amplitude.")],
    9: [("Likelihood", "The probability model for the observed data conditional on parameters and nuisance assumptions."), ("Prior", "The parameter distribution imposed before conditioning on the current data."), ("Posterior", "The parameter distribution proportional to likelihood times prior."), ("Nuisance parameter", "A required model parameter that affects the data but is not the primary scientific target."), ("Parameter degeneracy", "A direction in parameter space along which substantially different parameters predict similar data.")],
    10: [("Selection function", "The probability that an object with specified latent and observed properties enters the analyzed sample."), ("Malmquist bias", "Preferential inclusion of intrinsically brighter objects in a flux-limited sample."), ("Eddington bias", "Net migration across a threshold caused by measurement scatter and a steep underlying population distribution."), ("Completeness", "The fraction of the target population retained by detection and analysis cuts."), ("Injection-recovery", "A calibration procedure that inserts controlled synthetic sources and measures their probability of recovery.")],
    11: [("Concordance", "Consistency of multiple probes within a shared model and correctly represented covariance."), ("Tension", "A quantified discrepancy between inferences that accounts for uncertainty, dependence, and parameterization."), ("Shared covariance", "Statistical dependence between probe estimates caused by common data, calibration, volume, or modeling."), ("Posterior predictive check", "A comparison between observed diagnostics and data replicated from the fitted model."), ("Look-elsewhere effect", "Inflation of apparent significance when many discrepancies or subsets are searched and only the largest is reported.")],
    12: [("Spatial curvature", "The constant-curvature contribution to FLRW spatial geometry, parameterized by Omega_k."), ("Equation-of-state parameter", "The pressure-to-density ratio w used to characterize a dark-energy component."), ("Evolving dark energy", "A model in which w changes with epoch rather than remaining constant."), ("Expansion history", "The redshift dependence of H(z) implied by the cosmic energy budget and gravity model."), ("Geometric degeneracy", "Different parameter combinations that preserve nearly the same distance or angular observable.")],
    13: [("Statistical uncertainty", "Variation expected from finite noisy data under the adopted sampling model."), ("Calibration uncertainty", "Error in the mapping from instrument response to a physical observable."), ("Model systematic", "Bias or uncertainty caused by an incomplete or misspecified physical or population model."), ("Error budget", "A structured accounting of uncertainty sources, correlations, and propagation to the final claim."), ("Blinding", "A procedure that hides or offsets sensitive results to reduce analyst-driven confirmation bias.")],
    14: [("Calibrated observable", "A measured quantity transformed from instrument output with documented response and corrections."), ("Likelihood data product", "The data vector, covariance, selection model, and nuisance prescription needed for inference."), ("Cross-probe analysis", "Joint or comparative inference using observables with complementary parameter sensitivities."), ("Robustness test", "A controlled change in data, model, calibration, or analysis that probes claim stability."), ("Claim boundary", "The explicit limit beyond which the available data and model do not justify interpretation.")],
}


def _terms(number: int) -> list[tuple[str, str]]:
    terms = TERM_SETS[number]
    if not 5 <= len(terms) <= 8:
        raise ValueError(f"Lecture {number:02d} requires 5-8 terms")
    return terms


def slide_section(number: int, title: str, question: str, equation: str, evidence: str, limitation: str) -> str:
    terms = _terms(number)
    buttons, panels = [], []
    for index, (name, definition) in enumerate(terms, 1):
        tab_id, panel_id = f"term-{number:02d}-{index}-tab", f"term-{number:02d}-{index}-panel"
        selected, hidden = ("true", "") if index == 1 else ("false", " hidden")
        neighbor = terms[index % len(terms)][0]
        buttons.append(f'<button class="term-button" id="{tab_id}" type="button" role="tab" aria-selected="{selected}" aria-controls="{panel_id}" data-term-target="{panel_id}">{html.escape(name)}</button>')
        panels.append(f'<article class="term-detail" id="{panel_id}" role="tabpanel" aria-labelledby="{tab_id}"{hidden}><h3>{html.escape(name)}</h3><p><strong>Definition:</strong> {html.escape(definition)}</p><p><strong>Why it matters here:</strong> It is required to answer {html.escape(question)} and to distinguish direct observation from cosmological inference.</p><p><strong>Relationships:</strong> Read it with <em>{html.escape(neighbor)}</em>, the model <span class="equation-inline">\\({html.escape(equation)}\\)</span>, and the evidence statement {html.escape(evidence)}</p><p><strong>Boundary or common confusion:</strong> {html.escape(limitation)}</p></article>')
    return f"<section class='slide glossary-slide' aria-labelledby='terms-{number:02d}-heading'><span class='slide-no'>Terms · 8 min</span><h2 id='terms-{number:02d}-heading'>Terms for This Lecture</h2><div class='term-explorer' data-term-explorer><div class='term-list' role='tablist' aria-label='Lecture terms'>{''.join(buttons)}</div><div class='term-details'>{''.join(panels)}</div></div></section>"


def notes_section(number: int, title: str, question: str, equation: str, evidence: str, limitation: str) -> str:
    terms = _terms(number)
    entries = []
    for index, (name, definition) in enumerate(terms):
        neighbor = terms[(index + 1) % len(terms)][0]
        entries.append(f'<dt><strong>{html.escape(name)}</strong></dt><dd><p>{html.escape(definition)} In this module it is used to answer <q>{html.escape(question)}</q></p><p><strong>Observable/model connection:</strong> The term links <q>{html.escape(evidence.rstrip(".!?"))}</q> to <em>{html.escape(neighbor)}</em> and the quantitative relation <span class="equation-inline">\\({html.escape(equation)}\\)</span>. State which part is measured, calibrated, derived, or model-dependent.</p><p><strong>Limit:</strong> {html.escape(limitation)} That boundary must remain attached when the term is used in a cosmological claim.</p></dd>')
    return f"<section><h2>Terms Developed in Context</h2><p>These terms organize the chain from recorded signal to calibrated observable, likelihood, and bounded cosmological claim.</p><dl>{''.join(entries)}</dl></section>"
