"""Lecture-specific terminology content for ASTR 101 slides and notes.

This module is the persistent source for the interactive term explorers added
to the second-pass lecture generator.  Each entry supplies concise slide text
and an additional notes-only development paragraph.
"""

TERM_DETAILS = {
    1: [
        {
            "term": "celestial sphere",
            "definition": "An imaginary sphere centered on the observer onto which directions to celestial objects are projected.",
            "matters": "It turns a three-dimensional universe with mostly unknown distances into a two-dimensional map of observable directions.",
            "relationships": "Altitude and azimuth locate points on the local celestial sphere; daily apparent rotation traces arcs on it as Earth rotates.",
            "limitation": "It is a geometric model, not a physical shell, and it does not by itself encode an object's distance.",
            "notes": "The model is especially useful when planning observations because a telescope is first pointed toward an angular direction. Two stars that appear adjacent on the sphere can be separated by hundreds of parsecs in space.",
        },
        {
            "term": "horizon",
            "definition": "The great circle separating the visible half of the sky from directions blocked by the ground for a particular observer.",
            "matters": "Rise, set, and target visibility are defined relative to this local boundary.",
            "relationships": "Altitude is measured upward from the horizon, while azimuth is measured around it; both depend on location and time.",
            "limitation": "A real skyline may sit above the ideal astronomical horizon because of terrain, buildings, trees, or atmospheric refraction.",
            "notes": "The ideal horizon is perpendicular to the local vertical. Observing plans therefore need both the geometric horizon and a site-specific horizon mask that records obstructions.",
        },
        {
            "term": "zenith",
            "definition": "The point on the celestial sphere directly above an observer.",
            "matters": "Objects near the zenith are viewed through less atmosphere than objects near the horizon.",
            "relationships": r"The zenith has altitude \(90^\circ\); its position among the stars changes continuously as Earth rotates.",
            "limitation": "Zenith is observer-specific: two separated observers generally have different zenith directions.",
            "notes": "The zenith defines the local vertical and anchors the altitude coordinate. Near-zenith observations usually reduce extinction and image distortion, although some telescope mounts have practical tracking limits there.",
            "equation": r"h_{\rm zenith}=90^\circ",
        },
        {
            "term": "meridian",
            "definition": "The great circle passing through north, the zenith, and south on an observer's sky.",
            "matters": "A target crossing the meridian is usually at its greatest altitude for that day and is often best placed for observation.",
            "relationships": "Meridian crossing connects local sky geometry to hour angle and local sidereal time.",
            "limitation": "Crossing the meridian does not guarantee visibility if the target culminates below the horizon or daylight is present.",
            "notes": "For a northern target, upper culmination normally provides the shortest atmospheric path. The concept becomes quantitative in Lecture 2, where hour angle zero identifies meridian transit.",
        },
        {
            "term": "altitude",
            "definition": "The angular height of an object above the local horizon.",
            "matters": "Altitude determines whether a target is visible and strongly affects atmospheric extinction and image quality.",
            "relationships": r"It ranges from \(0^\circ\) at the ideal horizon to \(90^\circ\) at the zenith and is paired with azimuth.",
            "limitation": "Altitude changes with time and observer location, so it is not a permanent coordinate of a star.",
            "notes": "Negative altitude places an object below the ideal horizon. Hand spans can estimate altitude, but a useful observing log should record the estimate's uncertainty and any skyline obstruction.",
        },
        {
            "term": "azimuth",
            "definition": "The compass direction of an object measured around the local horizon, conventionally from north through east.",
            "matters": "Together with altitude it gives an immediately usable pointing direction for naked-eye or telescope observations.",
            "relationships": "Azimuth is the horizontal coordinate in the altitude-azimuth system and changes as a celestial object follows its daily arc.",
            "limitation": "Conventions can differ in other fields, so the zero direction and direction of increase must be stated.",
            "notes": r"Astronomy normally uses \(0^\circ\) north, \(90^\circ\) east, \(180^\circ\) south, and \(270^\circ\) west. Reporting only azimuth is insufficient because many points share the same vertical circle.",
        },
        {
            "term": "angular size",
            "definition": "The angle an object spans at the observer, rather than its physical diameter.",
            "matters": "Astronomers can measure angular size directly even when physical size or distance is unknown.",
            "relationships": r"For small angles, physical size \(D\), distance \(d\), and angular size \(\theta\) satisfy \(D\approx d\theta\) when \(\theta\) is in radians.",
            "limitation": "Large angular size does not necessarily mean large physical size; a nearby small object can appear larger than a distant giant object.",
            "notes": "The Sun and Moon both span about half a degree despite radically different diameters because their distance-to-size ratios are similar. The small-angle relation fails if degrees are inserted without conversion to radians.",
            "equation": r"D \approx d\theta\quad(\theta\ {\rm in\ radians})",
        },
    ],
    2: [
        {
            "term": "right ascension",
            "definition": "A celestial longitude measured eastward along the celestial equator, usually in hours, minutes, and seconds.",
            "matters": "It gives a nearly location-independent way to identify where an object lies east or west on the sky map.",
            "relationships": "Right ascension combines with declination to locate a source and with local sidereal time to determine hour angle.",
            "limitation": "Coordinates slowly change because of precession and proper motion, so catalogs specify an epoch.",
            "notes": r"Twenty-four hours of right ascension correspond to \(360^\circ\), so one hour of RA equals \(15^\circ\). RA is a coordinate, not the clock time at which an object must be observed.",
            "equation": r"24^{\rm h}=360^\circ",
        },
        {
            "term": "declination",
            "definition": "Angular position north or south of the celestial equator.",
            "matters": "Declination helps determine whether a target ever rises and how high it can culminate from a given latitude.",
            "relationships": "It is the celestial analogue of latitude and pairs with right ascension in the equatorial coordinate system.",
            "limitation": "Declination alone does not specify when a target is above the horizon.",
            "notes": r"Declination ranges from \(+90^\circ\) at the north celestial pole to \(-90^\circ\) at the south celestial pole. At meridian transit, target altitude can be estimated from observer latitude and declination.",
        },
        {
            "term": "ecliptic",
            "definition": "The Sun's apparent annual path on the celestial sphere, corresponding to the plane of Earth's orbit.",
            "matters": "The Moon and planets remain near the ecliptic because the solar system formed from a flattened disk.",
            "relationships": "Its tilt relative to the celestial equator is Earth's obliquity, the geometric cause of seasonal changes in solar altitude and day length.",
            "limitation": "Planetary orbits are not exactly coplanar, so planets and the Moon can lie several degrees away from it.",
            "notes": "The ecliptic is a projected path, not a material track. Its intersections with the celestial equator define the equinox directions.",
        },
        {
            "term": "local sidereal time",
            "definition": "A clock based on Earth's rotation relative to the stars; numerically it equals the right ascension currently crossing the local meridian.",
            "matters": "It converts catalog coordinates into an immediate statement about where a target is in its daily path.",
            "relationships": "Hour angle equals local sidereal time minus right ascension; hour angle zero means meridian transit.",
            "limitation": "It is not civil solar time and advances about four minutes earlier each solar day.",
            "notes": "Sidereal time separates the geometry of the star field from time zones and daylight-saving rules. It is the natural clock for scheduling equatorial-coordinate observations.",
            "equation": r"H={\rm LST}-\alpha",
        },
        {
            "term": "phase",
            "definition": "The fraction and orientation of a body's illuminated hemisphere visible to the observer.",
            "matters": "Lunar phase predicts brightness, rise and set timing, and observing conditions.",
            "relationships": "Phase follows Sun-object-observer geometry; new and full Moon are alignments, while quarter phases are roughly right-angle configurations.",
            "limitation": "Ordinary lunar phases are not caused by Earth's shadow.",
            "notes": "Half of the Moon is illuminated at nearly all times; the changing phase is the changing visible fraction of that half. The phase cycle is synodic and therefore differs from the Moon's orbital period relative to the stars.",
        },
        {
            "term": "node",
            "definition": "One of the two points where an inclined orbit crosses a chosen reference plane.",
            "matters": "Lunar nodes explain why most new and full moons do not produce eclipses.",
            "relationships": "An eclipse requires the Moon to be near a node while also near new or full phase.",
            "limitation": "Nodes are geometric crossing directions, not physical objects, and their positions precess.",
            "notes": "The ascending node crosses from south to north of the reference plane; the descending node crosses the opposite way. Node precession changes the calendar dates of eclipse seasons.",
        },
        {
            "term": "eclipse season",
            "definition": "A several-week interval when the Sun lies close enough to a lunar node for eclipses to be geometrically possible.",
            "matters": "It explains the clustering of solar and lunar eclipses rather than an eclipse at every new and full Moon.",
            "relationships": "It combines the concepts of phase, orbital inclination, and node alignment.",
            "limitation": "An eclipse season permits eclipses but does not guarantee that every eclipse is visible from a particular location.",
            "notes": "Because the node line precesses, eclipse seasons recur in less than half a year. Solar-eclipse visibility is especially local because the Moon's umbral shadow covers only a narrow path on Earth.",
        },
    ],
    3: [
        {
            "term": "astronomical unit",
            "definition": "A distance unit defined as exactly 149,597,870,700 metres, close to Earth's average distance from the Sun.",
            "matters": "It puts solar-system distances on a manageable numerical scale.",
            "relationships": "The AU supplies the baseline for annual stellar parallax and links planetary distances to Kepler's laws.",
            "limitation": "It is a unit, not Earth's instantaneous Sun distance, which varies along Earth's orbit.",
            "notes": "Expressing planetary distances in AU reveals orbital scale ratios directly. The modern AU is fixed by definition rather than continually remeasured from Earth's changing orbit.",
        },
        {
            "term": "light-year",
            "definition": "The distance light travels in vacuum during one Julian year.",
            "matters": "It connects cosmic distance to light-travel time and therefore to how far into the past we observe.",
            "relationships": "One parsec is about 3.26 light-years; both are distance units used beyond the solar system.",
            "limitation": "Despite the word year, it measures distance, not duration.",
            "notes": "A star 10 light-years away is seen through light that has traveled for about 10 years. This does not mean the star itself is 10 years old.",
        },
        {
            "term": "parsec",
            "definition": "The distance at which one astronomical unit subtends a parallax angle of one arcsecond.",
            "matters": "It ties a widely used stellar distance unit directly to a measurable geometric angle.",
            "relationships": "Distance in parsecs is the reciprocal of annual parallax in arcseconds for the standard small-angle geometry.",
            "limitation": "The reciprocal formula becomes statistically delicate when parallax uncertainty is comparable to the measured parallax.",
            "notes": r"A parsec is about \(3.086\times10^{16}\) m or 3.26 ly. Catalog inference at low signal-to-noise often uses probability models rather than simply inverting a noisy parallax.",
            "equation": r"d({\rm pc})=\frac{1}{p({\rm arcsec})}",
        },
        {
            "term": "parallax",
            "definition": "An apparent shift in an object's direction caused by observing it from separated positions.",
            "matters": "Annual stellar parallax provides a direct geometric rung of the cosmic distance ladder.",
            "relationships": "A larger baseline increases the shift, while a larger distance decreases it.",
            "limitation": "Parallax is an angular effect and must be separated from proper motion and measurement systematics.",
            "notes": "Earth's orbit provides observations six months apart with a two-AU separation, while the conventional parallax angle uses a one-AU radius. Nearby stars show larger parallaxes than distant stars.",
        },
        {
            "term": "baseline",
            "definition": "The known separation between observing positions used in triangulation.",
            "matters": "A longer baseline produces a larger parallax angle for the same target and improves geometric leverage.",
            "relationships": "Baseline, angular shift, and distance form the parallax triangle.",
            "limitation": "Increasing baseline does not remove errors in pointing, reference-star calibration, or source motion.",
            "notes": "Classroom parallax may use the distance between two eye positions; stellar parallax uses Earth's orbit. The baseline must be stated consistently with whether the measured angle is a half-shift or full shift.",
        },
        {
            "term": "standard candle",
            "definition": "An object or relation whose intrinsic luminosity can be estimated, allowing distance to be inferred from observed flux.",
            "matters": "It extends distance measurement far beyond the direct reach of trigonometric parallax.",
            "relationships": "It uses the inverse-square law and must be calibrated by nearer distance indicators.",
            "limitation": "Standard candles are not perfectly identical; extinction, metallicity, and calibration scatter can bias the inferred distance.",
            "notes": "Cepheid variables and Type Ia supernovae are standardizable rather than literally identical candles. Their reliability depends on overlapping distance-ladder rungs.",
            "equation": r"F=\frac{L}{4\pi d^2}",
        },
        {
            "term": "order of magnitude",
            "definition": "A scale expressed by the nearest power of ten.",
            "matters": "It allows rapid comparisons and exposes results that are physically implausible before detailed calculation.",
            "relationships": "Logarithmic scales, scientific notation, and ratio reasoning all use orders of magnitude.",
            "limitation": "It deliberately suppresses factors of a few and should not replace precision when precision matters.",
            "notes": r"Earth-Sun distance is about \(10^{11}\) m, while the nearest-star distance is about \(10^{16}\) m, a five-order-of-magnitude gap. The method is a reasonableness check, not a claim of exact equality.",
        },
    ],
    4: [
        {
            "term": "ellipse",
            "definition": "A closed curve for which the sum of distances to two fixed foci is constant.",
            "matters": "Bound two-body orbits are ellipses in the Newtonian approximation.",
            "relationships": "The central mass lies at one focus; semi-major axis sets orbital scale and eccentricity sets shape.",
            "limitation": "Real multi-body orbits are perturbed and need not remain perfect fixed ellipses.",
            "notes": "A circle is the special case with coincident foci and zero eccentricity. The geometric center of an ellipse is not generally the location of the attracting body.",
        },
        {
            "term": "semi-major axis",
            "definition": "Half the longest diameter of an ellipse.",
            "matters": "For a bound orbit it is the characteristic size that enters Kepler's third law and the orbital energy.",
            "relationships": r"Orbital period grows as \(a^{3/2}\) for bodies orbiting the same dominant mass.",
            "limitation": "It is not the instantaneous distance from the orbiting body to the focus except for a circular orbit.",
            "notes": r"Periapsis and apoapsis distances are \(a(1-e)\) and \(a(1+e)\). Thus the same semi-major axis can accompany different distance variations when eccentricity differs.",
            "equation": r"P^2\propto a^3",
        },
        {
            "term": "period",
            "definition": "The time required for a repeating motion to complete one cycle.",
            "matters": "Orbital period is directly observable and constrains system mass when paired with orbital size.",
            "relationships": "Kepler's third law connects period to semi-major axis and total gravitating mass.",
            "limitation": "Different periods can be defined relative to the stars, the Sun, or repeating alignments.",
            "notes": "For planetary dynamics the sidereal orbital period is usually intended. A synodic period measures recurrence as seen from another moving body and can differ substantially.",
        },
        {
            "term": "eccentricity",
            "definition": "A dimensionless measure of how much an orbit departs from a circle.",
            "matters": "It controls the contrast between nearest and farthest orbital distances and the associated speed changes.",
            "relationships": r"Bound ellipses have \(0\le e<1\); \(e=0\) is circular.",
            "limitation": "A diagram can exaggerate eccentricity, and Earth's orbit is much closer to circular than many textbook sketches suggest.",
            "notes": "Eccentricity describes shape but not size or orientation. Seasons on Earth are dominated by axial tilt, not Earth's small orbital eccentricity.",
        },
        {
            "term": "center of mass",
            "definition": "The mass-weighted average position of all matter in a system.",
            "matters": "Two gravitating bodies both orbit their common center of mass rather than one remaining perfectly fixed.",
            "relationships": r"Its location obeys \(m_1r_1=m_2r_2\) for two bodies along their separation line.",
            "limitation": "It can lie inside one body, between bodies, or even outside both; it is not necessarily a material point.",
            "notes": "The Sun's reflex motion around the solar-system barycenter underlies radial-velocity planet detection. Center-of-mass reasoning also prevents treating the smaller body's effect as exactly zero.",
            "equation": r"m_1r_1=m_2r_2",
        },
        {
            "term": "escape velocity",
            "definition": "The minimum launch speed needed to reach arbitrarily large distance with zero speed remaining, neglecting later propulsion and drag.",
            "matters": "It connects a body's mass and radius to atmospheric retention and spacecraft energetics.",
            "relationships": r"For a spherical body, \(v_{\rm esc}=\sqrt{2GM/R}\).",
            "limitation": "It is not the speed needed to remain in orbit, and real launches face atmosphere, rotation, and powered trajectories.",
            "notes": "Escape speed depends on gravitational potential, not projectile mass. A body can escape with lower instantaneous speed if engines add energy throughout the trajectory.",
            "equation": r"v_{\rm esc}=\sqrt{\frac{2GM}{R}}",
        },
        {
            "term": "tide",
            "definition": "A differential gravitational effect caused by variation in gravitational acceleration across an extended body.",
            "matters": "Tides deform oceans and solid bodies, exchange angular momentum, heat moons, and can disrupt objects.",
            "relationships": r"Tidal strength rises strongly at small separation, approximately as \(M/r^3\) for a distant perturber.",
            "limitation": "A tide is not simply the total gravitational pull; uniform acceleration of the whole body does not create stretching.",
            "notes": "The near and far sides of Earth both experience ocean bulges in the idealized model because acceleration relative to Earth's center differs on both sides. Local coastlines and ocean dynamics then shape observed tidal heights.",
            "equation": r"a_{\rm tidal}\propto \frac{M}{r^3}",
        },
    ],
    5: [
        {
            "term": "wavelength",
            "definition": "The spatial distance over which a wave's pattern repeats.",
            "matters": "Astronomical wavelength selects which physical processes, temperatures, and materials a detector can reveal.",
            "relationships": r"In vacuum, wavelength and frequency satisfy \(c=\lambda\nu\); photon energy is inversely proportional to wavelength.",
            "limitation": "Color names cover broad bands, and measured wavelength can be shifted by source motion or cosmic expansion.",
            "notes": "Shorter-wavelength photons carry more energy. Earth's atmosphere transmits some bands and blocks others, which is why observatory location depends on wavelength.",
            "equation": r"c=\lambda\nu",
        },
        {
            "term": "frequency",
            "definition": "The number of wave cycles passing a point per unit time.",
            "matters": "Frequency is directly linked to photon energy and provides an alternative coordinate for spectra.",
            "relationships": r"It increases as wavelength decreases in vacuum, and \(E=h\nu\).",
            "limitation": "Wavelength and frequency axes run in opposite directions, so spectral trends must be read carefully.",
            "notes": "Frequency remains constant when light crosses a stationary boundary while speed and wavelength may change. Astronomers commonly switch between frequency, wavelength, and energy units depending on the band.",
            "equation": r"E=h\nu",
        },
        {
            "term": "photon",
            "definition": "A quantum of electromagnetic radiation carrying energy and momentum.",
            "matters": "Detectors ultimately count or convert photons, so astronomical evidence is limited by photon statistics.",
            "relationships": r"Photon energy is \(E=h\nu=hc/\lambda\), linking quantum detections to spectral wavelength.",
            "limitation": "A photon is not a tiny colored pellet following a classical trajectory; quantum behavior depends on the measurement.",
            "notes": "A bright source delivers more photons per unit area and time, while a hotter spectrum shifts the energy distribution. Shot noise scales roughly as the square root of detected photon number.",
            "equation": r"E=h\nu=\frac{hc}{\lambda}",
        },
        {
            "term": "blackbody",
            "definition": "An ideal absorber and emitter whose thermal spectrum depends only on temperature.",
            "matters": "It provides the baseline model for interpreting stellar continua and planetary thermal emission.",
            "relationships": r"Wien's law links peak wavelength to temperature, while Stefan-Boltzmann links emitted flux to \(T^4\).",
            "limitation": "Real spectra contain absorption, emission, opacity effects, and geometric complications.",
            "notes": "Stars approximate blackbodies in their continua but their spectral lines carry composition and atmospheric-structure information. A fitted color temperature can differ from a physical temperature if the source is not thermal.",
            "equation": r"\lambda_{\max}T=b",
        },
        {
            "term": "emission line",
            "definition": "A narrow spectral feature where intensity exceeds the surrounding continuum because atoms, ions, or molecules emit at particular transitions.",
            "matters": "Emission lines identify material and diagnose temperature, density, ionization, and motion.",
            "relationships": "The line wavelength reflects an energy-level difference; Doppler shifts move the observed wavelength.",
            "limitation": "A line's strength is not a simple abundance meter because excitation, opacity, and geometry also matter.",
            "notes": "Hot low-density gas viewed against a darker background often produces an emission spectrum. Line ratios can be more informative than a single line because they constrain physical conditions.",
        },
        {
            "term": "absorption line",
            "definition": "A narrow reduction in intensity where intervening material removes photons at specific transition wavelengths.",
            "matters": "Stellar absorption lines reveal atmospheric composition, temperature class, pressure, and radial motion.",
            "relationships": "They occur when cooler gas lies in front of a brighter continuous source and share transition wavelengths with corresponding emission lines.",
            "limitation": "A missing or weak line does not prove an element is absent; the atoms may be in the wrong excitation or ionization state.",
            "notes": "The pattern of many absorption lines, not one feature in isolation, supports classification. Instrument response and Earth's atmosphere must be calibrated before interpreting line depth.",
        },
        {
            "term": "Doppler shift",
            "definition": "A change in observed wavelength or frequency caused by relative line-of-sight motion between source and observer.",
            "matters": "It measures radial velocity in stars, gas clouds, galaxies, and exoplanet-host systems.",
            "relationships": r"At speeds much less than light, \(\Delta\lambda/\lambda_0\approx v_r/c\).",
            "limitation": "It measures only the line-of-sight component, and cosmological redshift requires a broader expansion model at large distances.",
            "notes": "A redshift corresponds to recession and a blueshift to approach under the usual convention. Calibration requires comparing observed line centers with laboratory rest wavelengths.",
            "equation": r"\frac{\Delta\lambda}{\lambda_0}\approx\frac{v_r}{c}",
        },
    ],
    6: [
        {
            "term": "aperture",
            "definition": "The effective diameter of a telescope's primary light-collecting opening.",
            "matters": "Aperture sets both photon-collecting power and the best possible diffraction-limited angular resolution.",
            "relationships": r"Collecting area grows as \(D^2\), while diffraction angle shrinks approximately as \(\lambda/D\).",
            "limitation": "A larger aperture cannot by itself remove atmospheric seeing, tracking errors, or detector noise.",
            "notes": "Doubling diameter gives four times the collecting area. For ground-based optical telescopes, adaptive optics or interferometry may be needed to approach the diffraction limit.",
        },
        {
            "term": "collecting area",
            "definition": "The effective surface area that intercepts incoming radiation.",
            "matters": "It controls the photon rate and therefore how faint a source can be measured in a given exposure.",
            "relationships": r"For an unobscured circular aperture, \(A=\pi D^2/4\); signal-to-noise then also depends on background and detector properties.",
            "limitation": "Central obstructions, reflectivity losses, and instrument throughput reduce effective area below geometric area.",
            "notes": "Collecting area improves sensitivity, not magnification by itself. Comparing telescopes requires effective throughput across the wavelength band, not diameter alone.",
            "equation": r"A=\frac{\pi D^2}{4}",
        },
        {
            "term": "resolution",
            "definition": "The ability of an observing system to distinguish nearby details or sources as separate.",
            "matters": "Resolution determines whether structure is measured or blurred together.",
            "relationships": r"The diffraction scale for a circular aperture is approximately \(\theta=1.22\lambda/D\), but seeing and detector sampling can dominate.",
            "limitation": "Resolution is not the same as magnification; enlarging a blurred image does not recover missing detail.",
            "notes": "Angular resolution must be compared with pixel scale and source separation. Spectral and temporal resolution are analogous ideas in wavelength and time rather than angle.",
            "equation": r"\theta_{\rm diff}\approx1.22\frac{\lambda}{D}",
        },
        {
            "term": "seeing",
            "definition": "Atmospheric blurring and image motion caused mainly by turbulent variations in refractive index.",
            "matters": "It often sets the practical resolution of ground-based optical images.",
            "relationships": "Seeing is measured as an angular width of stellar images and can be improved with site selection, short exposures, or adaptive optics.",
            "limitation": "Seeing is distinct from cloud cover, transparency, and diffraction, though all affect observing quality.",
            "notes": "A night can be transparent but have poor seeing, or clear stellar images can occur through a somewhat less transparent atmosphere. Space telescopes avoid atmospheric seeing but retain diffraction and engineering limits.",
        },
        {
            "term": "field of view",
            "definition": "The angular region of sky recorded or visible in one observation.",
            "matters": "It controls target framing, survey speed, and whether comparison stars or extended structures fit in the image.",
            "relationships": "Field of view depends on focal length and detector dimensions; pixel scale partitions it into samples.",
            "limitation": "A wide field does not guarantee high resolution or sensitivity.",
            "notes": "Instrument design trades field size against sampling, aberration control, and data volume. Observers should distinguish a single detector's field from a survey's total sky coverage.",
        },
        {
            "term": "detector",
            "definition": "A device that converts incident radiation into measurable electrical or digital signals.",
            "matters": "Detector response determines wavelength sensitivity, noise, dynamic range, and calibration strategy.",
            "relationships": "A telescope forms or directs the signal; the detector samples it into counts that must be corrected for bias, dark current, and sensitivity variations.",
            "limitation": "Recorded counts are not automatically calibrated physical fluxes.",
            "notes": "CCDs, infrared arrays, radio receivers, and particle detectors use different conversion processes. Quantum efficiency gives the fraction of incident photons that contribute detected signal.",
        },
        {
            "term": "signal-to-noise",
            "definition": "The ratio of the measured source signal to the uncertainty in that measurement.",
            "matters": "It quantifies whether a detection or feature is statistically useful rather than merely visible.",
            "relationships": r"In a source-dominated photon-counting limit, \({\rm S/N}\approx\sqrt{N}\), so quadrupling photons roughly doubles S/N.",
            "limitation": "Longer exposure cannot average away all systematic errors, saturation, confusion, or calibration bias.",
            "notes": "Background sky, read noise, dark current, and source counts all enter a realistic noise budget. Reporting S/N without defining the aperture, wavelength bin, or measurement is incomplete.",
            "equation": r"{\rm S/N}\approx\sqrt{N}\quad{\rm (photon\ limited)}",
        },
    ],
    7: [
        {
            "term": "protoplanetary disk",
            "definition": "A rotating disk of gas and dust surrounding a young star from which planets and smaller bodies can form.",
            "matters": "Its flattened structure explains the broadly coplanar, same-direction architecture of many planetary systems.",
            "relationships": "Temperature gradients across the disk influence condensation, the ice line, and the materials available for accretion.",
            "limitation": "Disk evolution is dynamic and diverse; the solar nebula is reconstructed from incomplete evidence rather than observed directly.",
            "notes": "Angular-momentum conservation helps a collapsing cloud flatten into a disk. Observed disks around young stars show rings and gaps, but those structures do not always prove a planet is present.",
        },
        {
            "term": "accretion",
            "definition": "Growth by gravitationally or collisionally gathering smaller particles and bodies.",
            "matters": "It links microscopic dust grains to planetesimals, embryos, planets, and continuing impact histories.",
            "relationships": "Collision speed, sticking efficiency, gravity, and gas drag determine whether encounters build or erode bodies.",
            "limitation": "Accretion is not automatically smooth; fragmentation, migration, and giant impacts can interrupt or reverse growth.",
            "notes": "Once bodies become massive enough, gravitational focusing increases their collision cross section. The transition from dust to kilometre-scale planetesimals remains an active modeling challenge.",
        },
        {
            "term": "differentiation",
            "definition": "Separation of a planetary body into layers of different composition or density, commonly during heating and melting.",
            "matters": "It explains cores, mantles, crusts, magnetic-field potential, and volcanic chemistry.",
            "relationships": "Dense materials sink while buoyant materials rise when the interior can flow; heat comes from accretion, radioactivity, and impacts.",
            "limitation": "Small or cold bodies may remain only partly differentiated, and later mixing can obscure the original layering.",
            "notes": "Differentiation is inferred from density, moment of inertia, seismic data, magnetic fields, and meteorite chemistry. Layering records thermal history as well as composition.",
        },
        {
            "term": "cratering",
            "definition": "The excavation and deformation of a surface by high-speed impacts.",
            "matters": "Crater abundance and preservation provide a relative record of surface age and resurfacing.",
            "relationships": "Impact rate, projectile properties, gravity, atmosphere, erosion, and volcanism all shape the observed crater population.",
            "limitation": "Crater counts require calibration and assumptions; a crater-poor surface may be young or actively resurfaced.",
            "notes": "Large craters are rarer than small ones, and overlapping or eroded craters complicate counting. Absolute ages rely on samples or dynamical models, not image counts alone.",
        },
        {
            "term": "volcanism",
            "definition": "Transport of molten or volatile-rich material from a body's interior to its surface.",
            "matters": "It reshapes terrain, releases atmospheric gases, and reveals internal heat.",
            "relationships": "Volcanism competes with cratering and erosion in setting surface age; tidal heating can sustain it on some moons.",
            "limitation": "Volcanic-looking landforms require geological context because impacts or tectonics can make similar shapes.",
            "notes": "Earth, Venus, Mars, the Moon, and Io show different volcanic styles because composition, gravity, atmosphere, and heat supply differ. Detecting present activity requires temporal or thermal evidence.",
        },
        {
            "term": "greenhouse effect",
            "definition": "Surface warming produced when an atmosphere absorbs and re-emits outgoing infrared radiation while remaining comparatively transparent to incoming stellar energy.",
            "matters": "It is central to explaining the divergent climates of Venus, Earth, and Mars.",
            "relationships": "Atmospheric composition, pressure, clouds, albedo, and energy balance determine its magnitude.",
            "limitation": "It is not caused by a glass-like lid or by ozone, and the existence of a natural greenhouse effect does not specify its strength.",
            "notes": "A planet's equilibrium temperature omits atmospheric back-radiation. Positive feedbacks can amplify warming, but clouds and circulation make full climate response more complex than a one-layer model.",
        },
        {
            "term": "comparative planetology",
            "definition": "The study of planets and moons by comparing their properties, histories, and physical processes.",
            "matters": "Controlled comparisons reveal why similar starting conditions can lead to different outcomes.",
            "relationships": "It integrates accretion, differentiation, cratering, volcanism, atmospheres, and orbital environment.",
            "limitation": "Planets are not controlled laboratory duplicates; many variables change together, so causal claims require care.",
            "notes": "Earth and Venus isolate some contrasts in atmosphere and climate while sharing approximate size. Mars and the Moon help test how size and internal heat affect geological longevity.",
        },
    ],
    8: [
        {
            "term": "ice line",
            "definition": "The disk distance beyond which temperatures were low enough for abundant volatile compounds such as water to condense as solids.",
            "matters": "Extra solid material beyond this line helped planetary cores grow rapidly enough to capture massive gas envelopes.",
            "relationships": "It links the protoplanetary disk's temperature gradient to the compositional contrast between terrestrial and giant-planet regions.",
            "limitation": "The line moved as the disk evolved and differs by volatile species; it was not a fixed sharp wall.",
            "notes": "Water ice is usually the reference in introductory solar-system models. Disk heating, opacity, and stellar luminosity shift the condensation boundary over time.",
        },
        {
            "term": "Jovian planet",
            "definition": "A giant planet dominated in bulk by hydrogen, helium, and/or volatile-rich material rather than a solid rocky surface.",
            "matters": "Jovian planets show how rapid core growth and gas capture produce worlds unlike terrestrial planets.",
            "relationships": "Their large masses, low mean densities, ring systems, and extensive moon systems connect to formation beyond the ice line.",
            "limitation": "Gas giant and ice giant are useful subcategories; not all Jovian planets have the same composition or interior.",
            "notes": "Jupiter and Saturn are hydrogen-helium gas giants, while Uranus and Neptune contain larger fractions of heavier volatile-rich material. None has a solid surface where atmospheric pressure simply stops.",
        },
        {
            "term": "ring system",
            "definition": "A disk of many independently orbiting particles around a planet or other body.",
            "matters": "Rings reveal orbital dynamics, collisions, resonances, and the balance between aggregation and tidal disruption.",
            "relationships": "Ring gaps and edges can be shaped by shepherd moons and orbital resonances; particles follow Keplerian orbits.",
            "limitation": "A ring is not a rigid solid sheet, even when it looks continuous from far away.",
            "notes": "Inner ring particles orbit faster than outer particles. Frequent collisions keep rings thin and nearly circular while continually modifying particle sizes.",
        },
        {
            "term": "small body",
            "definition": "A solar-system object smaller than a planet or recognized dwarf planet, including most asteroids, comets, and trans-Neptunian objects.",
            "matters": "Small bodies preserve information about early solar-system materials and deliver records of collisions and migration.",
            "relationships": "Their orbit, composition, and activity connect them to formation zones, resonances, impacts, and cometary behavior.",
            "limitation": "Classification boundaries are partly conventional and do not imply that all members share one origin.",
            "notes": "Some small bodies are rubble piles, some are differentiated fragments, and some retain volatile ices. Population statistics often reveal more than one object's appearance.",
        },
        {
            "term": "comet",
            "definition": "A volatile-rich small body that can develop a gas-and-dust coma and tails when heated near the Sun.",
            "matters": "Comets sample cold formation environments and show how solar heating releases primitive material.",
            "relationships": "Sublimation drives activity; dust and ion tails respond differently to sunlight and the solar wind.",
            "limitation": "A tail does not trail directly behind the comet's motion; it points broadly away from the Sun.",
            "notes": "A comet nucleus is much smaller than its visible coma. Repeated passages can exhaust surface volatiles, fragment the nucleus, or leave an inactive object.",
        },
        {
            "term": "impact",
            "definition": "A high-speed collision in which kinetic energy excavates, heats, deforms, or disrupts planetary material.",
            "matters": "Impacts build planets, alter atmospheres, create craters, and occasionally cause global biological or climatic consequences.",
            "relationships": r"Impact energy scales as \(mv^2/2\), while outcome also depends on angle, composition, gravity, and atmosphere.",
            "limitation": "Crater diameter is not equal to projectile diameter, and dramatic consequences cannot be inferred from size alone.",
            "notes": "Typical solar-system encounter speeds make even modest bodies energetically important. Frequency falls strongly with impactor size, so risk combines low probability with potentially high consequence.",
            "equation": r"K=\frac{1}{2}mv^2",
        },
        {
            "term": "habitable environment",
            "definition": "An environment with physical and chemical conditions that could support a specified form of life for some interval.",
            "matters": "It shifts habitability from a simple distance criterion to a testable set of energy, solvent, chemistry, and stability requirements.",
            "relationships": "Stellar flux, atmosphere, internal heating, liquid reservoirs, and nutrient cycling can all contribute.",
            "limitation": "Habitable does not mean inhabited, and Earth-like surface liquid water is not the only conceivable habitat.",
            "notes": "Subsurface oceans can be maintained by tidal or radiogenic heat outside the classical circumstellar habitable zone. Any claim must state the assumed biology and timescale.",
        },
    ],
    9: [
        {
            "term": "luminosity",
            "definition": "The total radiant energy a source emits per unit time.",
            "matters": "Luminosity is an intrinsic stellar property used to compare energy output independent of distance.",
            "relationships": r"Observed flux follows \(F=L/(4\pi d^2)\); for a thermal star, \(L=4\pi R^2\sigma T^4\).",
            "limitation": "Luminosity can refer to all wavelengths or a specified band, and anisotropic sources complicate the simple interpretation.",
            "notes": "A star can appear faint because it is intrinsically dim or far away. Distance is therefore required to turn flux into luminosity.",
            "equation": r"L=4\pi R^2\sigma T^4",
        },
        {
            "term": "flux",
            "definition": "Radiant power received per unit area at the observer or detector.",
            "matters": "Flux is the directly measured brightness quantity from which luminosity is inferred.",
            "relationships": "It decreases with inverse square of distance for isotropic emission and is integrated over a stated wavelength band.",
            "limitation": "Flux is affected by distance, extinction, filter response, and calibration; it is not intrinsic luminosity.",
            "notes": "Two equally luminous stars at different distances have different fluxes. A complete flux measurement states units, bandpass, aperture, and whether extinction has been corrected.",
            "equation": r"F=\frac{L}{4\pi d^2}",
        },
        {
            "term": "apparent magnitude",
            "definition": "A logarithmic measure of how bright a source appears from Earth in a specified band.",
            "matters": "It compresses enormous brightness ranges into the historical scale used in observing and catalogs.",
            "relationships": "A five-magnitude difference corresponds to a flux ratio of 100; smaller magnitudes are brighter.",
            "limitation": "Apparent magnitude mixes luminosity, distance, extinction, and bandpass.",
            "notes": "A one-magnitude step is a flux factor of about 2.512. Negative magnitudes are valid and simply indicate sources brighter than the conventional zero point.",
            "equation": r"m_2-m_1=-2.5\log_{10}\!\left(\frac{F_2}{F_1}\right)",
        },
        {
            "term": "absolute magnitude",
            "definition": "The apparent magnitude an object would have at a standard distance of 10 parsecs, with the relevant convention stated.",
            "matters": "It provides a distance-normalized comparison of intrinsic brightness.",
            "relationships": "Apparent and absolute magnitude are linked by the distance modulus, with extinction added when relevant.",
            "limitation": "It remains band-dependent and is not identical to bolometric luminosity.",
            "notes": r"The distance modulus \(m-M=5\log_{10}(d/10\,{\rm pc})\) assumes distance in parsecs and no extinction. A star with \(m=M\) is at 10 pc.",
            "equation": r"m-M=5\log_{10}\!\left(\frac{d}{10\,{\rm pc}}\right)",
        },
        {
            "term": "spectral type",
            "definition": "A classification based primarily on the pattern and strength of stellar absorption lines, strongly ordered by surface temperature.",
            "matters": "It connects an observed spectrum to temperature, ionization state, and stellar population.",
            "relationships": "The O-B-A-F-G-K-M sequence runs from hot to cool and helps set horizontal position on an H-R diagram.",
            "limitation": "Line strength reflects excitation and ionization, not simply elemental abundance.",
            "notes": "Hydrogen Balmer lines peak near A-type temperatures rather than in the hottest stars. Luminosity class adds information about surface gravity and evolutionary state.",
        },
        {
            "term": "main sequence",
            "definition": "The diagonal band on an H-R diagram occupied by stars stably fusing hydrogen in their cores.",
            "matters": "It represents the longest-lived stage of most stars and links mass to luminosity, temperature, radius, and lifetime.",
            "relationships": "Higher-mass main-sequence stars are generally hotter, more luminous, and shorter-lived.",
            "limitation": "It is not an evolutionary track that each star slides down from hot to cool.",
            "notes": "A star's location along the main sequence is primarily set by mass and composition. Leaving the band signals a structural change after core hydrogen depletion.",
        },
        {
            "term": "H-R diagram",
            "definition": "A plot of stellar luminosity or absolute magnitude against surface temperature, color, or spectral type.",
            "matters": "It organizes stellar properties and reveals main-sequence stars, giants, supergiants, and white dwarfs.",
            "relationships": "Position combines luminosity and temperature; the Stefan-Boltzmann law then constrains radius.",
            "limitation": "Axis directions and observables vary, and a diagram is a population snapshot rather than one star's path through time.",
            "notes": "Temperature usually decreases to the right, unlike many familiar graphs. Cluster H-R diagrams are especially powerful because their stars have similar distance and age.",
        },
    ],
    10: [
        {
            "term": "hydrostatic equilibrium",
            "definition": "A state in which inward gravity is balanced at each layer by an outward pressure gradient.",
            "matters": "It explains why a star can remain stable over long periods rather than rapidly collapse or expand.",
            "relationships": "Energy generation and transport maintain the temperature and pressure needed for the balance.",
            "limitation": "It is a quasi-static approximation and can fail during pulsations, explosions, or rapid collapse.",
            "notes": "The balance is local, not merely a cancellation of two forces at the surface. When core fuel changes, the star readjusts its pressure, density, and radius to seek a new equilibrium.",
        },
        {
            "term": "nuclear fusion",
            "definition": "Reactions that combine lighter nuclei into heavier nuclei while converting a small amount of mass into energy.",
            "matters": "Fusion powers stars and produces many chemical elements.",
            "relationships": "Core temperature and density set reaction rates; released energy supports hydrostatic equilibrium.",
            "limitation": "Fusion is not ordinary burning and does not proceed equally for all nuclei or stellar masses.",
            "notes": "Hydrogen fusion begins through different reaction chains depending on core conditions. Fusion beyond iron does not release energy, helping set the stage for massive-star collapse.",
            "equation": r"E=\Delta mc^2",
        },
        {
            "term": "main-sequence lifetime",
            "definition": "The duration for which a star sustains core hydrogen fusion.",
            "matters": "It sets the dominant timescale of stellar evolution and lets cluster turnoffs indicate age.",
            "relationships": "A rough scaling is available fuel divided by luminosity; massive stars have more fuel but consume it much faster.",
            "limitation": "The simple mass-to-luminosity estimate suppresses composition, mixing, and detailed stellar structure.",
            "notes": "Because luminosity rises steeply with mass, high-mass stars have much shorter lifetimes. A low-mass star can remain on the main sequence longer than the current age of the universe.",
            "equation": r"t_{\rm MS}\sim\frac{M}{L}",
        },
        {
            "term": "red giant",
            "definition": "An evolved star with a greatly expanded, cool surface and high luminosity after core hydrogen depletion.",
            "matters": "It demonstrates how internal fuel changes reorganize a star's radius, temperature, and energy transport.",
            "relationships": "Hydrogen shell burning and later helium fusion connect the red-giant phase to white-dwarf formation for Sun-like stars.",
            "limitation": "Red color does not imply low total power; the large surface area can make a cool star highly luminous.",
            "notes": "The core contracts while outer layers expand, so different regions respond oppositely. Exact giant-branch evolution depends strongly on mass and composition.",
        },
        {
            "term": "white dwarf",
            "definition": "A compact stellar remnant supported mainly by electron degeneracy pressure, with no sustained core fusion.",
            "matters": "It is the typical endpoint for low- and intermediate-mass stars.",
            "relationships": "Its mass must remain below the Chandrasekhar limit; it cools and fades after formation.",
            "limitation": "A white dwarf is not a low-mass main-sequence star and is not supported by ordinary thermal gas pressure.",
            "notes": "White dwarfs pack roughly stellar mass into an Earth-sized volume. Additional mass can trigger a nova or, in some systems, a Type Ia supernova rather than making a stable arbitrarily massive remnant.",
        },
        {
            "term": "supernova",
            "definition": "A stellar explosion or thermonuclear disruption that produces a rapid, enormous increase in luminosity and ejects or transforms stellar material.",
            "matters": "Supernovae distribute elements, drive interstellar shocks, form compact remnants, and serve as distance probes.",
            "relationships": "Core-collapse events follow massive-star evolution; Type Ia events involve white dwarfs in binary systems.",
            "limitation": "Supernova is a family of mechanisms, not one universal explosion process.",
            "notes": "Spectra and light curves distinguish subclasses and constrain ejecta composition and energy. Not every massive-star collapse produces the same visible outcome.",
        },
        {
            "term": "neutron star",
            "definition": "An extremely compact remnant composed primarily of dense nuclear matter and supported by quantum and nuclear effects.",
            "matters": "It tests physics at densities beyond terrestrial laboratories and powers pulsars and some high-energy transients.",
            "relationships": "It can form after core collapse if the remnant mass is below the black-hole threshold.",
            "limitation": "It is not simply a giant atomic nucleus, and its internal equation of state remains uncertain.",
            "notes": "A neutron star can contain more than a solar mass within a radius of roughly tens of kilometres. Rotation and magnetic fields produce observable pulses when emission beams sweep past Earth.",
        },
        {
            "term": "black hole",
            "definition": "A region of spacetime bounded by an event horizon from which signals cannot escape to distant observers.",
            "matters": "Black holes are predicted endpoints of sufficiently massive collapse and laboratories for strong gravity.",
            "relationships": r"For a nonrotating mass, the Schwarzschild radius is \(2GM/c^2\); accretion and orbital motion reveal the object indirectly.",
            "limitation": "Black holes do not pull more strongly than the same mass at the same distance, and the event horizon is not a solid surface.",
            "notes": "Most black-hole observations concern hot surrounding matter, gravitational effects, or gravitational waves rather than light from inside the horizon. Spin and charge modify the simplest model.",
            "equation": r"r_s=\frac{2GM}{c^2}",
        },
    ],
    11: [
        {
            "term": "disk",
            "definition": "The flattened rotating component of the Milky Way containing much of its gas, dust, and ongoing star formation.",
            "matters": "It is the Galaxy component in which the Sun resides and where spiral structure is most visible.",
            "relationships": "The disk includes thin and thick stellar populations and surrounds the central bulge.",
            "limitation": "It is not razor-thin or perfectly circular, and dust obscures optical views through it.",
            "notes": "Young stars and molecular clouds concentrate near the thin disk, while older stars occupy a thicker distribution. Infrared and radio observations penetrate dust better than visible light.",
        },
        {
            "term": "bulge",
            "definition": "The dense, centrally concentrated stellar component of a disk galaxy.",
            "matters": "Its stars and motions reveal the Milky Way's formation history and central gravitational environment.",
            "relationships": "The Milky Way's bulge is associated with a bar and surrounds the central supermassive black hole.",
            "limitation": "A bulge is not simply a scaled-up spherical star cluster; it can be barred, boxy, and dynamically complex.",
            "notes": "Bulge populations are generally older than the thin disk, but age and metallicity distributions overlap. Dust makes its three-dimensional structure difficult to infer from optical images alone.",
        },
        {
            "term": "halo",
            "definition": "A roughly extended, low-density component surrounding the Galaxy's disk and bulge.",
            "matters": "It contains old stars and globular clusters and is embedded in a much more massive dark-matter halo.",
            "relationships": "Halo-star orbits differ from orderly disk rotation; streams record disrupted satellites.",
            "limitation": "The sparse visible stellar halo is not the same thing as the dominant dark-matter halo.",
            "notes": "Stellar-halo metallicities and streams preserve evidence of mergers. Mapping the dark halo relies on gravitational tracers rather than direct images.",
        },
        {
            "term": "spiral arm",
            "definition": "A curved region in a disk galaxy with enhanced gas, dust, young stars, and star formation.",
            "matters": "Spiral arms organize where recent star formation is seen and help map galactic structure.",
            "relationships": "They are commonly treated as patterns or waves through which stars and gas move, not permanent material spokes.",
            "limitation": "Visible bright stars overemphasize recent star formation and do not trace all of the disk's mass.",
            "notes": "Gas compression near an arm can promote cloud collapse. Different tracers—ionized gas, molecular gas, old stars—need not peak at exactly the same location.",
        },
        {
            "term": "interstellar medium",
            "definition": "The gas, dust, cosmic rays, magnetic fields, and radiation occupying space between stars.",
            "matters": "It supplies material for new stars and receives energy and enriched elements from stellar winds and supernovae.",
            "relationships": "Its cold clouds, warm phases, and hot plasma participate in a star-formation feedback cycle.",
            "limitation": "Interstellar space is not empty, but its density is far below ordinary laboratory vacua and varies enormously.",
            "notes": "Different wavelengths trace different phases: radio molecules, optical emission lines, infrared dust, and X-ray plasma. Observed extinction is both a nuisance and a measurement of dust.",
        },
        {
            "term": "rotation curve",
            "definition": "A graph of orbital speed versus distance from a galaxy's center.",
            "matters": "It tests how enclosed gravitating mass changes with radius.",
            "relationships": r"For circular motion, \(v^2=GM(<r)/r\); flat outer curves imply increasing enclosed mass beyond most visible light.",
            "limitation": "Interpreting a curve assumes orbital geometry and must account for bars, warps, gas motions, and measurement uncertainties.",
            "notes": r"If most mass were centrally concentrated, outer speed would decline approximately as \(r^{-1/2}\). The observed near-flat behavior motivates extended dark-matter distributions or alternative gravity tests.",
            "equation": r"v^2(r)=\frac{GM(<r)}{r}",
        },
        {
            "term": "dark matter",
            "definition": "Matter inferred from gravity that does not emit, absorb, or scatter enough electromagnetic radiation to be seen directly.",
            "matters": "It explains a large share of the gravitational mass in galaxies, clusters, and cosmic structure models.",
            "relationships": "Rotation curves, gravitational lensing, cluster dynamics, and cosmology provide independent evidence.",
            "limitation": "Dark matter names an inferred component, not a confirmed particle identity; ordinary faint matter cannot explain all observations.",
            "notes": "A strong case comes from converging measurements with different systematics. The term should not be confused with dark energy, which affects cosmic expansion rather than clustering like matter.",
        },
    ],
    12: [
        {
            "term": "spiral galaxy",
            "definition": "A galaxy with a rotating stellar disk, gas and dust, and often spiral arms surrounding a central bulge.",
            "matters": "Its structure connects angular momentum, ongoing star formation, and environmental history.",
            "relationships": "Spirals tend to contain colder gas and bluer young populations than many ellipticals.",
            "limitation": "Morphology alone does not specify mass, age, or a fixed evolutionary stage.",
            "notes": "Bars are common within spiral galaxies and can move gas inward. Inclination and wavelength can hide or exaggerate spiral structure.",
        },
        {
            "term": "elliptical galaxy",
            "definition": "A galaxy with a smooth ellipsoidal light distribution and little obvious disk or spiral structure.",
            "matters": "Ellipticals provide evidence about stellar aging, mergers, gas loss, and pressure-supported dynamics.",
            "relationships": "Their stars commonly have more randomly oriented motions than stars in a cold rotating disk.",
            "limitation": "Elliptical does not mean featureless or uniformly old, and some retain gas, dust, or recent star formation.",
            "notes": "The largest ellipticals often occupy cluster centers and may have complex assembly histories. Apparent shape is a projected view of a three-dimensional stellar distribution.",
        },
        {
            "term": "irregular galaxy",
            "definition": "A galaxy lacking a clear spiral or elliptical form at the observed scale and wavelength.",
            "matters": "Irregular structure can expose tidal disturbance, intense star formation, or low-mass disk dynamics.",
            "relationships": "Some irregulars result from interactions, while others are isolated dwarf systems.",
            "limitation": "The label describes appearance, not one formation mechanism.",
            "notes": "Resolution and observing band affect classification: a high-redshift galaxy may appear irregular because only bright star-forming clumps are detected. Kinematic data can reveal order hidden from images.",
        },
        {
            "term": "redshift",
            "definition": "The fractional increase in observed wavelength relative to a laboratory or emitted reference wavelength.",
            "matters": "It measures line-of-sight motion at low speeds and traces cosmic expansion for distant galaxies.",
            "relationships": r"It is defined by \(z=(\lambda_{\rm obs}-\lambda_0)/\lambda_0\); at small \(z\), \(v\approx cz\).",
            "limitation": "Large cosmological redshift is not adequately described as an ordinary speed through static space.",
            "notes": "Spectral patterns establish redshift by matching multiple lines. Peculiar velocity adds scatter to the expansion relation, especially for nearby galaxies.",
            "equation": r"z=\frac{\lambda_{\rm obs}-\lambda_0}{\lambda_0}",
        },
        {
            "term": "starburst",
            "definition": "An episode of unusually intense star formation relative to a galaxy's past average or available gas.",
            "matters": "Starbursts rapidly transform gas, dust, luminosity, chemical enrichment, and feedback.",
            "relationships": "Interactions and mergers can compress gas and trigger bursts; massive young stars then produce ultraviolet light and supernovae.",
            "limitation": "Bright infrared or ultraviolet emission can be obscured or contaminated by an active nucleus.",
            "notes": "A starburst is temporary because rapid gas consumption and feedback cannot continue indefinitely. Star-formation rates require wavelength-dependent calibration and assumptions about the stellar population.",
        },
        {
            "term": "active galactic nucleus",
            "definition": "A compact, unusually luminous galactic center powered by matter accreting onto a supermassive black hole.",
            "matters": "AGN can outshine their host galaxies and influence surrounding gas through radiation, winds, and jets.",
            "relationships": "Accretion converts gravitational energy into radiation; orientation and obscuration help explain observed AGN classes.",
            "limitation": "A central point source is not automatically an AGN, and black-hole mass alone does not set luminosity without fuel.",
            "notes": "Spectra, variability, radio jets, and high-energy emission provide complementary diagnostics. AGN feedback is important in galaxy-evolution models but is difficult to quantify.",
        },
        {
            "term": "merger",
            "definition": "The gravitational interaction and eventual combination of two or more galaxies.",
            "matters": "Mergers rearrange stellar orbits, compress gas, trigger star formation or AGN activity, and build galactic structure.",
            "relationships": "Tidal tails and distorted morphologies are evidence of interaction; dark-matter halos strongly affect the dynamics.",
            "limitation": "Most stars do not collide directly because stellar separations are enormous, even though the galaxies merge.",
            "notes": "Dynamical friction transfers orbital energy and helps galaxy cores coalesce. The final morphology depends on mass ratio, gas fraction, orbit, and feedback.",
        },
    ],
    13: [
        {
            "term": "expansion",
            "definition": "The time-dependent increase of distances between sufficiently separated, unbound cosmic locations as described by the changing cosmological scale factor.",
            "matters": "It organizes the redshift-distance relation and the thermal history of the universe.",
            "relationships": r"The Hubble parameter is \(\dot a/a\); redshift links observed wavelength to the scale factor at emission.",
            "limitation": "Expansion does not make bound systems such as atoms, people, or the solar system grow.",
            "notes": "Galaxies can also have peculiar velocities through their local environment. Expansion is homogeneous on large scales and has no unique spatial center within the standard model.",
            "equation": r"H(t)=\frac{\dot a}{a}",
        },
        {
            "term": "Hubble-Lemaitre law",
            "definition": "The approximate proportionality between recession velocity and distance for nearby galaxies participating in cosmic expansion.",
            "matters": "Its slope measures the present expansion rate and provides a first distance-redshift tool.",
            "relationships": r"The low-redshift form is \(v=H_0d\); scatter includes peculiar velocities and distance errors.",
            "limitation": "It is a local approximation and must be replaced by a cosmological model at large redshift.",
            "notes": r"Estimating \(H_0\) requires independent distances and calibrated redshifts. Different modern methods have produced a well-known tension that is still investigated.",
            "equation": r"v=H_0d",
        },
        {
            "term": "cosmic microwave background",
            "definition": "Nearly uniform microwave radiation released when the early universe became transparent, now cooled by expansion.",
            "matters": "Its spectrum and tiny anisotropies provide precise evidence about the early universe and cosmological parameters.",
            "relationships": "Expansion stretches the radiation to a present blackbody temperature near 2.7 K; anisotropies seed later structure.",
            "limitation": "It is not light from the Big Bang's first instant and does not come from one distant shell centered on Earth.",
            "notes": "The CMB last-scattering surface is seen in every direction because every observer is surrounded by their own observable boundary. Foreground emission must be separated from the cosmological signal.",
        },
        {
            "term": "lookback time",
            "definition": "The elapsed cosmic time between emission of the light we observe and its reception now.",
            "matters": "It makes distant observations a record of earlier stages of cosmic history.",
            "relationships": "Lookback time depends on redshift and the expansion history, not simply distance divided by today's Hubble speed.",
            "limitation": "It is not the current age of the observed object or its present-day distance.",
            "notes": "At substantial redshift, several distance definitions coexist because spacetime evolves while light travels. A cosmological model is needed to translate redshift into time.",
        },
        {
            "term": "dark matter",
            "definition": "A nonluminous gravitating matter component that clusters and helps build galaxies and larger structures.",
            "matters": "Cosmological structure grows too slowly from the observed early fluctuations without a dominant cold matter component.",
            "relationships": "CMB anisotropies, lensing, galaxy clustering, and galaxy dynamics constrain its abundance and distribution.",
            "limitation": "Its particle nature remains unknown, and it is distinct from dark energy.",
            "notes": "In cosmology, dark matter supplies gravitational wells into which ordinary gas falls. Models must match evidence from both early-universe and late-time structure.",
        },
        {
            "term": "dark energy",
            "definition": "The name for the component or effect associated with the observed accelerated expansion of the universe.",
            "matters": "It dominates the present cosmic energy budget in the standard model and changes distance-redshift relations.",
            "relationships": "Supernova distances, CMB constraints, and large-scale clustering jointly constrain its behavior.",
            "limitation": "The label does not identify a known substance; a cosmological constant is the simplest model, not a settled mechanism.",
            "notes": "Dark energy remains smooth on galaxy scales in the standard picture and does not behave like unseen matter in rotation curves. Its pressure and equation-of-state parameter govern expansion dynamics.",
        },
        {
            "term": "large-scale structure",
            "definition": "The cosmic network of galaxies, groups, clusters, filaments, walls, and voids on millions to billions of light-years.",
            "matters": "Its statistics test how primordial fluctuations grew under gravity and expansion.",
            "relationships": "Dark matter supplies the main gravitational framework; galaxy surveys trace it with selection-dependent bias.",
            "limitation": "Survey maps are incomplete observational samples, not direct three-dimensional pictures of all matter.",
            "notes": "Redshift gives a radial coordinate only after applying a cosmological model and correcting for peculiar velocities. Simulations compare predicted clustering with observed statistics.",
        },
    ],
    14: [
        {
            "term": "survey",
            "definition": "A systematic observing program designed to measure a defined sample or region with documented selection and calibration.",
            "matters": "Surveys turn individual detections into population-level evidence.",
            "relationships": "Cadence, depth, sky area, wavelength, and selection function determine which phenomena and populations are measurable.",
            "limitation": "A large sample is not automatically representative if the selection process is biased.",
            "notes": "A reproducible survey states detection thresholds, masks, observing cadence, and data processing. Archive users must understand these choices before drawing demographic conclusions.",
        },
        {
            "term": "selection effect",
            "definition": "A systematic difference between the population observed and the population that exists, caused by how targets enter a sample.",
            "matters": "It can create false trends or hide real populations even when every measurement is individually accurate.",
            "relationships": "Detection threshold, survey cadence, wavelength, geometry, and follow-up choices define a selection function.",
            "limitation": "It is not random noise and cannot always be removed by increasing sample size.",
            "notes": "Early exoplanet catalogs favored massive close-in planets because those systems produced stronger, faster signals. Correct inference models the probability that each kind of object would have been detected.",
        },
        {
            "term": "transit",
            "definition": "A periodic decrease in observed stellar flux when an orbiting body crosses the star's apparent disk.",
            "matters": "Transit depth estimates planet-to-star area ratio and repeated timing determines orbital period.",
            "relationships": r"For a small dark planet, \(\Delta F/F\approx(R_p/R_\star)^2\); spectroscopy during transit can probe an atmosphere.",
            "limitation": "Only favorably aligned systems transit, and stellar variability or blended eclipsing binaries can mimic the signal.",
            "notes": "Transit duration and shape constrain impact parameter and stellar density when combined with a model. Planet radius still depends on knowing the star's radius.",
            "equation": r"\frac{\Delta F}{F}\approx\left(\frac{R_p}{R_\star}\right)^2",
        },
        {
            "term": "radial velocity",
            "definition": "The component of an object's velocity along the observer's line of sight, inferred from Doppler shifts.",
            "matters": "Periodic stellar radial-velocity changes reveal the gravitational pull of orbiting companions.",
            "relationships": "Combined with a transit, it constrains planet mass and density; the signal also depends on orbital inclination.",
            "limitation": "Without inclination information it usually yields a minimum companion mass, and stellar activity can imitate a planet.",
            "notes": "The method measures the star's reflex motion around the system center of mass. Multiple spectral lines and activity indicators help separate orbital motion from spots and pulsations.",
        },
        {
            "term": "multi-messenger astronomy",
            "definition": "The coordinated study of an event or source using different carriers such as electromagnetic radiation, gravitational waves, neutrinos, and cosmic rays.",
            "matters": "Different messengers probe complementary regions and physical processes that one channel alone cannot reveal.",
            "relationships": "Timing and sky localization link detections; physical models must explain all messenger data consistently.",
            "limitation": "Coincidence is not automatically association, and each messenger has distinct backgrounds and localization limits.",
            "notes": "A robust association quantifies chance-coincidence probability and respects instrument latency and sky coverage. Non-detections can also constrain models.",
        },
        {
            "term": "biosignature",
            "definition": "An observable feature whose presence, abundance, pattern, or disequilibrium could indicate biological activity.",
            "matters": "It frames the search for life as inference from measurements rather than recognition of a single Earth-like molecule.",
            "relationships": "Atmospheric spectra, surface reflectance, environmental context, and planetary evolution all enter interpretation.",
            "limitation": "No proposed biosignature is automatically proof of life; abiotic false positives and biological false negatives must be tested.",
            "notes": "A persuasive claim requires multiple compatible lines of evidence and elimination of plausible nonbiological production pathways. Detectability also depends on clouds, stellar contamination, and instrument sensitivity.",
        },
        {
            "term": "uncertainty",
            "definition": "A quantified statement of the range and structure of values consistent with measurement and model limitations.",
            "matters": "It determines how strongly data support a claim and whether two results are meaningfully different.",
            "relationships": "Random noise, calibration systematics, model assumptions, and sample variance contribute in different ways.",
            "limitation": "Uncertainty is not ignorance or error in the sense of a mistake, and a narrow statistical interval does not include every systematic risk.",
            "notes": "Good reporting states what the interval means and how it was obtained. Repeated precision cannot compensate for an unrecognized bias shared by all measurements.",
        },
        {
            "term": "source evaluation",
            "definition": "The structured assessment of a claim's provenance, evidence, methods, expertise, conflicts, and consistency with independent results.",
            "matters": "It separates persuasive presentation from reliable astronomical knowledge.",
            "relationships": "Primary data, peer-reviewed analysis, mission documentation, uncertainty, and reproducibility form an evidence chain.",
            "limitation": "Authority alone does not prove a claim, while a single anomaly does not overturn a well-tested model without comparable evidence.",
            "notes": "Students should trace headlines back to the underlying paper or data release, identify what was measured versus inferred, and check whether later work confirms the result. Evaluation is strongest when criteria are applied consistently to favored and disfavored claims.",
        },
    ],
}
