from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LECTURES = ROOT / "lectures"
REFERENCE_LOG = ROOT / "reference-log.md"

VISUAL_TEXT = {
    2: ("Condensation Sequence", "hot inner disk", "frost line", "icy solids", "Temperature sets chemistry; migration can later rearrange the architecture."),
    3: ("Orbital Resonance", "inner orbit", "2:1 period ratio", "outer orbit", "Repeated alignments exchange energy and angular momentum."),
    4: ("Differentiated Interior", "metal core", "rocky mantle", "volatile layer", "Density and magnetic evidence constrain unseen interiors."),
    5: ("Surface Age Evidence", "old cratered terrain", "young smooth plains", "resurfacing boundary", "Crater density is a relative clock only when preservation is comparable."),
    7: ("Airless Surface Record", "fresh crater rays", "mature regolith", "space weathering", "No atmosphere means impact and exposure records can persist."),
    8: ("Mars Water Evidence", "valley network", "delta deposit", "hydrated minerals", "Geomorphology plus mineralogy is stronger than either alone."),
    11: ("Small Body Evidence", "asteroid", "comet", "meteorite sample", "Primitive material and impact dynamics connect formation to hazard."),
    12: ("Exoplanet Selection Effects", "transit depth", "radial velocity", "missing small worlds", "Detection methods shape the planet population we see first."),
    13: ("Habitability Evidence Chain", "liquid environment", "energy source", "chemistry", "Habitability is a converging evidence argument, not a distance label."),
    14: ("Mission Traceability", "science question", "measurement", "instrument", "A mission succeeds when each payload measurement tests a defined claim."),
}


def svg_for(n: int) -> str:
    title, a, b, c, footer = VISUAL_TEXT[n]
    colors = ["#0f6b78", "#b87911", "#102a43"]
    return f"""<svg class="lecture-visual" data-astr120-visual="{n:02d}" viewBox="0 0 960 560" role="img" aria-label="{title} diagram">
  <rect width="960" height="560" fill="#fbfcfd"/>
  <text x="42" y="58" font-size="30" fill="#102a43" font-family="Segoe UI, sans-serif">{title}</text>
  <circle cx="205" cy="280" r="70" fill="{colors[0]}" opacity="0.88"/>
  <rect x="400" y="210" width="180" height="140" rx="18" fill="{colors[1]}" opacity="0.78"/>
  <polygon points="740,190 840,280 740,370 640,280" fill="{colors[2]}" opacity="0.82"/>
  <path d="M280 280 L400 280 M580 280 L640 280" stroke="#5b6773" stroke-width="5" marker-end="url(#arrow{n})"/>
  <defs><marker id="arrow{n}" markerWidth="12" markerHeight="12" refX="10" refY="4" orient="auto"><path d="M0,0 L0,8 L12,4 z" fill="#5b6773"/></marker></defs>
  <text x="145" y="405" font-size="22" fill="#102a43" font-family="Segoe UI, sans-serif">{a}</text>
  <text x="420" y="405" font-size="22" fill="#102a43" font-family="Segoe UI, sans-serif">{b}</text>
  <text x="650" y="405" font-size="22" fill="#102a43" font-family="Segoe UI, sans-serif">{c}</text>
  <text x="42" y="515" font-size="19" fill="#5b6773" font-family="Segoe UI, sans-serif">{footer}</text>
</svg>"""


def main() -> None:
    for n in VISUAL_TEXT:
        path = LECTURES / f"lecture-{n:02d}-slides.html"
        text = path.read_text(encoding="utf-8")
        pattern = re.compile(r"<figure><svg viewBox=\"0 0 960 560\".*?</svg><figcaption>(.*?)</figcaption></figure>", re.S)
        replacement = f"<figure>{svg_for(n)}<figcaption>{VISUAL_TEXT[n][4]}</figcaption></figure>"
        text, count = pattern.subn(replacement, text, count=1)
        if count == 0:
            raise RuntimeError(f"No generated SVG block replaced in {path}")
        path.write_text(text, encoding="utf-8")

    log = REFERENCE_LOG.read_text(encoding="utf-8") if REFERENCE_LOG.exists() else "# ASTR 120 Reference Log\n"
    for n, (title, *_rest) in VISUAL_TEXT.items():
        entry = f"| lecture-{n:02d}-slides.html | {title} original diagram | Generated SVG | local lecture slide SVG generated by `src/polish_astr120_visuals.py` | VERIFIED | Original course diagram; no external license; generated 2026-09-23; visual encodes lecture-specific reasoning. |"
        if f"lecture-{n:02d}-slides.html | {title} original diagram" not in log:
            log += entry + "\n"
    REFERENCE_LOG.write_text(log, encoding="utf-8")
    print("polished ASTR120 visuals")


if __name__ == "__main__":
    main()
