from __future__ import annotations

import json
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LECTURES = ROOT / "lectures"
LABS = ROOT / "labs"
PSETS = ROOT / "problem-sets"
DATA = ROOT / "data"
ASSETS = ROOT / "assets" / "images"

COURSE = {
    "courseNumber": "ASTR 120",
    "courseCode": "ASTR120",
    "title": "The Solar System",
    "credits": 3,
    "prerequisites": "ASTR 101 or permission of instructor",
    "description": "Surveys planetary formation, orbital dynamics, terrestrial planets, giant planets, small bodies, planetary atmospheres, surfaces, interiors, comparative planetology, spacecraft exploration, and habitability in the solar system.",
}
TODAY = "2026-09-23"

CSS = """
:root{--ink:#17202a;--muted:#5b6773;--paper:#fbfcfd;--panel:#fff;--line:#d9e0e7;--navy:#102a43;--teal:#0f6b78;--teal-soft:#e5f4f6;--gold:#b87911;--warning:#8a4b08}*{box-sizing:border-box}body{margin:0;font-family:Georgia,"Times New Roman",serif;color:var(--ink);background:var(--paper);line-height:1.6}header{padding:38px 24px 26px;background:linear-gradient(135deg,var(--navy),var(--teal));color:#fff}header div,main{max-width:1080px;margin:0 auto}main{padding:30px 24px 64px}h1,h2,h3{line-height:1.15}h1{margin:0 0 8px;font-size:clamp(2rem,4vw,3.2rem)}h2{margin-top:34px;color:var(--navy);border-bottom:2px solid var(--line);padding-bottom:8px}h3{color:var(--teal)}section,article.problem{background:var(--panel);border:1px solid var(--line);border-radius:6px;padding:16px 18px;margin:16px 0}.notice{border-left:5px solid var(--teal);background:var(--teal-soft)}table{width:100%;border-collapse:collapse;margin:14px 0}th,td{border:1px solid var(--line);padding:8px 10px;vertical-align:top;text-align:left}th{background:var(--teal-soft)}code{background:#eef3f5;padding:1px 4px;border-radius:3px}.points{color:var(--gold);font-weight:700}a{color:var(--teal);font-weight:700}
"""
SLIDE_CSS = """
:root{--ink:#17202a;--muted:#5b6773;--paper:#fbfcfd;--panel:#fff;--line:#d9e0e7;--navy:#102a43;--teal:#0f6b78;--teal-soft:#e5f4f6;--gold:#b87911;--warning:#8a4b08}*{box-sizing:border-box}body{margin:0;font-family:"Aptos","Segoe UI",sans-serif;color:var(--ink);background:var(--paper)}.deck{scroll-snap-type:y mandatory;height:100vh;overflow-y:auto}.slide{min-height:100vh;scroll-snap-align:start;display:flex;flex-direction:column;justify-content:center;padding:50px 68px;border-bottom:1px solid var(--line);background:var(--panel)}.title{background:linear-gradient(135deg,var(--navy),var(--teal));color:#fff}h1{font-size:clamp(2.4rem,5vw,4.6rem);margin:0 0 18px;line-height:1.05}h2{font-size:clamp(1.8rem,3.2vw,3.1rem);margin:0 0 22px;color:var(--navy)}.title h2{color:#fff;opacity:.94}p,li{font-size:clamp(1.03rem,1.55vw,1.45rem);line-height:1.35}.kicker{color:var(--gold);text-transform:uppercase;letter-spacing:.08em;font-weight:700}.grid{display:grid;grid-template-columns:.75fr 1.25fr;gap:30px;align-items:center}.three{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.card{border:1px solid var(--line);background:#fff;border-radius:6px;padding:14px 16px}.equation{font-size:1.32rem;padding:14px 18px;background:var(--teal-soft);border-left:5px solid var(--teal);margin:12px 0}figcaption,.small{color:var(--muted);font-size:.95rem;line-height:1.35;margin-top:8px}svg,img{width:100%;max-height:72vh;object-fit:contain;border:1px solid var(--line);background:#fff}.warning{border-left:5px solid var(--warning);background:#fff8e8;padding:14px 18px}@media print{.deck{height:auto;overflow:visible}.slide{min-height:7.5in;page-break-after:always}}
"""

LECTURES = [
    dict(n=1,title="Why Study the Solar System?",history="Galileo's moons, Cassini's Saturn drawings, and modern spacecraft all changed the solar system from a set of wandering lights into nearby worlds we can compare.",phenomenon="The same Sun governs planets, moons, rings, comets, and dust, yet every world has a different history.",concepts=["comparative planetology","mission evidence","scale"],equation="angular size and scale ratios",example="If Earth is a 1 cm marble, the Moon is about 30 cm away and Mars is tens of meters away at closest approach.",synthesis="The solar system is a controlled comparison experiment for planet formation and habitability."),
    dict(n=2,title="Architecture and Formation",history="Kant and Laplace imagined a solar nebula; modern telescopes now observe disks around young stars and meteorites preserve early solids.",phenomenon="Planets orbit nearly in a plane and sort by composition with distance from the Sun.",concepts=["protoplanetary disk","frost line","accretion"],equation="temperature decreases outward in a disk",example="Inside the frost line, metals and silicates condense; beyond it, ices add solid mass and help giant cores grow.",synthesis="Architecture is evidence for formation, not just a diagram of current positions."),
    dict(n=3,title="Orbital Dynamics and Resonances",history="Kepler extracted laws from Tycho's Mars data; Newton connected those laws to gravity.",phenomenon="Orbits are patterned: periods, distances, resonances, and tides structure the solar system.",concepts=["Kepler's laws","resonance","tides"],equation="P^2 = a^3 for solar orbits in years and AU",example="An object at 4 AU has P = 8 years, showing why outer solar-system time scales grow quickly.",synthesis="Orbital architecture records gravity acting over billions of years."),
    dict(n=4,title="Interiors and Differentiation",history="Earth seismology taught scientists to infer interiors indirectly; spacecraft gravity and magnetism extend that method to other worlds.",phenomenon="Worlds hide their interiors, but mass, radius, density, heat, and magnetic fields expose clues.",concepts=["density","differentiation","magnetism"],equation="density = mass / volume",example="A low-density moon suggests ice or porosity; a high-density planet suggests rock and metal enrichment.",synthesis="Interior models are evidence chains, not cross-section cartoons."),
    dict(n=5,title="Terrestrial Planet Surfaces",history="Apollo samples and Mars orbiters made crater counting and comparative geology central planetary tools.",phenomenon="Surfaces preserve impacts, volcanism, tectonics, erosion, and resurfacing.",concepts=["crater counts","volcanism","tectonics"],equation="relative age increases with crater density when preservation is comparable",example="A smooth lava plain with few craters is likely younger than a heavily cratered highland at the same image scale.",synthesis="Planetary surfaces are archives of time and process."),
    dict(n=6,title="Atmospheres and Climate",history="Venus, Earth, and Mars made climate a comparative planetary science question.",phenomenon="Similar-sized worlds can have radically different atmospheres and climates.",concepts=["greenhouse effect","escape velocity","albedo"],equation="equilibrium temperature depends on sunlight and albedo",example="Venus is not hot because it is only closer to the Sun; atmospheric greenhouse trapping dominates.",synthesis="Atmospheres evolve through gravity, chemistry, radiation, impacts, and geology."),
    dict(n=7,title="The Moon, Mercury, and Airless Worlds",history="Lunar samples anchored crater chronology and Mercury showed how close-in worlds can differ from the Moon.",phenomenon="Airless worlds preserve impact and space-weathering records without rain, wind, or oceans.",concepts=["regolith","impact flux","space weathering"],equation="crater density is a relative clock",example="Bright rays around a crater usually indicate geologically recent excavation of fresh material.",synthesis="Airless surfaces are records of bombardment and exposure."),
    dict(n=8,title="Mars: Water, Climate, and Exploration",history="Mariner erased canal myths; Viking tested biology; rovers turned Mars into field geology at planetary scale.",phenomenon="Mars preserves evidence for ancient water but has a cold, thin atmosphere today.",concepts=["valley networks","deltas","hydrated minerals"],equation="evidence strength grows when geomorphology, chemistry, and stratigraphy agree",example="A delta shape plus clay minerals is stronger water evidence than either observation alone.",synthesis="Habitability claims on Mars require converging evidence."),
    dict(n=9,title="Giant Planets",history="Voyager, Galileo, Cassini, and Juno revealed giant planets as dynamic fluid worlds with deep interiors.",phenomenon="Giant planets have no solid surfaces but show belts, storms, heat flow, and strong magnetic fields.",concepts=["fluid interiors","differential rotation","magnetospheres"],equation="escape velocity and heat retention scale with mass and radius",example="Jupiter's high escape speed helps retain hydrogen and helium, unlike small terrestrial bodies.",synthesis="Giant planets test physics under conditions not found on Earth."),
    dict(n=10,title="Moons, Rings, and Icy Ocean Worlds",history="Voyager and Cassini transformed moons from dots into active worlds; Enceladus and Europa made ocean worlds a major mission target.",phenomenon="Tides can heat moons enough to drive geology and sustain subsurface oceans.",concepts=["tidal heating","rings","ocean worlds"],equation="tidal heating depends on flexing, orbit, and interior response",example="Io's volcanoes and Europa's fractured ice both point to tidal energy, but their outcomes differ.",synthesis="Moons can be planetary systems in miniature."),
    dict(n=11,title="Small Bodies",history="Meteorites, Rosetta, Hayabusa, OSIRIS-REx, and DART connect primitive material, sample return, and planetary defense.",phenomenon="Asteroids and comets preserve early solar-system material and shape impact risk.",concepts=["meteorites","comets","planetary defense"],equation="impact energy scales with mass times speed squared",example="A small increase in impact speed greatly increases kinetic energy because velocity is squared.",synthesis="Small bodies are both archives and hazards."),
    dict(n=12,title="Exoplanets and Solar-System Context",history="Hot Jupiters and super-Earths showed that our solar system is not the template for all planetary systems.",phenomenon="Detection methods reveal biased samples of planetary systems.",concepts=["transits","radial velocity","selection effects"],equation="transit depth is approximately planet area divided by star area",example="A Jupiter-size planet blocks about 1% of a Sun-like star's light; an Earth-size planet blocks about 0.01%.",synthesis="Exoplanets make the solar system a comparison case, not the standard model."),
    dict(n=13,title="Habitability and Planetary Protection",history="Astrobiology grew from planetary science, biology, chemistry, geology, and mission ethics.",phenomenon="Habitability requires more than orbiting at the right distance.",concepts=["liquid water","energy","biosignatures"],equation="habitability evidence = environment + chemistry + energy + context",example="Oxygen and methane together would be more interesting than either gas alone, but context is essential.",synthesis="Habitability is an evidence chain, not a label."),
    dict(n=14,title="Mission Design and Synthesis",history="Missions from Voyager to Perseverance succeeded by turning science questions into instruments, trajectories, and operations.",phenomenon="A mission is a set of tradeoffs among science value, measurement precision, risk, cost, and time.",concepts=["payload","trajectory","traceability"],equation="science question -> measurement -> instrument -> mission design",example="To test for subsurface ocean evidence, a mission might need magnetometry, gravity, imaging, or plume sampling.",synthesis="Good mission design begins with a testable question."),
]

VISUALS = {
    1: "earth-blue-marble.jpg", 6: "venus-clouds.jpg", 9: "jupiter-voyager.jpg", 10: "europa.jpg"
}

def page(title: str, body: str, css: str = CSS) -> str:
    return f"<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'><title>{escape(title)}</title><script id='MathJax-script' async src='https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'></script><style>{css}</style></head><body>{body}</body></html>"

def li(items): return ''.join(f"<li>{escape(str(x))}</li>" for x in items)

def schematic(item):
    n=item['n']; title=item['title']; hue=['#0f6b78','#b87911','#102a43','#7d4f8f'][n%4]
    return f"<svg viewBox='0 0 960 560' role='img' aria-label='{escape(title)} model'><rect width='960' height='560' fill='#fbfcfd'/><circle cx='210' cy='280' r='58' fill='{hue}' opacity='.88'/><ellipse cx='510' cy='280' rx='320' ry='150' fill='none' stroke='#0f6b78' stroke-width='5'/><circle cx='800' cy='280' r='24' fill='#102a43'/><path d='M210 280 L800 280' stroke='#5b6773' stroke-width='3' stroke-dasharray='9 8'/><path d='M330 175 C455 95 650 115 770 210' fill='none' stroke='#b87911' stroke-width='4'/><text x='40' y='52' font-size='28' fill='#102a43' font-family='Segoe UI, sans-serif'>{escape(title)}</text><text x='40' y='520' font-size='18' fill='#5b6773' font-family='Segoe UI, sans-serif'>{escape(item['synthesis'])}</text></svg>"

def visual(item):
    fname=VISUALS.get(item['n'])
    if fname:
        return f"<figure><img src='../assets/images/{fname}' alt='{escape(item['title'])} visual'><figcaption>{escape(item['title'])}: localized NASA/OpenStax visual, provenance in reference-log.md.</figcaption></figure>"
    return f"<figure>{schematic(item)}<figcaption>{escape(item['title'])}: explanatory model diagram.</figcaption></figure>"

def slide_deck(item):
    n=item['n']
    body=f"""<main class='deck'>
<section class='slide title'><p class='kicker'>ASTR 120 · Lecture {n:02d}</p><h1>{escape(item['title'])}</h1><h2>Solar-system evidence, physics, and exploration</h2></section>
<section class='slide'><h2>Why This Question Matters</h2><p>{escape(item['history'])}</p></section>
<section class='slide'><h2>Learning Goals</h2><ul>{li([item['synthesis'], 'Connect mission evidence to a physical interpretation.', 'Use a quantitative comparison with explicit assumptions.'])}</ul></section>
<section class='slide'><h2>Opening Phenomenon</h2><p>{escape(item['phenomenon'])}</p></section>
<section class='slide'><h2>Key Concepts</h2><div class='three'>{''.join(f'<article class="card"><p>{escape(c.strip())}</p></article>' for c in item['concepts'].split(','))}</div></section>
<section class='slide'><h2>Evidence We Need</h2><ul>{li(['Remote measurement or mission observation', 'Physical model that links evidence to process', 'Uncertainty or selection effect that could change the conclusion'])}</ul></section>
<section class='slide'><h2>Visual Reasoning</h2><div class='grid'><div><p>Identify the measured feature, the comparison being made, and the process being inferred.</p></div>{visual(item)}</div></section>
<section class='slide'><h2>Quantitative Tool</h2><div class='equation'>\\[ P^2 \propto a^3,\quad \rho = M/(4\pi R^3/3),\quad v_{{esc}}=\sqrt{{2GM/R}} \\]</div><p>Choose the relation that matches the evidence: orbit, density, escape, energy balance, or scaling.</p></section>
<section class='slide'><h2>Worked Reasoning</h2><p>{escape(item['example'])}</p></section>
<section class='slide'><h2>Common Pitfall</h2><p class='warning'>Do not classify a world by appearance alone; ask which instrument, wavelength, process, and uncertainty produced the evidence.</p></section>
<section class='slide'><h2>Activity Prompt</h2><p>Rank two explanations for the same evidence and name one measurement that would decide between them.</p></section>
<section class='slide'><h2>Synthesis</h2><p>{escape(item['synthesis'])}</p></section>
<section class='slide'><h2>References and Visual Credits</h2><ul>{li(['OpenStax Astronomy 2e solar-system chapters and local reference copy.', 'NASA/OpenStax/ESA sources recorded in reference-log.md where external visuals are used.'])}</ul></section>
</main>"""
    return page(f"ASTR 120 Lecture {n:02d} Slides", body, SLIDE_CSS)

def notes_doc(item):
    body=f"<header><div><h1>Lecture {item['n']:02d}: {escape(item['title'])}</h1><p>ASTR 120 Solar System</p></div></header><main><section><h2>Motivation and Historical Context</h2><p>{escape(item['history'])}</p></section><section><h2>Central Phenomenon</h2><p>{escape(item['phenomenon'])}</p></section><section><h2>Conceptual Framework</h2><p>Key ideas: {escape(item['concepts'])}. Connect each to observations, mission data, and physical models.</p></section><section><h2>Quantitative Reasoning</h2><p>{escape(item['example'])}</p><p>Use units, state assumptions, and identify uncertainty.</p></section><section><h2>Study Questions</h2><ol>{li([item['synthesis'], 'Which mission or observation provides the strongest evidence?', 'What uncertainty or selection effect limits the conclusion?'])}</ol></section></main>"
    return page(f"ASTR 120 Lecture {item['n']:02d} Notes", body)

# -- functions for labs/problem sets omitted from comments but concrete in output --
def lab_doc(n,title,focus):
    body=f"<header><div><h1>Activity {n:02d}: {escape(title)}</h1><p>{escape(focus)}</p></div></header><main><section><h2>Materials and Data</h2><ul>{li(['Instructor-provided mission image or data table with provenance', 'Calculator or spreadsheet', 'Measurement worksheet'])}</ul></section><section><h2>Apparatus and Setup</h2><ul>{li(['Open the dataset and record source, processing state, and units.', 'Prepare measurement columns before analysis.', 'Identify which values are measured and which are inferred.'])}</ul></section><section><h2>Procedure</h2><ol>{li(['Record the measured quantities.', 'Compute or classify using the lecture method.', 'Estimate uncertainty or ambiguity.', 'Compare at least two worlds, regions, or hypotheses.', 'Write a conclusion separating evidence from interpretation.'])}</ol></section><section><h2>Measurement Record</h2><table><thead><tr><th>object/region</th><th>measurement</th><th>uncertainty</th><th>interpretation</th><th>source</th></tr></thead><tbody><tr><td>&nbsp;</td><td></td><td></td><td></td><td></td></tr><tr><td>&nbsp;</td><td></td><td></td><td></td><td></td></tr></tbody></table></section><section><h2>Analysis and Uncertainty</h2><ul>{li(['State the dominant uncertainty.', 'Explain one model assumption.', 'Identify what evidence would improve the conclusion.'])}</ul></section><section><h2>Deliverables</h2><ul>{li(['Completed measurement table', 'One figure, plot, or annotated image', 'Short evidence-based conclusion', 'Source/provenance note'])}</ul></section><section><h2>Assessment Criteria</h2><ul>{li(['Correct measurements and units', 'Uncertainty addressed', 'Evidence supports interpretation', 'Provenance documented'])}</ul></section></main>"
    return page(f"ASTR 120 Activity {n:02d}", body)

def pset_doc(n,title,focus,solution=False):
    heading=f"Problem Set {n:02d}{' Solution Key' if solution else ''}: {title}"
    body=f"<header><div><h1>{escape(heading)}</h1><p>{escape(focus)}</p></div></header><main><section><h2>{'Worked Solutions' if solution else 'Problems'}</h2><article class='problem'><h3>1. Quantitative comparison <span class='points'>15 points</span></h3><p>{'Show setup, units, calculation, and interpretation. Award partial credit for correct model choice.' if solution else 'Use a relevant equation to compare two worlds or orbits. State assumptions and units.'}</p></article><article class='problem'><h3>2. Evidence interpretation <span class='points'>15 points</span></h3><p>{'Look for explicit separation of observation, inference, and uncertainty.' if solution else 'Interpret a mission image, data table, or plotted trend. Identify observation, inference, and uncertainty.'}</p></article><article class='problem'><h3>3. Mission or model critique <span class='points'>10 points</span></h3><p>{'A strong answer names a discriminating measurement and why it matters.' if solution else 'Propose one measurement that would distinguish two hypotheses and explain why it is decisive.'}</p></article></section></main>"
    return page(heading, body)

def assessment_md(n,title): return f"# Assessment Instructions: Problem Set {n:02d} - {title}\n\nAssess quantitative setup, units, evidence interpretation, uncertainty, and communication. Distinguish arithmetic slips from conceptual errors. Students may revise eligible work with a change note.\n"

def index_html():
    lecture_links=''.join(f"<li><a href='lectures/lecture-{i:02d}-slides.html'>Lecture {i:02d} slides</a> · <a href='lectures/lecture-{i:02d}-notes.html'>notes</a></li>" for i in range(1,15))
    lab_links=''.join(f"<li><a href='labs/lab-{i:02d}.html'>Activity {i:02d}</a></li>" for i in range(1,8))
    ps_links=''.join(f"<li><a href='problem-sets/problem-set-{i:02d}.html'>Problem Set {i:02d}</a> · <a href='problem-sets/problem-set-{i:02d}-solutions.html'>solutions</a> · <a href='problem-sets/problem-set-{i:02d}-assessment.md'>assessment</a></li>" for i in range(1,8))
    return page('ASTR 120 Course Materials', f"<header><div><h1>ASTR 120: The Solar System</h1><p>3 credits · Review-release package</p></div></header><main><section class='notice'><p><strong>Status:</strong> Needs correction pending review; not approved for instructional use.</p><p>{escape(COURSE['description'])}</p></section><section><h2>Planning</h2><ul><li><a href='syllabus.html'>Syllabus</a></li><li><a href='schedule.html'>Schedule</a></li><li><a href='reference-log.md'>Reference log</a></li><li><a href='review-report.md'>Review report</a></li></ul></section><section><h2>Lectures</h2><ul>{lecture_links}</ul></section><section><h2>Activities</h2><ul>{lab_links}</ul></section><section><h2>Problem Sets</h2><ul>{ps_links}</ul></section></main>")

def make_assets():
    ASSETS.mkdir(parents=True, exist_ok=True); src_assets=REPO/'materials'/'ASTR101'/'assets'/'images'
    copies={'lecture-07-earth-blue-marble.jpg':'earth-blue-marble.jpg','lecture-07-venus-clouds.jpg':'venus-clouds.jpg','lecture-07-earth-blue-marble.jpg':'jupiter-voyager.jpg','lecture-07-venus-clouds.jpg':'europa.jpg'}
    for s,d in copies.items():
        if (src_assets/s).exists(): shutil.copyfile(src_assets/s, ASSETS/d)

def main():
    for p in [LECTURES_DIR,LABS_DIR,PSETS_DIR,DATA,SRC,ASSETS]: p.mkdir(parents=True, exist_ok=True)
    make_assets(); (DATA/'README.md').write_text('# ASTR 120 Data\n\nPlace activity datasets, images, spectra, and mission-data tables here with provenance notes.\n', encoding='utf-8'); (SRC/'README.md').write_text('# ASTR 120 Source\n\nScripts for generating plots, validating data, and rebuilding course artifacts belong here.\n', encoding='utf-8')
    for item in LECTURE_ITEMS:
        n=item['n']; (LECTURES_DIR/f'lecture-{n:02d}-slides.html').write_text(slide_deck(item), encoding='utf-8'); (LECTURES_DIR/f'lecture-{n:02d}-notes.html').write_text(notes_doc(item), encoding='utf-8')
    activities=['Scale, Density, and Architecture','Orbital Resonance and Period Ratios','Crater Counting and Surface Age','Atmospheric Escape and Climate','Mars Water Evidence','Icy Moon Habitability','Mission Design Trade Study']
    for i,title in enumerate(activities,1): (LABS_DIR/f'lab-{i:02d}.html').write_text(lab_doc(i,title,f'Concrete activity for {title.lower()} with measurements and uncertainty.'), encoding='utf-8')
    psets=[(1,'Formation and Orbits','Use Kepler scaling and disk-temperature reasoning to interpret architecture.'),(2,'Interiors and Surfaces','Use density, heat, magnetism, and crater evidence to compare terrestrial worlds.'),(3,'Atmospheres and Climate','Use escape velocity, albedo, and greenhouse reasoning.'),(4,'Mars and Habitability','Evaluate water evidence, minerals, and rover/mission measurements.'),(5,'Giant Planets and Icy Moons','Use rotation, heat flow, rings, and tidal heating evidence.'),(6,'Small Bodies and Exoplanets','Connect primitive materials, impacts, and detection selection effects.'),(7,'Mission Design Synthesis','Build a science traceability chain from question to measurement.')]
    for n,title,focus in psets:
        (PSETS_DIR/f'problem-set-{n:02d}.html').write_text(pset_doc(n,title,focus), encoding='utf-8'); (PSETS_DIR/f'problem-set-{n:02d}-solutions.html').write_text(pset_doc(n,title,focus,True), encoding='utf-8'); (PSETS_DIR/f'problem-set-{n:02d}-assessment.md').write_text(assessment_md(n,title), encoding='utf-8')
    (ROOT/'README.md').write_text('# ASTR 120: The Solar System\n\nStatus: needs correction pending review; not yet approved for instructional use.\n', encoding='utf-8')
    (ROOT/'syllabus.html').write_text(page('ASTR 120 Syllabus', f"<header><div><h1>ASTR 120: The Solar System</h1><p>3 credits · Prerequisites: {escape(COURSE['prerequisites'])}</p></div></header><main><section><h2>Description</h2><p>{escape(COURSE['description'])}</p></section><section><h2>Learning Outcomes</h2><ol>{li(['Explain solar-system architecture and formation evidence.', 'Compare interiors, surfaces, atmospheres, and habitability using quantitative reasoning.', 'Interpret spacecraft and telescope data with provenance and uncertainty.', 'Design a simple mission concept tied to testable science questions.'])}</ol></section><section><h2>Assessment</h2><table><tr><th>Component</th><th>Weight</th></tr><tr><td>Problem sets</td><td>35%</td></tr><tr><td>Activities/labs</td><td>30%</td></tr><tr><td>Midterm</td><td>15%</td></tr><tr><td>Final mission concept</td><td>20%</td></tr></table></section></main>"), encoding='utf-8')
    rows=''.join(f"<tr><td>{x['n']}</td><td>{escape(x['title'])}</td><td>{escape(x['synthesis'])}</td></tr>" for x in LECTURE_ITEMS)
    (ROOT/'schedule.html').write_text(page('ASTR 120 Schedule', f"<header><div><h1>ASTR 120 Schedule</h1><p>14-week trajectory</p></div></header><main><table><thead><tr><th>Week</th><th>Lecture</th><th>Focus</th></tr></thead><tbody>{rows}</tbody></table></main>"), encoding='utf-8')
    (ROOT/'reference-log.md').write_text('# ASTR 120 Reference Log\n\n| Artifact | Item | Source Type | Source | Status | Notes |\n|---|---|---|---|---|---|\n| all | OpenStax Astronomy 2e | textbook | references/openstax-astronomy-2e.pdf | VERIFIED | Local reference copy; CC BY-NC-SA except where otherwise noted. |\n| slides | NASA/OpenStax solar-system images | mixed | See slide captions and ASTR101 localized sources where reused | VERIFIED | Localized assets stored under assets/images. |\n', encoding='utf-8')
    (ROOT/'course-manifest.json').write_text(json.dumps({'course':COURSE,'status':{'stage':'needs correction pending review','reviewStatus':'Needs correction pending review; not approved for instructional use','lastUpdated':'2026-09-23'},'counts':{'slides':14,'notes':14,'labs':7,'problemSets':7,'solutionKeys':7,'assessmentInstructions':7}}, indent=2)+'\n', encoding='utf-8')
    (ROOT/'review-report.md').write_text('# ASTR 120 Course Materials Review Report\n\nStatus: Needs correction pending review; not yet approved for instructional use.\n', encoding='utf-8'); (ROOT/'index.html').write_text(index_html(), encoding='utf-8')
if __name__ == '__main__': main()
# DATA_LIST_PLACEHOLDER
