from __future__ import annotations

import argparse
import re
from html import escape
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LECTURES = ROOT / "lectures"


# This is the course-local source of truth for the terminology explorers and
# matching notes sections.  Each tuple is:
# (term, slide definition, slide significance/relationship, limitation,
#  optional compact equation, expanded notes prose).
TERMS: dict[int, list[tuple[str, str, str, str, str, str]]] = {
    1: [
        ("Comparative planetology", "The study of worlds by comparing how the same physical processes operate under different masses, compositions, or environments.", "It turns Venus, Earth, Mars, moons, and small bodies into controlled contrasts; observables such as density, spectra, and crater abundance test models of formation and evolution.", "A comparison is only fair when measurement quality, spatial scale, and geologic age are comparable.", "", "Comparative planetology asks why worlds that share some initial conditions diverge, and why very different worlds sometimes display similar processes. In this lecture it organizes the course: bulk density constrains composition, spectra constrain materials, and images constrain morphology. The method is strongest when several observables support the same model and weakest when one visually striking example is treated as representative."),
        ("Scale model", "A representation that preserves a stated ratio between model and real lengths, times, masses, or other quantities.", "Scale exposes why planetary diameters, orbital separations, signal travel times, and spacecraft access cannot all be shown faithfully in one ordinary diagram.", "A model that preserves distance may not preserve size, area, brightness, or travel time; the chosen scale must be named.", r"\(s=d_{\rm model}/d_{\rm real}\)", "A scale model is quantitative only when its scale factor and preserved quantity are explicit. Mapping Earth's diameter to 1 cm gives an Earth–Moon distance near 30 cm, but the same model puts even nearby planets tens of metres away. This term connects directly to angular resolution and mission evidence because great separation and small angular size limit what remote images can reveal."),
        ("Bulk density", "A world's total mass divided by the volume implied by its mean radius.", "Density is an early composition diagnostic: rock-metal planets, ice-rich moons, and gas-rich giants occupy different broad regimes.", "Mean density does not uniquely reveal layering, mineralogy, porosity, or compression; interior models require additional evidence.", r"\(\rho=M/(\tfrac{4}{3}\pi R^3)\)", "Bulk density combines two inferred quantities: mass, usually from gravitational effects, and radius, usually from imaging, occultation, or transit geometry. It is a first discriminator among volatile-rich, rocky, and metal-enriched bodies, not a complete interior solution. Later lectures add differentiation, gravity harmonics, magnetic fields, and equations of state to break the degeneracies hidden by one average number."),
        ("Remote sensing", "Measurement of a target without physical contact, using reflected, emitted, or transmitted radiation and sometimes radar.", "Most planetary knowledge begins with wavelength-dependent brightness, spectra, images, or timing measurements that are converted into temperature, composition, shape, or motion.", "Remote measurements depend on calibration, viewing geometry, resolution, and a model connecting signal to physical property.", "", "Remote sensing separates the detector signal from the physical quantity inferred from it. A spectrum may contain absorption bands, but composition follows only after calibration and comparison with laboratory or theoretical spectra. The term therefore links instrument wavelength, spatial resolution, and selection effects to every later claim about surfaces and atmospheres."),
        ("In situ measurement", "A measurement made within the environment being studied by a flyby spacecraft, orbiter, lander, rover, or atmospheric probe.", "Local fields, particles, chemistry, pressure, and texture can test interpretations made from distant observations and provide ground truth.", "A spacecraft samples a restricted place and time; local conditions may not represent an entire planet or moon.", "", "In situ measurements trade broad coverage for direct environmental contact. A rover can determine mineral chemistry at a specific outcrop, while an orbiter maps regional context at lower spatial or compositional detail. Combining the two reduces ambiguity, but landing-site selection creates its own selection effect."),
        ("Selection effect", "A systematic distortion caused by some objects, locations, wavelengths, or outcomes being easier to observe than others.", "It explains why the best imaged, brightest, nearest, or most frequently visited worlds can appear more typical or more active than the full population.", "A selection effect is not random error and cannot be removed merely by collecting more of the same biased observations.", "", "Selection effects shape both solar-system exploration and exoplanet catalogs. Mission targets are chosen for accessibility, safety, and scientific return, so explored terrain is not a random sample. The correct response is to model the selection process, compare complementary datasets, and limit conclusions to the population actually sampled."),
    ],
    2: [
        ("Protoplanetary disk", "A rotating disk of gas and dust around a young star from which planets and smaller bodies can assemble.", "Its temperature, density, composition, and angular momentum provide the initial conditions used to explain nearly coplanar, mostly prograde orbits.", "Disks evolve while planets grow; the present solar system is not a frozen image of the original disk.", "", "A protoplanetary disk forms because collapsing material with angular momentum cannot fall directly into the star. Collisions and gas drag damp motions toward a common plane while material moves inward or outward. Disk observations around young stars support the framework, but reconstructing our own disk also requires meteorites, orbital architecture, and dynamical models."),
        ("Angular momentum", "The conserved measure of rotational motion; for a small body on a nearly circular orbit it scales with mass, orbital speed, and distance from the rotation axis.", "Conservation of angular momentum helps a collapsing cloud flatten and rotate faster, and later constrains migration and orbital exchange.", "Angular momentum can be redistributed among gas, planets, and ejected bodies even though the total of an isolated system is conserved.", r"\(L\approx mvr\)", "Angular momentum is the bookkeeping quantity behind disk formation and much orbital evolution. As a cloud contracts, a smaller characteristic radius requires faster rotation unless torques transfer angular momentum elsewhere. Resonances and migration in Lecture 03 are therefore continuations of formation physics rather than unrelated corrections."),
        ("Condensation sequence", "The ordered appearance of solid materials as cooling gas crosses the temperatures at which different compounds become stable condensates.", "It links disk temperature to the initial availability of metals, silicates, and volatile ices for planet building.", "Condensation predicts local starting materials, not final composition after radial mixing, impacts, atmospheric loss, and migration.", "", "The condensation sequence is an equilibrium guide to which solids can exist at a location in a cooling disk. Refractory metals and silicates condense at higher temperatures than water, carbon dioxide, and other volatile compounds. Meteorite components preserve parts of this history, while planetary migration and later processing explain departures from a simple radial sequence."),
        ("Frost line", "The approximate disk radius beyond which a chosen volatile, commonly water, can remain as solid ice during planet formation.", "Beyond the water frost line, added ice increases the solid inventory available for rapid core growth and changes the composition of planetesimals.", "The frost line is a moving, species-dependent zone rather than a permanent sharp boundary.", r"\(T(r_{\rm frost})\approx T_{\rm cond}\)", "The frost line converts a thermal model into a compositional prediction. Its position changes as accretion heating, stellar luminosity, and disk opacity evolve, and different volatiles have different condensation fronts. It explains a broad trend in available solids, but cannot by itself account for water delivered inward or dry bodies scattered outward."),
        ("Accretion", "Growth by collisions and gravitational capture of dust, pebbles, planetesimals, and planetary embryos.", "Accretion connects microscopic solids to planets and predicts that collision speed, gas drag, and gravitational focusing affect growth rates.", "Not every collision produces growth; high-speed impacts can bounce, erode, fragment, or disrupt bodies.", "", "Accretion is a sequence of regimes rather than one simple sticking process. Dust aggregates, pebble concentration, planetesimal formation, and embryo collisions involve different forces and timescales. Gravitational focusing accelerates growth once bodies become massive, while destructive collisions and migration prevent a monotonic path from grain to planet."),
        ("Planetesimal", "A solid body large enough for gravity and orbital dynamics to dominate its subsequent growth and collisions.", "Planetesimals are the building blocks sampled by asteroids, comets, and meteorites and are central to models of planetary embryo formation.", "The size threshold and formation mechanism are model-dependent; the term does not imply an untouched primitive composition.", "", "Planetesimals bridge disk solids and full planets. Their mutual gravity increases encounter cross sections, while gas drag and resonant interactions alter their orbits. Some survived as small bodies, whereas others melted, differentiated, or were incorporated into larger planets."),
    ],
    3: [
        ("Semi-major axis", "Half the longest diameter of an ellipse; for an orbit it sets the orbit's characteristic size and energy.", "Kepler's third law relates semi-major axis to period, making it measurable through repeated positions or timing.", "It is not the instantaneous star–planet distance except for a circular orbit.", r"\(P^2=a^3\)", r"The semi-major axis is the orbital length scale that appears in Kepler's third law and the two-body orbital energy. An eccentric body moves between periapsis and apoapsis, so its current distance varies even though \(a\) remains fixed in the ideal two-body problem. Perturbations can slowly change \(a\), especially during migration or resonant encounters."),
        ("Orbital period", "The time required for a body to complete one orbit relative to a specified reference direction.", "Period ratios reveal resonances, and period combined with semi-major axis tests the central mass through Keplerian dynamics.", "Sidereal and synodic periods differ; the relevant definition must match the observation.", r"\(P^2=\frac{4\pi^2}{GM}a^3\)", r"An orbital period can be inferred from repeated sky positions, transits, eclipses, or spacecraft tracking. For bodies orbiting the same dominant mass, period rises as \(a^{3/2}\), which makes outer-system processes slow. Apparent recurrence as seen from Earth may instead be a synodic period produced by two moving observers."),
        ("Mean-motion resonance", "A configuration in which two orbital periods are close to a ratio of small integers, causing gravitational kicks to repeat at preferred phases.", "Repeated geometry can protect or destabilize orbits, structure rings and asteroid populations, and maintain moon eccentricities.", "A near-integer period ratio alone does not prove resonant locking; the resonant angle must librate rather than circulate.", r"\(P_2/P_1\approx p/q\)", r"Mean motion is average angular orbital rate, so a \(2{:}1\) resonance repeats conjunction geometry after two inner orbits and one outer orbit. Whether the configuration is truly resonant depends on the behavior of a combination of orbital angles. Resonance exchanges energy and angular momentum and can preserve the eccentricity that powers tidal heating."),
        ("Perturbation", "A deviation from ideal two-body motion caused by additional masses, nonspherical gravity, drag, radiation, or relativity.", "Small accumulated perturbations reveal unseen masses, shape orbital architecture, and must be modeled for spacecraft navigation.", "A perturbation is not necessarily negligible; weak forces acting repeatedly can dominate long-term evolution.", "", "The two-body ellipse is a baseline model, not the full solar system. Planet–planet forces shift orbital elements, oblateness precesses satellite orbits, and atmospheric drag changes low spacecraft trajectories. Identifying the perturbing mechanism is essential before interpreting an orbital anomaly as a new object or new physics."),
        ("Tidal force", "The differential gravitational acceleration across an extended body.", "Tides distort worlds, exchange spin and orbital angular momentum, and can dissipate orbital energy as interior heat.", "Tidal force is a gradient in gravity, not simply strong gravity; dissipation depends on material response and orbital state.", r"\(\Delta g\propto GM R/r^3\)", "Tidal acceleration differs between the near and far sides of a body and therefore scales steeply with separation. Repeated deformation produces heat only when the material response has a lag or internal friction. Tides connect orbital resonance to volcanism on Io, ocean maintenance on icy moons, and gradual spin-orbit evolution."),
        ("Hill sphere", "The region around an orbiting body where its gravity can dominate satellite motion against the tidal influence of the central object.", "It provides a first estimate of where moons or rings can remain bound and how planet mass and orbital distance affect satellite systems.", "Stable satellite orbits occupy only part of the Hill sphere and are altered by eccentricity, inclination, and other perturbers.", r"\(r_H\approx a(m/3M)^{1/3}\)", r"The Hill sphere is derived from the restricted three-body problem and is a useful stability scale, not a hard physical boundary. A planet farther from the Sun or more massive generally controls a larger region. Prograde satellites usually require more conservative distances than the full \(r_H\), and resonances can create additional stable or unstable zones."),
    ],
    4: [
        ("Mean density", "The total mass of a world divided by the volume set by its mean radius.", "It constrains broad rock, metal, ice, gas, and porosity fractions before a detailed interior model is attempted.", "Different mixtures and compression states can share the same mean density.", r"\(\bar{\rho}=3M/(4\pi R^3)\)", "Mean density is a bulk boundary condition on any acceptable interior model. Large planets compress their interiors, so comparing raw densities without pressure effects can mislead. Combining density with moment-of-inertia, gravity, magnetic, seismic, or heat-flow evidence narrows the range of allowed layer structures."),
        ("Differentiation", "Separation of materials into layers according to density and chemical affinity while part of a body is mobile or molten.", "It explains metal-rich cores, silicate mantles, crusts, and the release or storage of heat-producing elements.", "A layered body need not be fully molten today, and later impacts or convection can modify the original layering.", "", "Differentiation requires enough heat for materials to move relative to one another. Dense metal tends to sink while lower-density silicate or ice rises, releasing gravitational energy that can add further heating. The process connects formation energy, radioactive decay, magnetic dynamos, and surface volcanism."),
        ("Moment of inertia", "A measure of how mass is distributed relative to a rotation axis.", "For a known mass and radius, the normalized moment of inertia helps distinguish centrally concentrated from nearly uniform interiors.", "It is usually inferred through rotational response or gravity measurements and is model-dependent when data are sparse.", r"\(I=C\,MR^2\)", r"The coefficient \(C\) is smaller when more mass is concentrated near the center. A uniform sphere has a larger normalized moment than a strongly differentiated planet. Spacecraft tracking, precession, and libration can constrain \(C\), providing information that mean density alone cannot supply."),
        ("Gravity field", "The spatial pattern of gravitational acceleration produced by a body's total mass and its internal mass distribution.", "Tracking spacecraft Doppler shifts and trajectories reveals departures from spherical symmetry, buried structures, and interior concentration.", "Gravity maps do not directly identify composition; several density distributions can reproduce similar fields.", "", "Planetary gravity is expanded into harmonics that describe equatorial bulges and regional mass anomalies. Those coefficients respond to rotation, tides, topography, and internal layering. Interpreting them requires shape and rotation data, which is why gravity is most powerful when paired with imaging or altimetry."),
        ("Dynamo", "A process in which motion of electrically conducting fluid sustains a planetary magnetic field.", "A field can indicate a conducting layer, energy to drive motion, and sufficient rotation or organization of flow.", "The absence of a present global field does not prove that a body never had a dynamo.", "", "A dynamo converts kinetic energy in a conducting fluid into magnetic energy. Cooling, compositional buoyancy, and rotation can support convection in a metallic core or conducting ocean. Crustal remanent magnetization can preserve evidence of an extinct field, linking present measurements to interior history."),
        ("Heat flow", "Thermal energy crossing a unit area per unit time from a body's interior toward its surface.", "Heat flow constrains radioactive decay, leftover formation energy, differentiation, tidal dissipation, and the ability to sustain geology.", "Surface heat flow may vary spatially and does not identify the heat source by itself.", r"\(q=-k\,dT/dz\)", "Conductive heat flow relates the temperature gradient to thermal conductivity, while convection transports heat by moving material. Small worlds generally cool faster because surface area is large relative to volume, but tidal heating can overturn that trend. Heat flow therefore connects size, age, orbital forcing, and geologic activity."),
    ],
    5: [
        ("Impact crater", "A roughly circular depression excavated when a projectile transfers energy and momentum to a planetary surface.", "Crater size, morphology, ejecta, and abundance record impact conditions, target properties, and surface history.", "Crater diameter is not the projectile diameter, and later erosion or burial can erase the record.", "", "Hypervelocity impacts create shock waves, excavation flow, ejecta blankets, and sometimes central peaks or multi-ring basins. Morphology changes with gravity, target strength, and impact energy. Craters are therefore both process indicators and time markers, provided preservation and detection limits are understood."),
        ("Crater density", "The number of craters above a stated size per unit surface area.", "When impact flux and preservation are comparable, higher crater density generally indicates longer exposure and an older surface.", "It is a relative clock unless calibrated, and resurfacing, saturation, and image resolution can bias counts.", r"\(N(>D)/A\)", "A valid crater-density comparison specifies area, minimum diameter, image resolution, and counting rules. Small craters accumulate quickly but are easily erased; large craters are rarer and probe longer timescales. Absolute ages require a chronology model anchored by radiometric ages, especially lunar samples."),
        ("Resurfacing", "Any process that buries, erodes, deforms, or replaces an older surface and resets part of its visible crater record.", "Volcanism, tectonics, sedimentation, glacial flow, and impacts can create young-looking terrain on an old world.", "Few craters date the exposed surface, not necessarily the planet or underlying rock.", "", "Resurfacing changes the observable clock rather than the age of the whole body. A lava plain can cover ancient crust, while tectonic deformation can make craters difficult to recognize without removing all material. Mapping boundaries and cross-cutting relationships helps distinguish local resurfacing from globally young terrain."),
        ("Stratigraphy", "The ordering of geologic units and events using superposition, cross-cutting, embayment, and other spatial relationships.", "It reconstructs relative history even when absolute ages or samples are unavailable.", "Local stratigraphic order may not transfer globally without correlation evidence.", "", "Planetary stratigraphy treats images and topography as a sequence of events. A flow that embays a crater is younger than that crater; a fault cutting both is younger still. Crater counts can then be applied to mapped units, linking relative order to modeled ages."),
        ("Volcanism", "The transport and eruption of molten or mobilized interior material onto or near a surface.", "Volcanic plains, shields, domes, and gases reveal internal heat, composition, and pathways through the lithosphere.", "Smooth terrain is not automatically volcanic; morphology, spectra, and context must rule out sedimentary or impact deposits.", "", "Volcanism is one mechanism by which interior energy becomes surface evidence. Eruption style depends on composition, volatile content, viscosity, gravity, and pressure. Comparing lunar maria, Venusian plains, Martian volcanoes, and icy cryovolcanic candidates shows that similar shapes can arise from different materials."),
        ("Tectonics", "Deformation of a planetary lithosphere by extension, compression, shear, loading, contraction, or convection.", "Faults, folds, rifts, ridges, and scarps reveal stress and interior evolution.", "Tectonics does not imply Earth-like plate tectonics; most worlds deform without mobile global plates.", "", "Tectonic features preserve the direction and relative timing of stress. Mercury's lobate scarps indicate contraction, while rifts can indicate extension or uplift. The term must be separated from plate tectonics, which is a particular global regime involving creation and recycling of lithosphere."),
    ],
    6: [
        ("Albedo", "The fraction of incident radiation reflected by a planet or atmosphere.", "Bond albedo controls total absorbed sunlight and therefore enters the first-order planetary energy budget.", "A bright planet can still be hot if its atmosphere traps outgoing infrared radiation; albedo alone is not surface temperature.", r"\(F_{\rm abs}=(1-A)S/4\)", "Albedo depends on wavelength, clouds, surface, and viewing geometry. Bond albedo integrates reflected energy over all wavelengths and directions, whereas geometric albedo describes brightness at a particular geometry. In climate reasoning, the absorbed solar flux is only the input side; outgoing infrared and atmospheric opacity determine equilibrium."),
        ("Effective temperature", "The blackbody temperature required to emit the same total thermal power per unit area as a planet emits to space.", "It connects absorbed sunlight to outgoing infrared radiation and provides a baseline for diagnosing greenhouse warming.", "It is not generally the surface temperature because emission to space may originate high in the atmosphere.", r"\(\sigma T_{\rm eff}^4=(1-A)S/4\)", r"Effective temperature follows from global radiative balance under simplified steady-state assumptions. The factor of four averages intercepted sunlight over the whole sphere. Comparing \(T_{\rm eff}\) with measured surface temperature reveals the atmospheric greenhouse effect but does not by itself specify the absorbing gases or vertical structure."),
        ("Greenhouse effect", "Surface and lower-atmosphere warming that occurs when an atmosphere absorbs and re-emits outgoing infrared radiation, raising the altitude from which energy escapes to space.", "It explains why Venus, Earth, and Mars do not follow distance from the Sun alone.", "The effect is not the same as ozone depletion or simply 'trapping heat'; convection, clouds, and spectral absorption also matter.", "", "Greenhouse gases make the atmosphere optically thick in parts of the thermal infrared. Because temperature usually decreases with altitude, emission to space from a higher level is colder; the surface must warm until the whole column again balances absorbed sunlight. Feedbacks involving water vapor, clouds, and albedo can strengthen or weaken the response."),
        ("Atmospheric scale height", r"The height over which pressure or density falls by a factor of \(e\) in an isothermal hydrostatic atmosphere.", "It links temperature, molecular mass, and gravity to atmospheric thickness and to transit or occultation signals.", "Real atmospheres are not perfectly isothermal and may depart from hydrostatic balance during weather or escape.", r"\(H=kT/(mg)\)", r"Scale height follows by balancing the vertical pressure gradient against gravity. Hot, low-molecular-mass gas on a low-gravity world has a large \(H\), making the atmosphere vertically extended. Composition and temperature therefore influence both retention and how an atmosphere appears in remote observations."),
        ("Escape velocity", "The minimum speed needed to coast away from a body's gravity without further propulsion in an ideal two-body model.", "Compared with molecular thermal speeds, it helps assess long-term atmospheric retention.", "It is not a sharp atmospheric-loss threshold; collisions, upper-atmosphere heating, nonthermal processes, and stellar wind matter.", r"\(v_{\rm esc}=\sqrt{2GM/R}\)", "Escape velocity depends on mass and radius, while molecular speed depends on temperature and particle mass. Light atoms in a hot exosphere are most vulnerable to Jeans escape, but impacts, sputtering, photochemistry, and hydrodynamic outflow can dominate under other conditions. Atmospheric survival is therefore an evolutionary problem, not a single comparison."),
        ("Runaway greenhouse", "A climate state in which positive feedback causes increasing surface evaporation and infrared opacity until oceans cannot remain stable at the surface.", "It provides a physical framework for understanding how a wet planet might evolve toward extreme heat.", "It is not simply a strong ordinary greenhouse and should not be inferred from high temperature alone.", "", "In a runaway greenhouse, outgoing longwave radiation approaches a limit while absorbed stellar energy remains larger, so the surface continues warming and volatile reservoirs evaporate. Venus is a central comparative case, but reconstructing its pathway requires atmospheric chemistry, water-loss evidence, and solar-history models. The term must be distinguished from current anthropogenic warming on Earth."),
    ],
    7: [
        ("Regolith", "Loose fragmented material covering coherent rock on an airless or nearly airless body.", "Its grain size, maturity, composition, and thickness record impacts, radiation exposure, and surface mixing.", "Regolith is not ordinary soil: it need not contain biology, water, or chemical weathering products.", "", "Regolith forms as repeated impacts fracture, excavate, melt, and redistribute surface material. Micrometeoroid bombardment and charged particles alter grains over time, producing optical maturation. Samples provide local calibration, while remote spectra and thermal measurements extend interpretation across the Moon, Mercury, and asteroids."),
        ("Impact flux", "The rate at which projectiles of specified sizes strike a target area over time.", "Crater chronology depends on how impact flux changes with epoch and location.", "Flux is not constant through solar-system history and differs among dynamically distinct targets.", "", "Impact flux combines the population of projectiles with encounter probabilities and velocities. The early solar system experienced much higher bombardment than today, and resonances can deliver objects unevenly. Converting crater density to an absolute age therefore requires a chronology model, not merely division by a modern rate."),
        ("Crater ray", "A bright or compositionally distinct streak of ejecta extending outward from a relatively fresh impact crater.", "Rays expose and distribute material that has undergone less space weathering, making them useful relative-youth indicators.", "Brightness can depend on composition and illumination as well as age; rays fade rather than marking an exact date.", "", "Crater rays form when ejecta travel ballistically and land in radial patterns. Freshly excavated grains often have higher optical contrast than mature regolith, so rays become less conspicuous with exposure. Their cross-cutting relationships help establish relative chronology, but calibrated crater counts or samples are needed for numerical ages."),
        ("Space weathering", "Physical and chemical alteration of exposed surface grains by micrometeoroids, solar-wind particles, radiation, and thermal cycling.", "It changes spectral slope, brightness, and absorption bands, complicating remote compositional interpretation.", "Its effects differ among silicate, carbonaceous, metallic, and icy surfaces; lunar behavior is not universal.", "", "Space weathering links exposure time to optical properties without requiring atmosphere or liquid water. On the Moon, nanophase iron and impact-produced glass tend to darken and redden mature soils. Asteroids can respond differently, so laboratory spectra, samples, and local context are needed before translating color into age."),
        ("Synchronous rotation", "A spin state in which a body's rotation period equals its orbital period, keeping nearly the same hemisphere toward its primary.", "Tidal evolution explains why the Moon presents a near side and far side and affects surface illumination histories.", "Synchronous rotation does not mean the body does not rotate; it turns once per orbit.", r"\(P_{\rm spin}=P_{\rm orbit}\)", "Tidal torques dissipate energy and drive spin toward a stable state. The Moon rotates relative to inertial space while orbiting Earth, so the same face remains approximately directed toward Earth. Libration lets observers see slightly more than half the lunar surface over time."),
        ("Volatile", "A substance that vaporizes, sublimates, or migrates readily at the temperatures and pressures of a planetary environment.", "Water and other volatiles can survive in permanently shadowed cold traps even on otherwise airless worlds.", "Volatile is environment-dependent; a compound stable as ice in one location may be gas elsewhere.", "", "Volatile stability is controlled by temperature, pressure, illumination, and binding to minerals or regolith. Mercury and the Moon can retain ice in polar cold traps despite intense sunlight at lower latitudes. Detection requires separating composition from radar, neutron, spectral, or thermal proxies."),
    ],
    8: [
        ("Valley network", "A branching system of channels cut into ancient terrain, often resembling drainage networks produced by surface runoff.", "Geometry and topographic integration make valley networks evidence for past moving liquid, precipitation, or snowmelt on Mars.", "A channel shape alone does not determine duration, discharge, climate, or whether flow was continuous.", "", "Martian valley networks are most common on old terrains and often connect upslope catchments to downslope basins. Their branching patterns are difficult to explain by isolated impacts alone, but groundwater sapping and episodic melting can contribute. Climate models must reproduce not just the presence of channels but their timing, distribution, and required water volumes."),
        ("Delta", "A sedimentary deposit formed where a sediment-bearing flow enters standing water and loses transport capacity.", "Layered, fan-shaped deposits can indicate sustained inflow, a stable basin level, and preserved environments favorable for geologic records.", "Fan shape is not sufficient; stratigraphy, grain transport, and basin geometry must support the interpretation.", "", "A delta records both flowing water and a receiving body such as a lake. Foreset geometry, distributary channels, and mineralogy help distinguish a true delta from an alluvial fan. At Jezero crater, orbital mapping guided rover observations, illustrating how remote and in situ evidence reinforce one another."),
        ("Hydrated mineral", "A mineral whose crystal structure contains water or hydroxyl produced or retained through chemical interaction.", "Clays, sulfates, and related phases can record past water chemistry, temperature, and environmental conditions.", "Hydrated minerals show water–rock interaction, not necessarily a long-lived surface ocean or biological activity.", "", "Hydrated minerals are identified through diagnostic spectral absorptions and confirmed where possible by rover instruments or samples. Different minerals form under different acidity, salinity, and temperature conditions, so mineral assemblages constrain environment more strongly than a generic 'water detected' claim. Later alteration can overprint or redistribute the signal."),
        ("Ground truth", "Detailed local measurement used to test or calibrate interpretations made from orbital or remote data.", "Rover imaging, chemistry, and texture connect kilometer-scale maps to specific rocks and sediments.", "A landing site is geographically limited and may not represent the planet as a whole.", "", "Ground truth does not make orbital observations obsolete; it establishes how remotely sensed units correspond to actual materials. Rover traverses can test spectral mineral identifications and stratigraphic predictions. Site selection favors safe and scientifically promising terrain, so conclusions must preserve the distinction between local confirmation and global prevalence."),
        ("Paleoclimate proxy", "An observable preserved in rock, landform, ice, or chemistry that responds predictably to past environmental conditions.", "Mars climate history relies on proxies because ancient temperature, precipitation, and pressure cannot be measured directly.", "Most proxies are non-unique and require models to translate the preserved signal into climate variables.", "", "Valley geometry, mineral assemblages, sedimentary layers, and isotopic ratios can all act as paleoclimate proxies. Each responds to several variables, so convergence among independent proxies is more persuasive than one indicator. The lecture's evidence hierarchy separates direct present measurements from model-dependent reconstruction of ancient conditions."),
        ("Habitability", "The capacity of an environment to support a specified form of life for a specified interval, given liquid solvent, energy, chemistry, and stability.", "Mars exploration often asks whether past environments were habitable even when no claim of life is made.", "Habitable does not mean inhabited, and Earth-like surface conditions are not the only possible criterion.", "", "Habitability is operational only when the organism, timescale, and environmental requirements are stated. A lake may have had liquid water but still lack usable energy or essential chemistry. Mars missions therefore combine geology, mineralogy, organics, radiation, and environmental history rather than treating one water feature as proof."),
    ],
    9: [
        ("Fluid interior", "An interior that deforms and flows on relevant timescales rather than behaving as a rigid solid surface.", "Giant planets are modeled through pressure, temperature, composition, rotation, gravity, and magnetic fields instead of surface geology.", "Fluid does not mean low density or ordinary liquid; hydrogen can become metallic under extreme pressure.", "", "A giant planet's visible clouds sit above deep molecular and possibly metallic-fluid layers. Pressure and temperature rise continuously, so familiar phase boundaries may be broad. Interior models must reproduce radius, gravity harmonics, heat flow, and atmospheric composition without direct access to a solid surface."),
        ("Differential rotation", "Rotation at different angular rates with latitude or depth.", "Cloud tracking and magnetic measurements reveal zonal winds and help separate atmospheric motion from deeper rotation.", "A cloud feature's period may trace wind rather than the bulk planet, so 'day length' can be model-dependent.", "", "On a fluid world, belts and zones can move eastward or westward relative to the deep interior. Radio or magnetic periodicity often provides a better rotation reference than visible clouds, but even magnetic fields can vary. Differential rotation contributes to jets, storms, and the interpretation of gravity measurements."),
        ("Zonal jet", "A broad east–west atmospheric current organized mainly by latitude.", "Alternating jets create giant-planet belts and zones and redistribute heat and momentum.", "Visible color bands are not identical to wind speed; clouds, chemistry, and altitude also affect appearance.", "", "Rapid rotation favors geostrophic and rotationally constrained flow, producing long-lived zonal jets. Cloud tracking estimates wind relative to a chosen rotation frame. Connecting color to dynamics requires spectroscopy and vertical cloud models because adjacent bands may differ in altitude or chemistry."),
        ("Intrinsic heat", "Thermal energy emitted from a planet in excess of absorbed and reradiated sunlight.", "Excess emission reveals ongoing cooling, contraction, differentiation, or other interior energy sources.", "A planet's total infrared emission includes reprocessed sunlight; the absorbed solar contribution must be subtracted.", r"\(L_{\rm int}=L_{\rm emitted}-L_{\rm absorbed}\)", "Jupiter, Saturn, and Neptune emit substantial intrinsic energy, whereas Uranus has unusually weak excess emission. Possible sources include residual formation heat, slow contraction, and helium separation. Measuring intrinsic heat connects atmospheric weather to interior evolution because upward energy flux can drive convection."),
        ("Magnetosphere", "The region where a planet's magnetic field strongly controls charged-particle motion and interacts with the solar wind.", "Its size, aurorae, radiation belts, and field geometry constrain the internal dynamo and plasma environment.", "A large magnetosphere does not imply a safe environment; trapped radiation can be intense.", "", "Magnetospheres are shaped jointly by internal magnetic fields, solar wind pressure, rotation, and plasma sources such as Io. Field measurements can constrain the conducting region and rotation, while particle observations reveal energy transport. The observed boundary moves with solar-wind conditions, so one crossing is not a fixed planetary radius."),
        ("Gravity harmonics", "Coefficients describing departures of a planet's gravity field from that of a perfect sphere.", "They encode rotational flattening, winds, and radial mass distribution and therefore constrain giant-planet interiors.", "Interpretation is non-unique and depends on rotation rate, equations of state, and atmospheric-flow models.", "", r"Even zonal harmonics such as \(J_2\) and \(J_4\) measure how an oblate, rotating planet's mass departs from spherical symmetry. Precise spacecraft tracking determines these coefficients. Interior models then adjust core mass, composition gradients, and wind depth to match them, illustrating the inverse nature of planetary inference."),
    ],
    10: [
        ("Tidal heating", "Conversion of mechanical energy into internal heat as changing tidal stresses deform a body and dissipate energy.", "It can maintain volcanism or subsurface oceans in moons too small to retain much primordial heat.", "Tides require both forcing and dissipation; a perfectly circular, rigid, synchronous moon would generate little heat.", "", "Tidal heating depends on orbit, primary mass, satellite size, and the material's deformability and lag. Resonances can maintain eccentricity against tidal damping, sustaining repeated flexing. Io and Europa demonstrate how composition and interior structure turn similar orbital forcing into very different geological outcomes."),
        ("Orbital resonance", "A repeated orbital configuration produced by a near ratio of small whole-number periods.", "Moon resonances can maintain eccentricity, focus gravitational forcing, and power long-lived tidal activity.", "A period ratio near an integer is insufficient by itself; the resonant geometry must remain bounded.", r"\(P_2/P_1\approx p/q\)", "The Laplace resonance among Io, Europa, and Ganymede coordinates conjunctions and prevents complete circularization of the inner moons. That maintained eccentricity supplies time-varying tides. Resonance therefore links orbital dynamics from Lecture 03 directly to geology and habitability."),
        ("Subsurface ocean", "A persistent layer of liquid, usually water-rich, beneath an ice shell or crust.", "Magnetic induction, gravity, libration, geology, and plume chemistry can provide independent tests of an ocean.", "Surface fractures or young terrain alone do not prove a global liquid layer.", "", "An ocean is inferred through an evidence chain rather than directly photographed. A time-varying external magnetic field can induce currents in a conductive salty layer, while gravity and libration constrain mechanical decoupling. Geological activity and plume material add context but may also admit localized melt alternatives."),
        ("Induced magnetic field", "A secondary magnetic response produced when a changing external field drives electric currents in a conductor.", "At moons such as Europa, induction is evidence for a globally connected conductive layer consistent with salty liquid water.", "Conductivity and depth are partly degenerate, and plasma effects must be modeled.", "", "As a moon moves through a changing planetary magnetic field, a conductive layer responds according to electromagnetic induction. The amplitude and phase of the response constrain conductivity and geometry. Salty water is a strong candidate, but distinguishing ocean thickness from conductivity requires multiple frequencies or complementary gravity and geology data."),
        ("Ring particle", "An individual ice, rock, or dust fragment orbiting within a planetary ring system.", "Collective collisions, resonances, and shepherding create gaps, waves, sharp edges, and changing structures.", "Rings are not solid disks, and images usually do not resolve typical particles individually.", "", "Ring particles follow Keplerian orbits, so inner material moves faster than outer material. Frequent collisions flatten the system and damp random motion, while moons and resonances organize structure. Brightness measures particle area and optical depth more directly than total mass."),
        ("Roche limit", "The approximate distance within which tides from a primary can prevent a self-gravitating fluid satellite from remaining intact.", "It helps explain why dense rings occupy regions where loose material may not accrete into a large moon.", "The limit depends on density, material strength, shape, and orbit; rigid bodies can survive inside the fluid estimate.", r"\(d_R\approx2.44R_p(\rho_p/\rho_s)^{1/3}\)", "The Roche limit compares a satellite's self-gravity with differential gravity from the planet. It is a useful boundary between accretion-friendly and disruption-friendly regimes, not a universal edge. Small strong objects and transient aggregates complicate the simple fluid-body derivation."),
    ],
    11: [
        ("Asteroid", "A small solid solar-system body whose observed activity is not dominated by volatile sublimation.", "Asteroid orbits, spectra, densities, and samples preserve evidence of accretion, differentiation, collisions, and dynamical transport.", "The asteroid–comet distinction is not absolute; some bodies are dormant, transitional, or active for non-sublimation reasons.", "", "Asteroids include primitive rubble piles, fragments of differentiated parents, binaries, and bodies altered by space weathering. Their present locations need not be formation locations because resonances and planetary migration redistribute them. Sample return connects remote spectral classes to laboratory mineralogy."),
        ("Comet", "A small body containing volatiles that can produce a coma and tails when heated.", "Comet composition and activity probe cold-region materials and volatile delivery, while orbital families record dynamical reservoirs.", "A comet nucleus is not a dirty snowball of uniform composition, and visible tails are not trails left behind in the orbital path.", "", "Solar heating drives sublimation and dust release, creating an atmosphere-like coma around the nucleus. Ion tails respond to the solar wind, while dust tails respond to radiation pressure and orbital motion. Repeated activity alters the surface, so measured gases may sample both primitive inventory and processed layers."),
        ("Meteorite", "A natural extraterrestrial fragment that survives atmospheric passage and reaches the ground.", "Laboratory measurements provide precise ages, isotopes, minerals, and textures unavailable from most remote observations.", "A meteorite is not a meteor, and its parent body or launch location may be uncertain.", "", "Meteorites connect hand-sample chemistry to asteroid and planetary history. Chondrites preserve primitive components, whereas achondrites and iron meteorites record melting and differentiation. Atmospheric filtering, terrestrial weathering, and collection bias mean recovered samples are not a complete census of small bodies."),
        ("Sublimation", "Direct transition from solid to gas under conditions where a stable liquid phase is absent.", "It drives cometary activity and can move volatiles across airless surfaces.", "Observed gas production depends on illumination, thermal inertia, dust mantles, and composition, not only distance from the Sun.", "", "Sublimation consumes latent heat and can excavate or entrain dust from a porous nucleus. Seasonal illumination and rotation localize jets, so activity is spatially and temporally variable. The process links volatile stability from the frost line to modern comet observations."),
        ("Rubble pile", "A gravitational aggregate of fragments with substantial void space and little tensile strength.", "Low density, spin behavior, and impact response affect sampling, deflection, and hazard mitigation.", "A rubble pile is not simply loose surface regolith; it describes much or all of the body's internal structure.", "", "Many small asteroids are assembled from collision fragments rather than being monolithic rock. Their weak cohesion changes crater formation and allows impacts to reshape or spin them. Deflection predictions must therefore include momentum transfer to ejecta and uncertain internal structure."),
        ("Planetary defense", "The coordinated detection, orbit determination, hazard assessment, and possible mitigation of objects that could impact Earth.", "It turns orbital and impact physics into a testable risk-reduction program, as demonstrated by kinetic-impact experiments.", "Deflection is useful only with sufficient warning and accurate tracking; destruction is not the default objective.", r"\(E_k=\tfrac12 mv^2\)", r"Planetary defense begins with surveys and repeated astrometry, because impact probability changes as orbital uncertainty shrinks. A kinetic impactor changes momentum slightly so the miss distance grows over time. Impact energy scales as \(v^2\), but mitigation effectiveness also depends on ejecta, shape, spin, and internal structure."),
    ],
    12: [
        ("Transit", "A temporary decrease in observed stellar brightness when a planet crosses the star's visible disk.", "Transit timing, duration, and depth constrain orbital period, geometry, and planet-to-star radius ratio.", "A brightness dip can have stellar or instrumental causes, and most planetary systems are not aligned to transit.", r"\(\delta\approx(R_p/R_\star)^2\)", "Transit depth is approximately an area ratio when the planet is dark and limb darkening is neglected. Repeated periodic events establish a stronger planetary case, while duration and shape constrain impact parameter and stellar density. Radius inherits uncertainty from the host star, and detection favors large, short-period planets."),
        ("Radial velocity", "The line-of-sight component of a star's motion inferred from Doppler shifts in its spectrum.", "A periodic stellar velocity signal measures the gravitational reflex motion caused by an orbiting companion.", "It yields a minimum mass unless orbital inclination is known and can be confused by stellar activity.", r"\(\Delta\lambda/\lambda\approx v_r/c\)", r"Radial-velocity spectrographs track tiny wavelength shifts relative to stable references. The amplitude grows for massive, close-in planets and depends on stellar mass, eccentricity, and \(\sin i\). Combining radial velocity with transits gives both mass and radius, enabling bulk-density comparison."),
        ("Detection bias", "A systematic preference for discovering planets whose signals are larger, more frequent, or easier to separate from noise.", "It must be modeled before using detected planets to infer the true population or compare architectures with the solar system.", "A catalog distribution is not automatically the underlying occurrence distribution.", "", "Transit surveys favor short-period planets around small stars, while radial-velocity surveys favor massive close companions around quiet stars. Observing baseline, cadence, and pipeline thresholds further shape completeness. Demographic inference requires injection–recovery tests or an equivalent selection model."),
        ("Minimum mass", r"The lower bound \(M_p\sin i\) obtained from radial velocity when orbital inclination \(i\) is unknown.", "It states precisely what the Doppler data constrain before transit, astrometry, or dynamics provide geometry.", "The true mass can be larger, especially for nearly face-on systems.", r"\(M_{\rm min}=M_p\sin i\)", r"Radial velocity measures motion projected along the line of sight, which introduces the inclination factor. For transiting systems \(i\) is near \(90^\circ\), so the minimum mass is close to the true mass. Without geometric information, population analyses account statistically for random orientations."),
        ("Planet occurrence rate", "The average number or fraction of planets in a defined radius, mass, period, and host-star range after correcting for survey completeness.", "Occurrence rates allow a fairer comparison between the solar system and exoplanet populations than raw discovery counts.", "The value depends on bin definitions, stellar sample, detection efficiency, and assumptions about missed planets.", "", "Occurrence is an inference from detections plus nondetections. A survey must estimate how often each type of planet would have been found around each target. Different studies can report different but compatible rates because their parameter ranges and completeness models differ."),
        ("Planetary migration", "A change in orbital size caused by exchange of angular momentum with a gas disk, planetesimal disk, or other planets.", "Migration explains why hot Jupiters and compact systems can contain planets that likely formed elsewhere.", "Migration is a family of mechanisms, not evidence that every planet moved by the same amount or direction.", "", "Disk torques can move growing planets inward or outward, while later gravitational scattering and planetesimal exchange reshape mature systems. Resonant chains may be captured during smooth migration and later disrupted. Exoplanet architectures show that formation models must include dynamical evolution after condensation and accretion."),
    ],
    13: [
        ("Habitable zone", "The range of orbital distances where a specified atmospheric model permits liquid water on a rocky planet's surface.", "It is a useful first filter connecting stellar luminosity, orbit, albedo, and greenhouse physics.", "It does not guarantee water, atmosphere, stability, or life and does not cover subsurface habitats.", "", "Habitable-zone boundaries are model outputs that depend on stellar spectrum, atmospheric composition, clouds, planetary mass, and climate feedbacks. They identify where surface liquid water is physically plausible under stated assumptions. Ocean worlds show why habitability can also exist outside the classical circumstellar zone."),
        ("Habitability", "The ability of an environment to support a specified form of life over a specified timescale.", "It integrates solvent, energy, essential chemistry, environmental stability, and access among those requirements.", "Habitability is not a directly observed substance and must not be equated with evidence of life.", "", "A rigorous habitability claim states what organism or metabolism is imagined and what measurements support each environmental requirement. Conditions can vary with depth and time, so a planet may contain habitable niches without a globally habitable surface. The concept links climate, geology, chemistry, and orbital history."),
        ("Biosignature", "An observable pattern, substance, or structure whose origin may be biological and whose alternatives can be tested.", "It frames life detection as comparison between biological production and abiotic false-positive models.", "No single gas or morphology is universally diagnostic; context and multiple lines of evidence are essential.", "", "A biosignature becomes persuasive when production, persistence, transport, and detection are understood. Atmospheric disequilibrium, organic patterns, textures, or isotopic fractionation can all have nonbiological sources. The evidentiary task is therefore to compare hypotheses rather than label an isolated detection."),
        ("False positive", "A nonbiological process or artifact that produces a signal resembling the proposed evidence for life.", "Photochemistry, geology, contamination, and data processing must be evaluated before assigning biological significance.", "Listing a possible false positive does not automatically invalidate a signal; its plausibility must be quantified.", "", "Abiotic oxygen production, mineral shapes, and terrestrial contamination illustrate different false-positive pathways. Tests should target the environmental conditions required by each alternative. A strong life-detection strategy includes measurements designed in advance to discriminate among them."),
        ("Forward contamination", "Transfer of terrestrial organisms or organic material from a spacecraft to another world.", "Preventing it protects potentially habitable environments and preserves the scientific integrity of life-detection measurements.", "Sterilization can reduce but not always eliminate risk, and requirements depend on mission destination and activity.", "", "Forward contamination is both a scientific and ethical concern. If terrestrial material reaches a sampled environment, a later detection may be ambiguous or the environment may be altered. Planetary-protection categories translate target biology potential and mission type into cleanliness, assembly, and operational controls."),
        ("Backward contamination", "Transfer of potentially hazardous extraterrestrial material to Earth's biosphere during sample return.", "Containment, verification, and controlled analysis protect Earth while allowing high-value laboratory science.", "It is a low-probability risk assessed under uncertainty, not evidence that returned samples are expected to contain life.", "", "Restricted Earth return planning uses sealed containment, chain of custody, independent verification, and staged analysis. The goal is to avoid both environmental release and contamination of the sample by Earth materials. This term connects mission design, biosignature credibility, and risk governance."),
    ],
    14: [
        ("Science traceability matrix", "A structured chain linking a science question to hypotheses, required observables, measurement performance, instruments, and mission operations.", "It reveals whether every payload element produces evidence capable of answering the stated question.", "A filled table is not proof of feasibility; assumptions and performance margins still require testing.", "", "A science traceability matrix turns broad goals into auditable requirements. If the question concerns a subsurface ocean, the matrix must state which measurable signature distinguishes ocean and no-ocean models and what precision is needed. Changes in instrument capability or trajectory should propagate visibly back to science return."),
        ("Payload", "The scientific instruments and supporting measurement hardware carried to meet mission objectives.", "Payload choice determines wavelength, sensitivity, spatial coverage, sampling environment, data rate, and many spacecraft requirements.", "More instruments do not automatically produce better science; mass, power, interference, and operations can reduce total return.", "", "A coherent payload contains complementary measurements rather than an unprioritized wish list. Each instrument should have a traceable role, calibration plan, and data product. Shared pointing, thermal, electromagnetic, or contamination constraints often make payload integration as important as individual instrument performance."),
        ("Trajectory", "The time-dependent path and velocity of a spacecraft under gravity, propulsion, and operational constraints.", "Trajectory determines arrival energy, flyby geometry, illumination, communication distance, coverage, and radiation exposure.", "The shortest path is rarely the lowest-energy or highest-science option.", "", "Mission trajectories may use launch energy, gravity assists, orbit insertion, aerobraking, or repeated flybys. Geometry determines what can be measured and when, so trajectory and payload are designed together. Uncertainty in navigation and target environment requires correction capability and margins."),
        ("Measurement requirement", "A quantitative statement of the accuracy, precision, resolution, range, cadence, or coverage needed to discriminate among science hypotheses.", "It translates scientific meaning into engineering performance that can be tested before launch.", "A requirement without a linked hypothesis or error budget can become arbitrary overdesign.", "", "Measurement requirements should follow from simulated or analytic discrimination between competing models. For imaging, pixel scale alone is insufficient; signal-to-noise, contrast, pointing stability, and illumination also matter. Verification plans demonstrate that the delivered system meets the required performance."),
        ("Uncertainty budget", "An accounting of independent and correlated sources of error that limit a derived result.", "It identifies which calibration, instrument, environmental, sampling, or model uncertainty most threatens the science conclusion.", "Adding errors linearly or quoting precision without systematic effects can seriously misstate confidence.", r"\(\sigma_y^2\approx\sum_i(\partial y/\partial x_i)^2\sigma_i^2\)", "An uncertainty budget begins with the quantity the mission must infer and propagates measurement errors through the model. Random noise may average down, while calibration bias or model degeneracy may not. The budget guides design effort toward the uncertainty that controls the final decision."),
        ("Mission architecture", "The coordinated choice of spacecraft elements, encounters, communications, operations, and data flow used to execute a mission.", "Flyby, orbiter, lander, rover, sample return, and multi-spacecraft designs offer different coverage, risk, duration, and evidence strength.", "Architecture is broader than trajectory and cannot be optimized on a single metric such as cost or resolution.", "", "Mission architecture connects scientific cadence to engineering reality. An orbiter offers repeated global context, a lander offers local in situ measurements, and sample return offers unmatched laboratory precision at high cost and complexity. Trade studies compare these options against traceable science value and risk."),
    ],
}


TERM_CSS = """
.term-explorer{display:grid;grid-template-columns:minmax(220px,.7fr) minmax(0,1.8fr);gap:28px;align-items:stretch;min-height:58vh}
.term-list{display:flex;flex-direction:column;gap:10px}
.term-button{width:100%;padding:12px 15px;border:2px solid var(--line);border-radius:8px;background:#fff;color:var(--navy);font:inherit;font-size:1.05rem;font-weight:700;text-align:left;cursor:pointer}
.term-button:hover{border-color:var(--teal)}
.term-button:focus-visible{outline:4px solid var(--gold);outline-offset:2px}
.term-button[aria-selected="true"]{color:#fff;background:var(--teal);border-color:var(--teal)}
.term-detail{border:1px solid var(--line);border-radius:10px;padding:20px 24px;background:var(--paper);overflow:auto}
.term-detail h3{margin:0 0 10px;color:var(--teal);font-size:clamp(1.35rem,2.2vw,2rem)}
.term-detail p{font-size:clamp(.96rem,1.35vw,1.22rem);margin:.55em 0}
.term-detail[hidden]{display:none}
.term-visual{font-size:1.12rem;padding:10px 14px;background:var(--teal-soft);border-left:4px solid var(--teal);margin-top:12px}
@media(max-width:800px){.term-explorer{grid-template-columns:1fr}.term-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))}}
"""

TERM_PRINT_CSS = """
@media print{.term-explorer{display:block;min-height:0}.term-list{display:none}.term-detail[hidden]{display:block}.term-detail{break-inside:avoid;margin:12px 0}}
"""

TERM_SCRIPT = """
<script data-astr120-term-explorer>
document.querySelectorAll("[data-term-explorer]").forEach((explorer)=>{
  const tabs=[...explorer.querySelectorAll('[role="tab"]')];
  const panels=[...explorer.querySelectorAll('[role="tabpanel"]')];
  const select=(tab,moveFocus=false)=>{
    tabs.forEach((item)=>{
      const active=item===tab;
      item.setAttribute("aria-selected",String(active));
      item.tabIndex=active?0:-1;
    });
    panels.forEach((panel)=>{panel.hidden=panel.id!==tab.getAttribute("aria-controls");});
    if(moveFocus)tab.focus();
  };
  tabs.forEach((tab,index)=>{
    tab.addEventListener("click",()=>select(tab));
    tab.addEventListener("keydown",(event)=>{
      if(!["ArrowDown","ArrowUp","ArrowRight","ArrowLeft","Home","End"].includes(event.key))return;
      event.preventDefault();
      let next=index;
      if(event.key==="Home")next=0;
      else if(event.key==="End")next=tabs.length-1;
      else next=(index+(["ArrowDown","ArrowRight"].includes(event.key)?1:-1)+tabs.length)%tabs.length;
      select(tabs[next],true);
    });
  });
});
</script>
"""


def term_slide(n: int) -> str:
    buttons = []
    panels = []
    for i, (term, definition, relation, limitation, equation, _notes) in enumerate(TERMS[n], 1):
        tab_id = f"l{n:02d}-term-{i}-tab"
        panel_id = f"l{n:02d}-term-{i}-panel"
        selected = i == 1
        buttons.append(
            f'<button class="term-button" id="{tab_id}" type="button" role="tab" '
            f'aria-selected="{str(selected).lower()}" aria-controls="{panel_id}" '
            f'data-term-target="{panel_id}" tabindex="{0 if selected else -1}">{escape(term)}</button>'
        )
        equation_html = f'<div class="term-visual">{equation}</div>' if equation else ""
        panels.append(
            f'<article class="term-detail" id="{panel_id}" role="tabpanel" aria-labelledby="{tab_id}"'
            f'{" hidden" if not selected else ""}><h3>{escape(term)}</h3>'
            f'<p><strong>Definition:</strong> {escape(definition)}</p>'
            f'<p><strong>Why it matters and connects:</strong> {escape(relation)}</p>'
            f'<p><strong>Boundary or common confusion:</strong> {escape(limitation)}</p>{equation_html}</article>'
        )
    return (
        f'<section class="slide glossary-slide" aria-labelledby="l{n:02d}-terms-heading">'
        f'<h2 id="l{n:02d}-terms-heading">Terms for This Lecture</h2>'
        f'<div class="term-explorer" data-term-explorer>'
        f'<div class="term-list" role="tablist" aria-label="Lecture {n:02d} terms">'
        + "".join(buttons)
        + '</div><div class="term-details">'
        + "".join(panels)
        + "</div></div></section>"
    )


def notes_section(n: int) -> str:
    items = []
    for term, _definition, _relation, _limitation, _equation, notes in TERMS[n]:
        items.append(f"<dt><strong>{escape(term)}</strong></dt><dd>{escape(notes)}</dd>")
    return (
        "<section><h2>Terms Developed in Context</h2>"
        "<p>These terms form the lecture's reasoning vocabulary. Each definition below extends the slide explorer by "
        "showing how the term is measured or modeled, how it connects to neighboring ideas, and where its use can fail.</p>"
        f"<dl>{''.join(items)}</dl></section>"
    )


def replace_or_insert_slide(text: str, n: int) -> str:
    existing = re.compile(
        r'<section class=["\']slide glossary-slide["\'][\s\S]*?</section>', re.I
    )
    text, count = existing.subn(lambda _match: term_slide(n), text, count=1)
    if not count:
        objective = re.compile(
            r'(<section class=["\']slide["\']><h2>Learning (?:Goals|Objectives)</h2>[\s\S]*?</section>)',
            re.I,
        )
        text, count = objective.subn(lambda match: match.group(1) + term_slide(n), text, count=1)
        if not count:
            raise RuntimeError(f"Lecture {n:02d}: no learning-objectives insertion point")

    if ".term-explorer{" not in text:
        text = text.replace("</style>", TERM_CSS + TERM_PRINT_CSS + "</style>", 1)
    if "data-astr120-term-explorer" not in text:
        text = text.replace("</body>", TERM_SCRIPT + "</body>", 1)
    return text


def replace_notes_terms(text: str, n: int) -> str:
    pattern = re.compile(
        r"<section><h2>(?:Terminology Support|Terms Developed in Context)</h2>[\s\S]*?</section>",
        re.I,
    )
    text, count = pattern.subn(lambda _match: notes_section(n), text, count=1)
    if not count:
        connection = re.compile(
            r"(<section><h2>Connection to the Course</h2>[\s\S]*?</section>)", re.I
        )
        text, count = connection.subn(lambda match: match.group(1) + notes_section(n), text, count=1)
        if not count:
            raise RuntimeError(f"Lecture {n:02d}: no notes insertion point")
    return text


def upgrade() -> None:
    for n in range(1, 15):
        slide_path = LECTURES / f"lecture-{n:02d}-slides.html"
        notes_path = LECTURES / f"lecture-{n:02d}-notes.html"
        slide_path.write_text(
            replace_or_insert_slide(slide_path.read_text(encoding="utf-8"), n),
            encoding="utf-8",
            newline="\n",
        )
        notes_path.write_text(
            replace_notes_terms(notes_path.read_text(encoding="utf-8"), n),
            encoding="utf-8",
            newline="\n",
        )
    print("Updated 14 ASTR120 slide/notes terminology pairs.")


def validate() -> None:
    from html.parser import HTMLParser

    class Parser(HTMLParser):
        def error(self, message: str) -> None:  # pragma: no cover
            raise RuntimeError(message)

    failures: list[str] = []
    for n in range(1, 15):
        slide = (LECTURES / f"lecture-{n:02d}-slides.html").read_text(encoding="utf-8")
        notes = (LECTURES / f"lecture-{n:02d}-notes.html").read_text(encoding="utf-8")
        Parser().feed(slide)
        Parser().feed(notes)
        tabs = re.findall(r'<button class="term-button"[^>]+>', slide)
        panels = re.findall(r'<article class="term-detail"[^>]+>', slide)
        ids = re.findall(r'\bid="([^"]+)"', slide)
        controls = [re.search(r'aria-controls="([^"]+)"', tab).group(1) for tab in tabs]
        panel_ids = [re.search(r'\bid="([^"]+)"', panel).group(1) for panel in panels]
        labels = [re.search(r'aria-labelledby="([^"]+)"', panel).group(1) for panel in panels]
        tab_ids = [re.search(r'\bid="([^"]+)"', tab).group(1) for tab in tabs]
        if len(tabs) != len(TERMS[n]) or len(panels) != len(tabs):
            failures.append(f"{n:02d}: expected {len(TERMS[n])} tabs/panels, got {len(tabs)}/{len(panels)}")
        if len(ids) != len(set(ids)):
            failures.append(f"{n:02d}: duplicate slide IDs")
        if controls != panel_ids or labels != tab_ids:
            failures.append(f"{n:02d}: tab/panel ARIA mapping mismatch")
        if not tabs or 'aria-selected="true"' not in tabs[0] or "hidden" in panels[0]:
            failures.append(f"{n:02d}: first panel state is not readable without JavaScript")
        if any('aria-selected="false"' not in tab for tab in tabs[1:]) or any(" hidden" not in panel for panel in panels[1:]):
            failures.append(f"{n:02d}: inactive state mismatch")
        if ".term-detail[hidden]{display:block}" not in slide.replace(" ", ""):
            failures.append(f"{n:02d}: print fallback missing")
        if 'data-astr120-term-explorer' not in slide or ':focus-visible' not in slide:
            failures.append(f"{n:02d}: keyboard script or visible focus missing")
        if "Terms Developed in Context" not in notes:
            failures.append(f"{n:02d}: notes section missing")
        for term, *_ in TERMS[n]:
            if f"<dt><strong>{escape(term)}</strong></dt>" not in notes:
                failures.append(f"{n:02d}: notes missing exact term {term!r}")
    if failures:
        raise SystemExit("\n".join(failures))
    print("Validated 14 pairs, 84 terms, 84 tabs, 84 panels, and exact notes coverage.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--validate-only", action="store_true")
    args = parser.parse_args()
    if not args.validate_only:
        upgrade()
    validate()
