"""Accessible lecture-term explorers for the ASTR 474 generators."""
from __future__ import annotations

import html


TERM_EXPLORER_CSS = """
.glossary-slide{justify-content:flex-start}.term-explorer{display:grid;grid-template-columns:minmax(220px,.7fr) minmax(0,1.8fr);gap:28px;align-items:stretch;min-height:58vh}.term-list{display:flex;flex-direction:column;gap:10px}.term-button{width:100%;padding:12px 14px;border:2px solid var(--line);border-radius:8px;background:#fff;color:var(--navy);font:700 1rem/1.25 'Aptos','Segoe UI',sans-serif;text-align:left;cursor:pointer}.term-button:hover{border-color:var(--teal)}.term-button:focus-visible{outline:4px solid var(--gold);outline-offset:2px}.term-button[aria-selected="true"]{color:#fff;background:var(--teal);border-color:var(--teal)}.term-details{min-width:0}.term-detail{border:1px solid var(--line);border-radius:10px;padding:18px 22px;background:var(--paper);overflow:auto}.term-detail h3{margin:0 0 10px;color:var(--teal);font:700 1.45rem/1.2 'Aptos','Segoe UI',sans-serif}.term-detail p{font-size:1rem;margin:9px 0}.term-detail[hidden]{display:none}.term-visual{margin-top:14px}@media(max-width:800px){.term-explorer{grid-template-columns:1fr}.term-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:520px){.term-list{grid-template-columns:1fr}}@media print{.term-explorer{display:block}.term-list{display:none}.term-detail[hidden]{display:block!important}.term-detail{break-inside:avoid;margin:12px 0}}
"""

TERM_EXPLORER_SCRIPT = """
<script>document.querySelectorAll("[data-term-explorer]").forEach((explorer)=>{const tabs=[...explorer.querySelectorAll('[role="tab"]')];const panels=[...explorer.querySelectorAll('[role="tabpanel"]')];const select=(tab)=>{tabs.forEach((item)=>item.setAttribute("aria-selected",String(item===tab)));panels.forEach((panel)=>{panel.hidden=panel.id!==tab.dataset.termTarget;});};tabs.forEach((tab,index)=>{tab.addEventListener("click",()=>select(tab));tab.addEventListener("keydown",(event)=>{if(!["ArrowDown","ArrowUp","ArrowRight","ArrowLeft","Home","End"].includes(event.key))return;event.preventDefault();const forward=event.key==="ArrowDown"||event.key==="ArrowRight";const nextIndex=event.key==="Home"?0:event.key==="End"?tabs.length-1:(index+(forward?1:-1)+tabs.length)%tabs.length;tabs[nextIndex].focus();select(tabs[nextIndex]);});});});</script>
"""

TERM_SETS = {
    1: [("Floating-point number", "A finite binary representation of a real number with bounded precision and exponent range."), ("Machine epsilon", "The scale of the spacing between one and the next larger representable number."), ("Roundoff error", "The discrepancy introduced when an exact arithmetic result is rounded to the available representation."), ("Cancellation", "Loss of significant information when nearly equal finite-precision quantities are subtracted."), ("Conditioning", "Sensitivity of the exact problem solution to small perturbations in its inputs.")],
    2: [("Initial-value problem", "A differential equation paired with a state specified at a starting time."), ("Local truncation error", "The one-step defect made by a numerical integrator assuming the incoming state is exact."), ("Global error", "The accumulated difference between the numerical and exact trajectories at a later time."), ("Adaptive timestep", "A step size changed by an error estimator to meet relative and absolute tolerance targets."), ("Stiffness", "A separation of dynamical timescales that makes explicit integration inefficient or unstable.")],
    3: [("Symplectic integrator", "A time-stepping map that preserves Hamiltonian phase-space geometry."), ("Kepler drift", "Exact or specialized propagation under the dominant two-body Hamiltonian during a split step."), ("Kick step", "Momentum update produced by the perturbing interaction part of a split Hamiltonian."), ("Timestep convergence", "Evidence obtained by comparing results from systematically refined step sizes."), ("Ephemeris", "A time-tagged prediction of an object's position and velocity in a specified frame and dynamical model.")],
    4: [("N-body system", "A set of mutually gravitating particles whose accelerations depend on every other particle."), ("Invariant", "A quantity such as total energy or angular momentum that the continuous model conserves."), ("Close encounter", "A near approach that creates a short dynamical timescale and strong acceleration."), ("Center-of-mass frame", "Coordinates measured relative to the system barycenter and its bulk motion."), ("Chaos", "Exponential sensitivity of trajectories to small differences in initial conditions.")],
    5: [("Conserved variable", "A density whose volume integral changes only through boundary fluxes or source terms."), ("Flux", "The rate at which a conserved quantity crosses a unit area."), ("Finite-volume method", "A discretization that updates cell averages from numerical fluxes at cell interfaces."), ("Riemann problem", "An initial discontinuity separating two constant states, used to determine interface waves and flux."), ("Shock", "A discontinuous compressive wave satisfying conservation laws and an entropy condition.")],
    6: [("Cell average", "The volume-averaged state represented by one finite-volume zone."), ("Numerical flux", "An interface estimate of transported conserved quantities used in the discrete update."), ("CFL condition", "A timestep restriction tying numerical propagation to the fastest resolved signal speed."), ("Numerical diffusion", "Artificial smoothing introduced by a discretization, especially near discontinuities."), ("Resolution study", "A controlled comparison across grid spacings used to test convergence and estimate discretization error.")],
    7: [("Specific intensity", "Radiative energy transported per projected area, time, solid angle, and frequency."), ("Optical depth", "A dimensionless path integral of opacity that measures attenuation strength."), ("Source function", "The ratio of emissivity to opacity, setting the intensity approached in an optically thick medium."), ("Formal solution", "The analytic integral solution of the transfer equation for specified source function and boundary intensity."), ("Boundary intensity", "Radiation entering the modeled ray at the starting surface.")],
    8: [("Optically thin approximation", "A small-optical-depth expansion that keeps only the leading contribution to emission or attenuation."), ("Taylor remainder", "The neglected higher-order terms that bound an approximation's error."), ("Relative error", "The difference from a reference divided by a declared reference magnitude."), ("Validity domain", "The range of inputs over which an approximation satisfies a stated accuracy criterion."), ("Reference solution", "A more accurate analytic or numerical result used for comparison, not automatically an exact truth.")],
    9: [("Monte Carlo estimator", "A sample-derived statistic used to approximate an expectation or probability."), ("Random seed", "An input that initializes a pseudorandom number generator and supports repeatable streams."), ("Bernoulli trial", "A two-outcome random experiment represented by zero or one."), ("Standard error", "The sampling standard deviation of an estimator across repeated independent datasets."), ("Convergence rate", "The scaling of estimator uncertainty with sample size, here typically proportional to N to the minus one-half.")],
    10: [("Rare event", "An outcome with small target probability that is difficult to estimate by ordinary sampling."), ("Importance sampling", "Sampling from a proposal distribution and weighting outcomes to recover a target expectation."), ("Proposal distribution", "The alternative probability law from which simulated samples are drawn."), ("Likelihood ratio", "The target-density to proposal-density weight applied to each sampled outcome."), ("Effective sample size", "A diagnostic of how weight concentration reduces the information content of weighted samples.")],
    11: [("Likelihood", "A probability model for observed data viewed as a function of model parameters."), ("Residual", "The observed value minus its model prediction under a stated sign convention."), ("Weighted least squares", "Parameter estimation that scales residuals by their uncertainties or covariance."), ("Identifiability", "The degree to which distinct parameter values produce distinguishable predictions."), ("Jacobian", "The matrix of model derivatives with respect to parameters used in optimization and local uncertainty estimates.")],
    12: [("Prior", "A probability distribution encoding parameter support and assumptions before conditioning on current data."), ("Posterior", "The parameter distribution obtained by combining likelihood and prior through Bayes' rule."), ("Conjugate model", "A likelihood-prior pairing whose posterior remains in the same distribution family."), ("Credible interval", "A posterior probability interval conditional on the adopted model and prior."), ("Posterior predictive check", "A comparison of replicated data drawn from the fitted model with observed diagnostic structure.")],
    13: [("Reproducibility", "The ability to regenerate a result from recorded code, data, parameters, environment, and random state."), ("Provenance", "The documented origin and transformation history of every input and derived artifact."), ("Dependency pinning", "Recording exact software versions needed to recreate an execution environment."), ("Checksum", "A content digest used to detect whether a file has changed."), ("Regression test", "An automated check that protects a previously established scientific or software behavior.")],
    14: [("Validation dossier", "A compact record of analytic checks, convergence evidence, uncertainty, provenance, and limitations supporting a result."), ("Discretization error", "Error caused by representing continuous equations on finite timesteps, grids, or basis sets."), ("Sampling error", "Random variation caused by estimating a quantity from a finite stochastic sample."), ("Parameter uncertainty", "Uncertainty propagated from incompletely known model inputs or fitted parameters."), ("Model discrepancy", "Systematic difference between the adopted mathematical model and the physical system it approximates.")],
}


def _terms(number: int) -> list[tuple[str, str]]:
    terms = TERM_SETS[number]
    if not 5 <= len(terms) <= 8:
        raise ValueError(f"Lecture {number:02d} requires 5-8 terms")
    return terms


def slide_section(number: int, title: str, question: str, equation: str, concept: str, limitation: str) -> str:
    terms = _terms(number)
    buttons, panels = [], []
    for index, (name, definition) in enumerate(terms, 1):
        tab_id, panel_id = f"term-{number:02d}-{index}-tab", f"term-{number:02d}-{index}-panel"
        selected, hidden = ("true", "") if index == 1 else ("false", " hidden")
        neighbor = terms[index % len(terms)][0]
        buttons.append(f'<button class="term-button" id="{tab_id}" type="button" role="tab" aria-selected="{selected}" aria-controls="{panel_id}" data-term-target="{panel_id}">{html.escape(name)}</button>')
        panels.append(f'<article class="term-detail" id="{panel_id}" role="tabpanel" aria-labelledby="{tab_id}"{hidden}><h3>{html.escape(name)}</h3><p><strong>Definition:</strong> {html.escape(definition)}</p><p><strong>Why it matters here:</strong> It helps answer {html.escape(question)} within the numerical model described here.</p><p><strong>Relationships:</strong> Connect it to <em>{html.escape(neighbor)}</em>, the governing expression <span class="equation-inline">\\({equation}\\)</span>, and the computed diagnostic developed later in the lecture.</p><p><strong>Boundary or common confusion:</strong> {html.escape(limitation)}</p></article>')
    return f'<section class="slide glossary-slide" aria-labelledby="terms-{number:02d}-heading"><p class="kicker">Core language</p><h2 id="terms-{number:02d}-heading">Terms for This Lecture</h2><div class="term-explorer" data-term-explorer><div class="term-list" role="tablist" aria-label="Lecture terms">{"".join(buttons)}</div><div class="term-details">{"".join(panels)}</div></div></section>'


def notes_section(number: int, title: str, question: str, equation: str, concept: str, limitation: str) -> str:
    terms = _terms(number)
    entries = []
    for index, (name, definition) in enumerate(terms):
        neighbor = terms[(index + 1) % len(terms)][0]
        entries.append(f'<dt><strong>{html.escape(name)}</strong></dt><dd><p>{html.escape(definition)} In this lecture it is used to address {html.escape(question)}</p><p><strong>Model connection:</strong> Read the term against <em>{html.escape(neighbor)}</em> and the governing relation <span class="equation-inline">\\({equation}\\)</span>. The relevant computational evidence is a controlled output, residual, invariant, or refinement sequence rather than visual smoothness alone.</p><p><strong>Interpretive limit:</strong> {html.escape(limitation)} This distinction separates numerical behavior from physical accuracy and model adequacy.</p></dd>')
    return f'<section><h2>Terms Developed in Context</h2><p>The terms below connect the mathematical model, implementation choices, computed diagnostics, and limits of the scientific claim.</p><dl>{"".join(entries)}</dl></section>'
