from __future__ import annotations

import csv
import json
import math
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LECTURES = ROOT / "lectures"
LABS = ROOT / "labs"
PSETS = ROOT / "problem-sets"
DATA = ROOT / "data"
SRC = ROOT / "src"
ASSETS = ROOT / "assets" / "images"
TODAY = "2026-09-24"

COURSE = {
    "courseNumber": "ASTR 210",
    "courseCode": "ASTR210",
    "title": "Observational Astronomy and Data Reduction",
    "credits": 4,
    "term": "Fall",
    "prerequisites": "ASTR 101; MATH 151; COMP 110",
    "description": "Builds practical observing skills in photometry, spectroscopy, astrometry, image calibration, signal-to-noise estimation, and uncertainty reporting. Students reduce CCD data, analyze public survey archives, and prepare a technical observing report.",
}

CSS = """
:root{--ink:#17202a;--muted:#5b6773;--paper:#fbfcfd;--panel:#fff;--line:#d9e0e7;--navy:#102a43;--teal:#0f6b78;--teal-soft:#e5f4f6;--gold:#b87911;--warning:#8a4b08}*{box-sizing:border-box}body{margin:0;font-family:Georgia,"Times New Roman",serif;color:var(--ink);background:var(--paper);line-height:1.6}header{padding:38px 24px 26px;background:linear-gradient(135deg,var(--navy),var(--teal));color:#fff}header div,main{max-width:1080px;margin:0 auto}main{padding:30px 24px 64px}h1,h2,h3{line-height:1.15}h1{margin:0 0 8px;font-size:clamp(2rem,4vw,3.2rem)}h2{margin-top:34px;color:var(--navy);border-bottom:2px solid var(--line);padding-bottom:8px}h3{color:var(--teal)}section,article.problem{background:var(--panel);border:1px solid var(--line);border-radius:6px;padding:16px 18px;margin:16px 0}.notice{border-left:5px solid var(--teal);background:var(--teal-soft)}table{width:100%;border-collapse:collapse;margin:14px 0}th,td{border:1px solid var(--line);padding:8px 10px;vertical-align:top;text-align:left}th{background:var(--teal-soft)}code{background:#eef3f5;padding:1px 4px;border-radius:3px}.points{color:var(--gold);font-weight:700}a{color:var(--teal);font-weight:700}
"""
SLIDE_CSS = """
:root{--ink:#17202a;--muted:#5b6773;--paper:#fbfcfd;--panel:#fff;--line:#d9e0e7;--navy:#102a43;--teal:#0f6b78;--teal-soft:#e5f4f6;--gold:#b87911;--warning:#8a4b08}*{box-sizing:border-box}body{margin:0;font-family:"Aptos","Segoe UI",sans-serif;color:var(--ink);background:var(--paper)}.deck{scroll-snap-type:y mandatory;height:100vh;overflow-y:auto}.slide{min-height:100vh;scroll-snap-align:start;display:flex;flex-direction:column;justify-content:center;padding:50px 68px;border-bottom:1px solid var(--line);background:var(--panel)}.title{background:linear-gradient(135deg,var(--navy),var(--teal));color:#fff}h1{font-size:clamp(2.4rem,5vw,4.5rem);margin:0 0 18px;line-height:1.05}h2{font-size:clamp(1.8rem,3.2vw,3.1rem);margin:0 0 22px;color:var(--navy)}.title h2{color:#fff;opacity:.94}p,li{font-size:clamp(1.03rem,1.55vw,1.45rem);line-height:1.35}.kicker{color:var(--gold);text-transform:uppercase;letter-spacing:.08em;font-weight:700}.grid{display:grid;grid-template-columns:.78fr 1.22fr;gap:30px;align-items:center}.three{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.card{border:1px solid var(--line);background:#fff;border-radius:6px;padding:14px 16px}.equation{font-size:1.32rem;padding:14px 18px;background:var(--teal-soft);border-left:5px solid var(--teal);margin:12px 0}figcaption,.small{color:var(--muted);font-size:.95rem;line-height:1.35;margin-top:8px}svg,img{width:100%;max-height:72vh;object-fit:contain;border:1px solid var(--line);background:#fff}.warning{border-left:5px solid var(--warning);background:#fff8e8;padding:14px 18px}@media print{.deck{height:auto;overflow:visible}.slide{min-height:7.5in;page-break-after:always}}
"""

LECTURES = [
    dict(n=1,title="From Pretty Pictures to Measurements",history="Observational astronomy matured when photographic plates, photoelectric photometers, CCDs, and survey archives turned telescopes into quantitative instruments.",phenomenon="Every image is a measurement shaped by photons, optics, detector response, atmosphere, calibration, and analysis choices.",concepts=["counts", "calibration", "metadata"],equation="measured image = sky + source + detector effects + noise",example="A galaxy image cannot be interpreted until bias, dark current, flat field, sky background, and exposure time are understood.",synthesis="A useful observation is reproducible, calibrated, and accompanied by uncertainty."),
    dict(n=2,title="Observing Planning and Error Budgets",history="Professional observing proposals succeed by converting a science question into target visibility, exposure time, calibration, and risk management.",phenomenon="A technically possible observation can still fail if the target is too low, too faint, saturated, or missing calibration frames.",concepts=["airmass", "exposure time", "calibration plan"],equation="airmass ≈ sec z",example="A target at altitude 30 degrees has airmass about 2, increasing extinction and seeing effects relative to zenith.",synthesis="Planning is the first stage of data reduction."),
    dict(n=3,title="CCD Detectors, Bias, Dark, and Flat Fields",history="CCDs replaced photographic plates because their response is more linear and calibratable, but only after detector artifacts are removed.",phenomenon="Raw CCD images contain electronic offsets, thermal signal, pixel sensitivity differences, cosmic rays, and real photons.",concepts=["bias", "dark current", "flat field"],equation="calibrated = (raw - bias - dark) / flat",example="If a pixel has raw 1430 counts, bias 1000, dark 30, and normalized flat 0.80, the calibrated value is 500 counts.",synthesis="Calibration turns a detector readout into a defensible measurement."),
    dict(n=4,title="Noise, Signal-to-Noise, and Detection Limits",history="Astronomers learned that deeper images are not just longer exposures; noise sources determine what can be detected confidently.",phenomenon="A faint source can be invisible in one image and significant in another because signal-to-noise changes.",concepts=["Poisson noise", "read noise", "sky background"],equation="SNR = S / sqrt(S + n_pix(B + D + R^2))",example="A source with 900 counts over sky noise of 400 counts has much different reliability than the same source on a bright sky.",synthesis="Detection is a probability statement, not simply seeing a spot."),
    dict(n=5,title="Aperture Photometry",history="Photometry became powerful when astronomers tied instrumental counts to standard stars and repeatable apertures.",phenomenon="Aperture choice, sky annulus, and calibration determine whether brightness measurements are biased or precise.",concepts=["aperture", "sky annulus", "zero point"],equation="m = -2.5 log10(F) + ZP",example="Two stars with flux ratio 100 differ by 5 magnitudes.",synthesis="Photometry is measurement design: source aperture plus background model plus calibration."),
    dict(n=6,title="Differential Photometry and Light Curves",history="Variable star and exoplanet work often depends on comparing a target with stable comparison stars in the same images.",phenomenon="Clouds or transparency changes can affect all stars, but differential photometry can preserve relative variability.",concepts=["comparison star", "light curve", "differential magnitude"],equation="Delta m = -2.5 log10(F_target / F_comp)",example="A 1 percent transit corresponds to about 0.011 magnitudes of dimming.",synthesis="Differential measurements can remove shared systematics while revealing real variation."),
    dict(n=7,title="Astrometry and Plate Solutions",history="Astrometry links images to the sky; from asteroid tracking to Gaia, position measurement is a foundation of celestial dynamics.",phenomenon="Pixels become RA/Dec only after the image is matched to a reference catalog and distortion model.",concepts=["centroid", "WCS", "residual"],equation="position = plate model(pixel coordinates)",example="A 0.4 pixel centroid error with 1.2 arcsec/pixel scale gives 0.48 arcsec positional uncertainty before catalog errors.",synthesis="Astrometry is geometry plus calibration plus residual analysis."),
    dict(n=8,title="Spectroscopy and Wavelength Calibration",history="Fraunhofer lines, laboratory spectra, and modern spectrographs let astronomers measure composition and motion remotely.",phenomenon="A spectrum is not physical until pixel position is mapped to wavelength and calibrated for response.",concepts=["dispersion", "arc lamp", "resolution"],equation="R = lambda / Delta lambda",example="At R=2000, a spectrograph near 600 nm resolves about 0.3 nm.",synthesis="Spectroscopy transforms images into physics only after wavelength and flux calibration."),
    dict(n=9,title="Radial Velocity and Redshift",history="Slipher's galaxy redshifts and modern exoplanet velocities show that wavelength shifts can reveal motion across cosmic and planetary scales.",phenomenon="Line shifts measure motion along the line of sight, but line identification and calibration come first.",concepts=["rest wavelength", "redshift", "radial velocity"],equation="v/c ≈ Delta lambda / lambda0",example="H-alpha shifted from 656.3 to 657.0 nm implies about 320 km/s recession.",synthesis="Velocity is inferred from calibrated wavelength shifts, not from image appearance."),
    dict(n=10,title="Survey Archives and Reproducible Queries",history="Modern astronomy is survey-rich: SDSS, Gaia, Pan-STARRS, ZTF, TESS, and archives make reproducibility a data-management problem.",phenomenon="A result from an archive depends on query criteria, filters, flags, version, and selection effects.",concepts=["catalog", "selection function", "query reproducibility"],equation="sample = catalog rows satisfying documented cuts",example="A color-selected star sample changes if saturated sources or high-uncertainty parallaxes are not filtered.",synthesis="Archive science requires recording the query as carefully as the conclusion."),
    dict(n=11,title="Image Stacking, Registration, and Cosmic Rays",history="Deep imaging and time-domain surveys rely on combining images while rejecting defects and preserving alignment.",phenomenon="Stacking increases signal-to-noise, but only if images are registered and outliers are handled correctly.",concepts=["registration", "median combine", "cosmic ray rejection"],equation="SNR improves roughly as sqrt(N) for independent equal exposures",example="Combining 9 equal exposures can improve SNR by about a factor of 3 if noise is independent.",synthesis="Stacking is statistical inference on pixels."),
    dict(n=12,title="Time-Domain Observing",history="Supernovae, variable stars, occultations, asteroids, and transits require cadence, not just depth.",phenomenon="The same target can be missed or misunderstood if the observing cadence samples the wrong timescale.",concepts=["cadence", "period", "aliasing"],equation="Nyquist-like sampling requires cadence faster than the event timescale",example="A 2-hour transit cannot be characterized with one image per night.",synthesis="Time is an observing dimension."),
    dict(n=13,title="Uncertainty, Reporting, and Scientific Claims",history="Astronomical papers persuade by connecting calibrated measurements, uncertainty, and claims in a transparent chain.",phenomenon="A result without uncertainty and provenance cannot be evaluated or reproduced.",concepts=["uncertainty", "provenance", "claim strength"],equation="claim strength depends on evidence, uncertainty, and model assumptions",example="A 3-sigma detection may be interesting; a 10-sigma detection with systematics ignored may still be suspect.",synthesis="Good reporting tells readers what was measured, how, and why it should be trusted."),
    dict(n=14,title="Technical Observing Report Workshop",history="Observing proposals and reports are professional genres that turn raw measurements into accountable scientific arguments.",phenomenon="The final report must let another astronomer understand, reproduce, and critique the observation.",concepts=["methods", "results", "limitations"],equation="question -> observation -> reduction -> measurement -> uncertainty -> claim",example="A calibrated light curve report should include target, comparison stars, aperture choices, timing, uncertainty, and limitations.",synthesis="A good observing report is a reproducible argument."),
]

DATASETS = {
    "photometry_standard_stars.csv": [("star","filter","counts","exptime_s","catalog_mag"),("STD-A","V",150000,30,10.21),("STD-B","V",62000,30,11.17),("STD-C","V",24000,30,12.20)],
    "variable_star_lightcurve.csv": [("time_bjd","target_flux","comp_flux"),(0.00,0.995,1.000),(0.05,0.992,1.001),(0.10,0.970,0.999),(0.15,0.955,1.000),(0.20,0.972,1.002),(0.25,0.994,1.001)],
    "asteroid_astrometry.csv": [("image","x_pix","y_pix","ra_deg","dec_deg"),(1,520.3,411.2,132.1021,12.5510),(2,534.7,415.8,132.0988,12.5521),(3,549.1,420.5,132.0954,12.5532)],
    "spectrum_lines.csv": [("line","rest_nm","observed_nm"),("Halpha",656.3,656.9),("Hbeta",486.1,486.55),("OIII",500.7,501.16)],
    "archive_query_sample.csv": [("source_id","g_mag","bp_rp","parallax_mas","parallax_error_mas"),(1,12.1,0.8,5.1,0.2),(2,15.3,2.1,1.2,0.5),(3,10.7,0.3,8.8,0.1)],
}

VISUALS = {1:"detector-chain",2:"airmass",3:"calibration",4:"snr",5:"aperture",6:"lightcurve",7:"astrometry",8:"spectrum",9:"redshift",10:"archive",11:"stacking",12:"cadence",13:"uncertainty",14:"report"}

def page(title, body, css=CSS):
    return f"<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'><title>{escape(title)}</title><script id='MathJax-script' async src='https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'></script><style>{css}</style></head><body>{body}</body></html>"

def li(items): return ''.join(f"<li>{escape(str(x))}</li>" for x in items)

def svg(item):
    key=VISUALS[item['n']]
    return f"<svg viewBox='0 0 960 560' role='img' aria-label='{escape(item['title'])} diagram'><rect width='960' height='560' fill='#fbfcfd'/><text x='42' y='58' font-size='30' fill='#102a43' font-family='Segoe UI, sans-serif'>{escape(item['title'])}</text><rect x='110' y='160' width='180' height='120' rx='16' fill='#0f6b78' opacity='.82'/><rect x='390' y='160' width='180' height='120' rx='16' fill='#b87911' opacity='.82'/><rect x='670' y='160' width='180' height='120' rx='16' fill='#102a43' opacity='.82'/><path d='M290 220 L390 220 M570 220 L670 220' stroke='#5b6773' stroke-width='5'/><text x='130' y='345' font-size='22' fill='#102a43' font-family='Segoe UI, sans-serif'>raw data</text><text x='402' y='345' font-size='22' fill='#102a43' font-family='Segoe UI, sans-serif'>{escape(key)}</text><text x='690' y='345' font-size='22' fill='#102a43' font-family='Segoe UI, sans-serif'>claim</text><text x='42' y='510' font-size='19' fill='#5b6773' font-family='Segoe UI, sans-serif'>{escape(item['synthesis'])}</text></svg>"

def slide(item):
    body=f"""<main class='deck'><section class='slide title'><p class='kicker'>ASTR 210 · Lecture {item['n']:02d}</p><h1>{escape(item['title'])}</h1><h2>Measurement, calibration, uncertainty</h2></section><section class='slide'><h2>Why This Matters</h2><p>{escape(item['history'])}</p></section><section class='slide'><h2>Learning Goals</h2><ul>{li([item['synthesis'],'Use the relevant quantitative method with units and assumptions.','Report uncertainty and provenance.'])}</ul></section><section class='slide'><h2>Opening Phenomenon</h2><p>{escape(item['phenomenon'])}</p></section><section class='slide'><h2>Key Concepts</h2><div class='three'>{''.join(f'<article class="card"><p>{escape(c)}</p></article>' for c in item['concepts'])}</div></section><section class='slide'><h2>Evidence and Failure Modes</h2><ul>{li(['What does the instrument measure directly?','Which calibration changes the numerical value?','Which systematic could mimic the signal?'])}</ul></section><section class='slide'><h2>Visual Reasoning</h2><div class='grid'><div><p>Follow the chain from raw measurement to calibrated claim.</p></div><figure>{svg(item)}<figcaption>{escape(item['title'])}: original workflow diagram for the measurement chain.</figcaption></figure></div></section><section class='slide'><h2>Quantitative Tool</h2><div class='equation'>\\[ {escape(item['equation'])} \\]</div><p>{escape(item['example'])}</p></section><section class='slide'><h2>Worked Reasoning</h2><p>{escape(item['worked'])}</p></section><section class='slide'><h2>Common Pitfall</h2><p class='warning'>{escape(item['pitfall'])}</p></section><section class='slide'><h2>Activity Prompt</h2><p>{escape(item['activity'])}</p></section><section class='slide'><h2>Synthesis</h2><p>{escape(item['synthesis'])}</p></section><section class='slide'><h2>References and Credits</h2><ul>{li(['OpenStax Astronomy 2e instrumentation and light chapters.', 'Astropy and observatory documentation where software is used.', 'Original workflow diagram generated for this course.'])}</ul></section></main>"""
    return page(f"ASTR 210 Lecture {item['n']:02d} Slides", body, SLIDE_CSS)

def notes(item):
    body=f"<header><div><h1>Lecture {item['n']:02d}: {escape(item['title'])}</h1><p>ASTR 210 Observational Astronomy and Data Reduction</p></div></header><main><section><h2>Context</h2><p>{escape(item['history'])}</p></section><section><h2>Measurement Problem</h2><p>{escape(item['phenomenon'])}</p></section><section><h2>Method</h2><p>{escape(item['worked'])}</p></section><section><h2>Quantitative Tool</h2><p>Use the rendered equation from the slide deck, preserve units, and state assumptions.</p></section><section><h2>Study Questions</h2><ol>{li([item['synthesis'],'What calibration or systematic matters most?', 'How would you validate the result?'])}</ol></section></main>"
    return page(f"ASTR 210 Lecture {item['n']:02d} Notes", body)

def lab(n,title,datafile,focus):
    body=f"<header><div><h1>Lab {n:02d}: {escape(title)}</h1><p>{escape(focus)}</p></div></header><main><section><h2>Materials and Data</h2><ul>{li([f'Dataset: ../data/{datafile}', 'Spreadsheet or Python notebook', 'Calculator and lab notebook'])}</ul></section><section><h2>Apparatus and Setup</h2><ul>{li(['Open the CSV and inspect columns/units.', 'Record data provenance from data/README.md.', 'Set up a calculation table before analysis.'])}</ul></section><section><h2>Procedure</h2><ol>{li(['Load the dataset.', 'Compute the required calibrated quantity.', 'Estimate uncertainty or identify dominant systematic.', 'Make one plot or annotated table.', 'Write an evidence-based conclusion.'])}</ol></section><section><h2>Measurement Record</h2><table><tr><th>quantity</th><th>value</th><th>uncertainty</th><th>unit</th><th>note</th></tr><tr><td>&nbsp;</td><td></td><td></td><td></td><td></td></tr></table></section><section><h2>Deliverables</h2><ul>{li(['Completed calculation table', 'One plot or annotated result', 'Short conclusion with uncertainty', 'Source/provenance note'])}</ul></section><section><h2>Assessment Criteria</h2><ul>{li(['Correct method and units', 'Uncertainty/systematic addressed', 'Plot/table is readable', 'Conclusion follows from evidence'])}</ul></section></main>"
    return page(f"ASTR 210 Lab {n:02d}", body)

def pset(n,title,focus):
    body=f"<header><div><h1>Problem Set {n:02d}: {escape(title)}</h1><p>{escape(focus)}</p></div></header><main><section><h2>Problems</h2>{''.join(f'<article class="problem"><h3>{i}. {escape(h)} <span class="points">15 points</span></h3><p>{escape(p)}</p></article>' for i,(h,p) in enumerate([('Calibration calculation','Compute the calibrated quantity from supplied counts and calibration terms. Show units and assumptions.'),('Uncertainty budget','Identify random and systematic terms and decide which dominates.'),('Data interpretation','Interpret a small table or plot and separate measurement from inference.'),('Reduction critique','Find one flaw in a proposed observing/reduction plan and fix it.')],1))}</section><section><h2>OpenStax Companion Practice</h2><p>Use source indexes to verify exact companion readings/problems before instructional assignment.</p></section></main>"
    return page(f"ASTR 210 Problem Set {n:02d}", body)

def sol(n,title):
    body=f"<header><div><h1>Problem Set {n:02d} Solution Key</h1></div></header><main><section><h2>Worked Solutions</h2>{''.join(f'<article class="problem"><h3>{i}. {escape(h)}</h3><p>{escape(s)}</p><table><tr><th>Criterion</th><th>Points</th></tr><tr><td>Model/setup</td><td>5</td></tr><tr><td>Calculation/evidence</td><td>5</td></tr><tr><td>Interpretation/uncertainty</td><td>5</td></tr></table><p><strong>Common errors:</strong> missing units, confusing calibrated and raw quantities, or ignoring systematics.</p></article>' for i,(h,s) in enumerate([('Calibration calculation','Subtract offsets, divide or scale by calibration terms, then interpret the calibrated quantity.'),('Uncertainty budget','Combine independent random terms in quadrature; discuss systematics separately.'),('Data interpretation','A valid interpretation names what is measured and what is inferred.'),('Reduction critique','A strong critique identifies a specific missing calibration, cadence, target constraint, or provenance issue.')],1))}</section><section><h2>OpenStax Companion Practice Notes</h2><p>Recommendations should be verified against the adopted source index before instructional release.</p></section></main>"
    return page(f"ASTR 210 Problem Set {n:02d} Solutions", body)

def assess(n,title): return f"# Assessment Instructions: Problem Set {n:02d} - {title}\n\n## Inputs to Inspect\nStudent submission, problem set, solution key, relevant lecture slides/notes.\n\n## Grading Standard\nPrioritize correct calibration logic, units, uncertainty, provenance, and interpretation.\n\n## Problem-Level Criteria\nAward credit for setup, calculation/evidence, uncertainty, and communication.\n\n## Feedback Requirements\nSeparate arithmetic slips from conceptual errors and give revision guidance.\n\n## Integrity and Evidence Checks\nFlag unsupported claims, missing units, fabricated sources, and unreproducible calculations.\n\n## Resubmission Pathway\nRevisions may improve mastery and grade when accompanied by a change note.\n"

def main():
    for p in [LECTURES,LABS,PSETS,DATA,SRC,ASSETS]: p.mkdir(parents=True, exist_ok=True)
    for name, rows in DATASETS.items():
        with (DATA/name).open('w', newline='', encoding='utf-8') as f: csv.writer(f).writerows(rows)
    (DATA/'README.md').write_text('# ASTR 210 Data\n\nSynthetic teaching datasets for photometry, astrometry, spectroscopy, archive queries, and observing calculations. Generated for review release; replace with local/real data before instructional use if desired.\n', encoding='utf-8')
    (SRC/'README.md').write_text('# ASTR 210 Source\n\nScripts for generating and validating ASTR 210 artifacts.\n', encoding='utf-8')
    for item in LECTURES:
        n=item['n']; (LECTURES/f'lecture-{n:02d}-slides.html').write_text(slide(item), encoding='utf-8'); (LECTURES/f'lecture-{n:02d}-notes.html').write_text(notes(item), encoding='utf-8')
    labs=[(1,'Detector Calibration','photometry_standard_stars.csv','Calibrate raw counts and compute a zero point.'),(2,'Signal-to-Noise Budget','photometry_standard_stars.csv','Estimate SNR and limiting magnitude.'),(3,'Aperture Photometry','photometry_standard_stars.csv','Measure instrumental magnitudes and compare standards.'),(4,'Differential Light Curve','variable_star_lightcurve.csv','Compute differential magnitudes and detect variability.'),(5,'Astrometry and Motion','asteroid_astrometry.csv','Estimate asteroid motion and positional uncertainty.'),(6,'Spectroscopic Wavelength Calibration','spectrum_lines.csv','Compute radial velocity from shifted lines.'),(7,'Archive Query Reproducibility','archive_query_sample.csv','Filter a catalog sample and document selection effects.')]
    for args in labs: (LABS/f'lab-{args[0]:02d}.html').write_text(lab(*args), encoding='utf-8')
    psets=[(1,'Planning and Calibration','Translate observing plans into calibration requirements.'),(2,'Noise and Photometry','Quantify noise, signal, and instrumental magnitudes.'),(3,'Light Curves and Astrometry','Analyze time-domain and positional data.'),(4,'Spectroscopy','Calibrate wavelengths and infer radial velocities.'),(5,'Archives and Selection Effects','Document queries and selection functions.'),(6,'Stacking and Time-Domain Strategy','Reason about registration, cadence, and SNR.'),(7,'Technical Observing Report','Assemble calibrated evidence into a reproducible claim.')]
    for n,title,focus in psets:
        (PSETS/f'problem-set-{n:02d}.html').write_text(pset(n,title,focus), encoding='utf-8'); (PSETS/f'problem-set-{n:02d}-solutions.html').write_text(sol(n,title), encoding='utf-8'); (PSETS/f'problem-set-{n:02d}-assessment.md').write_text(assess(n,title), encoding='utf-8')
    (ROOT/'README.md').write_text('# ASTR 210: Observational Astronomy and Data Reduction\n\nStatus: needs correction pending review; not yet approved for instructional use.\n', encoding='utf-8')
    (ROOT/'syllabus.html').write_text(page('ASTR 210 Syllabus', f"<header><div><h1>ASTR 210: Observational Astronomy and Data Reduction</h1><p>4 credits · Prerequisites: {escape(COURSE['prerequisites'])}</p></div></header><main><section><h2>Description</h2><p>{escape(COURSE['description'])}</p></section><section><h2>Assessment</h2><table><tr><th>Component</th><th>Weight</th></tr><tr><td>Labs</td><td>35%</td></tr><tr><td>Problem sets</td><td>30%</td></tr><tr><td>Technical observing report</td><td>25%</td></tr><tr><td>Participation</td><td>10%</td></tr></table></section></main>"), encoding='utf-8')
    rows=''.join(f"<tr><td>{x['n']}</td><td>{escape(x['title'])}</td><td>{escape(x['synthesis'])}</td></tr>" for x in LECTURES)
    (ROOT/'schedule.html').write_text(page('ASTR 210 Schedule', f"<header><div><h1>ASTR 210 Schedule</h1></div></header><main><table><thead><tr><th>Week</th><th>Lecture</th><th>Focus</th></tr></thead><tbody>{rows}</tbody></table></main>"), encoding='utf-8')
    (ROOT/'reference-log.md').write_text('# ASTR 210 Reference Log\n\n| Artifact | Item | Source Type | Source | Status | Notes |\n|---|---|---|---|---|---|\n| all | OpenStax Astronomy 2e | textbook | references/openstax-astronomy-2e.pdf | VERIFIED | Local reference copy. |\n| labs | Synthetic teaching datasets | generated data | materials/ASTR210/data/*.csv | VERIFIED | Generated for review release; provenance in data README. |\n| slides | Original workflow diagrams | generated SVG | lecture slide files | VERIFIED | Original course diagrams generated locally. |\n', encoding='utf-8')
    (ROOT/'course-manifest.json').write_text(json.dumps({'course':COURSE,'status':{'stage':'needs correction pending review','reviewStatus':'Needs correction pending review; not approved for instructional use','lastUpdated':'2026-09-24'},'counts':{'slides':14,'notes':14,'labs':7,'problemSets':7,'solutionKeys':7,'assessmentInstructions':7}}, indent=2)+'\n', encoding='utf-8')
    (ROOT/'review-report.md').write_text('# ASTR 210 Course Materials Review Report\n\nStatus: Needs correction pending review; not yet approved for instructional use.\n', encoding='utf-8')
    lecture_links=''.join(f"<li><a href='lectures/lecture-{i:02d}-slides.html'>Lecture {i:02d} slides</a> · <a href='lectures/lecture-{i:02d}-notes.html'>notes</a></li>" for i in range(1,15)); lab_links=''.join(f"<li><a href='labs/lab-{i:02d}.html'>Lab {i:02d}</a></li>" for i in range(1,8)); ps_links=''.join(f"<li><a href='problem-sets/problem-set-{i:02d}.html'>Problem Set {i:02d}</a> · <a href='problem-sets/problem-set-{i:02d}-solutions.html'>solutions</a> · <a href='problem-sets/problem-set-{i:02d}-assessment.md'>assessment</a></li>" for i in range(1,8))
    (ROOT/'index.html').write_text(page('ASTR 210 Course Materials', f"<header><div><h1>ASTR 210: Observational Astronomy and Data Reduction</h1><p>Review-release candidate</p></div></header><main><section class='notice'><p><strong>Status:</strong> Needs correction pending review; not yet approved for instructional use.</p></section><section><h2>Planning</h2><ul>{li(['Syllabus: syllabus.html','Schedule: schedule.html','Reference log: reference-log.md','Review report: review-report.md'])}</ul></section><section><h2>Lectures</h2><ul>{lecture_links}</ul></section><section><h2>Labs</h2><ul>{lab_links}</ul></section><section><h2>Problem Sets</h2><ul>{ps_links}</ul></section></main>"), encoding='utf-8')
if __name__ == '__main__': main()
